### ISSUE TITLE
Instrumentation key is not working with key vault

### ISSUE THREAD

**Issue by MelleD** [microsoft/ApplicationInsights-Java#884] opened 2019-03-28 13:54 UTC
Iam not sure if this a issue of this project or this one (https://github.com/Microsoft/azure-spring-boot/blob/master/azure-spring-boot-starters/azure-keyvault-secrets-spring-boot-starter/README.md). Maybe a combination.

I set directly some properties (e.g.  spring.datasource.url) into a key vault. 
So far this has always worked. But for the application insights instrumentation key this is not working. For the ai logback appender it works. I see some traces, but the telematic configuration throws this exception.

The  `azure.application-insights.instrumentation-key` is converted to the key vault name `azure-applicationInsights-instrumentationKey`

```
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'telemetryConfiguration' defined in class path resource [com/microsoft/applicationinsights/autoconfigure/ApplicationInsightsTelemetryAutoConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.microsoft.applicationinsights.TelemetryConfiguration]: Factory method 'telemetryConfiguration' threw exception; nested exception is java.lang.IllegalStateException: Instrumentation Key must be set to report telemetry
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:625)
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:605)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1288)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1127)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:538)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:498)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:320)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:318)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:307)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199)
	at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:273)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1239)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1166)
	at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:855)
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:758)
	... 50 common frames omitted
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.microsoft.applicationinsights.TelemetryConfiguration]: Factory method 'telemetryConfiguration' threw exception; nested exception is java.lang.IllegalStateException: Instrumentation Key must be set to report telemetry
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:185)
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:620)
	... 66 common frames omitted
Caused by: java.lang.IllegalStateException: Instrumentation Key must be set to report telemetry
	at com.microsoft.applicationinsights.autoconfigure.ApplicationInsightsProperties.getInstrumentationKey(ApplicationInsightsProperties.java:105)
	at com.microsoft.applicationinsights.autoconfigure.ApplicationInsightsTelemetryAutoConfiguration.telemetryConfiguration(ApplicationInsightsTelemetryAutoConfiguration.java:131)
	at com.microsoft.applicationinsights.autoconfigure.ApplicationInsightsTelemetryAutoConfiguration$$EnhancerBySpringCGLIB$$5ffb93c3.CGLIB$telemetryConfiguration$4(<generated>)
	at com.microsoft.applicationinsights.autoconfigure.ApplicationInsightsTelemetryAutoConfiguration$$EnhancerBySpringCGLIB$$5ffb93c3$$FastClassBySpringCGLIB$$45b83ebe.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:244)
	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:363)
	at com.microsoft.applicationinsights.autoconfigure.ApplicationInsightsTelemetryAutoConfiguration$$EnhancerBySpringCGLIB$$5ffb93c3.telemetryConfiguration(<generated>)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154)
	... 67 common frames omitted
```

I think there is a bug with the dash handling in a property class, because this works
```
  String iKey = context.getEnvironment().getProperty("azure.application-insights.instrumentation-key");
    if (StringUtils.isNoneBlank(iKey)) {
      return new ConditionOutcome(true, ConditionMessage.of("instrumentation key found"));
    }
```
but the property is not set in the class (think is the dash in the prefix)
```
@ConfigurationProperties("azure.application-insights")
public class ApplicationInsightsProperties {
```

**Comment by dhaval24** [comment] 2019-03-28 16:20
> The `azure.application-insights.instrumentation-key` is converted to the key vault name `azure-applicationInsights-instrumentationKey`

@SirWayne I am not sure if I fully understand this. From the stack trace I am not seeing this conversion. 

The best way to debug here can be to have a small repro of the scenario.

**Comment by SirWayne** [comment] 2019-03-28 17:55
You need an key vault on azure to reproduce this bug.
It's simple take the azure key vault starter + the insights starter and add the instrumenation key into  a key vault instead of the application.properties.

In key vault names you cannot use dots see the IMPORTANT part here https://github.com/Microsoft/azure-spring-boot/blob/master/azure-spring-boot-starters/azure-keyvault-secrets-spring-boot-starter/README.md

So have to convert the property names.

**Comment by dhaval24** [comment] 2019-03-28 20:16
@SirWayne thanks. I will try to reproduce this locally and update the issue as per the findings.

**Comment by SirWayne** [comment] 2019-03-29 08:56
It's not a big issue for us, because now we set the env `APPLICATION_INSIGHTS_IKEY ` in the kubernetes secret instead of a key vault.

This works.

**Comment by dhaval24** [comment] 2019-03-29 15:47
@SirWayne got it. Thanks for the update. Probably worth while to create a issue on https://github.com/Microsoft/azure-spring-boot/blob/master/azure-spring-boot-starters/azure-keyvault-secrets-spring-boot-starter repo as this seems to be a fundamental design concern of keyvault. Given that we already have a dash in the syntax of the property (`azure.application-insights.instrumentation-key`) it would be hard to change this without a major version upgrade and prevent breaking customers.

cc @incarnation-p-lee

**Comment by SirWayne** [comment] 2019-03-29 15:59
Yes i don't like the conversion. It would be better, that we can use dots for a key vault name

**Comment by SirWayne** [comment] 2019-05-27 06:06
@dhaval24 @Incarnation-p-lee 
Is there an update to this issue?

**Comment by Incarnation-p-lee** [comment] 2019-05-28 02:50
@SirWayne
Sorry for just noticing this issue. There is one question about how you use keyvault secrets starter ? Can u add secret with name `spring.datasource.ur` to keyvault ？

**Comment by SirWayne** [comment] 2019-05-28 08:01
@Incarnation-p-lee no, this is not possible. You have to use `spring-datasource-url` but this convention is very confusing and you cannot use all combintation see key `azure.application-insights.instrumentation-key`, which is not working.

Error is in key vault is:
```
Please provide a valid secret name. Secret names can only contain alphanumeric characters and dashes.
```

**Comment by Incarnation-p-lee** [comment] 2019-05-28 15:28
@SirWayne 
That may be the restriction from keyvault secrets names, take your example, you cannot add `azure.application-insights.instrumentation-key` as keyvault secret name. Only `azure-applicationInsights-instrumentationKey` is valid, and respectively property `azure.applicationinsights.instrumentationkey` will be generated from property source. If you insist to keep '-' in property, it is hardly to tell where should I convert the secret to property.

**Comment by SirWayne** [comment] 2019-05-29 07:38
Yes so you have to discuss with your key vault team about this restriction, because this will not work with spring boot properties. How i said you cannot use `applicationInsights-instrumentationKey` this will not work.

For me this is a Microsoft issue, you cannot fix this in the `azure-keyvault-secrets-spring-boot-starter`. I think you should discuss this with your key vault team about the `.` restriction.

**Comment by estaylorco** [comment] 2020-04-29 20:24
I just want to affirm that this really is a problem.  It is safe to safe that Azure Key Vault does _not_ support Spring Boot.  Until this problem of dots and dashes is fixed, please pull from the documentation and marketing materials any indication that Key Vault supports Spring Boot.  Thank you.

**Comment by simon-an** [comment] 2020-06-04 12:43
I can confirm that azure application-insights and azure keyvault are working together.
Tested with:
azure-keyvault-secrets-spring-boot-starter version 2.2.1
applicationinsights-spring-boot-starter version 2.6.1
spring boot 2.2.6.RELEASE

Keyvault Secret Name:  **azure-applicationinsights-instrumentationkey**

**Comment by trask** [comment] 2021-01-05 02:04
Closing, please open a new issue if you are still having this issue.

**Closed by trask** 2021-01-05 02:04 UTC
Labels: Spring Boot Starter, Team-Triaged
