### ISSUE TITLE
AI SDK unstable performance at startup

### ISSUE THREAD

**Issue by xscript** [Microsoft/ApplicationInsights-Java#474] opened 2017-11-30 14:43 UTC
Right now, we are using AI SDK to instrument Maven Plugins for Azure. Instrumentation key is put in `ApplicationInsights.xml` as the official document says.
However, we observe some serious performance issue with some users (both on Windows and macOS). Sometimes it took tens of seconds to initialize the AI client. After removing AI, our maven goals just finish within a second.
Below is an example we are seeing recently.
![perf](https://user-images.githubusercontent.com/2300784/33436419-ef53faf6-d61f-11e7-811a-6ef1f08466fc.gif)

Do you guys realize this issue? Any recommendation to improve AI client startup performance?
Thanks!

**Comment by grlima** [comment] 2017-11-30 16:19
@xscript - we haven't seen such issues. Could you please enable extra logging by adding the following tag to the ApplicationInsights.xml file, inside the root <ApplicationInsights> tag: <SDKLogger></SDKLogger> ?

**Comment by dhaval24** [comment] 2017-11-30 16:20
@xscript the tag would be <SDKLogger /> in ApplicationInsights.xml

**Comment by dhaval24** [comment] 2017-11-30 16:22
@xscript Also just to exclude the possibilities of other Java jobs taking bunch of priority, can you perform the same experiment where only a single java process is running which is above one? This will help to narrow down the issue if there is one.

**Comment by jdneo** [comment] 2017-12-01 07:29
Hi @dhaval24 

We use AI in our maven plugin. I exclude all the actions in MOJO's execution method. Here is the log:

```
[INFO] Scanning for projects...
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] Building Azure Java Functions 1.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- azure-functions-maven-plugin:0.1.8-SNAPSHOT:add (default-cli) @ artifactgid ---
AI: INFO 01-12-2017 15:21, 1: Configuration file has been successfully found as resource
AI: INFO 01-12-2017 15:21, 1: 'MaxTelemetryBufferCapacity': null value is replaced with '500'
AI: INFO 01-12-2017 15:21, 1: 'FlushIntervalInSeconds': null value is replaced with '5'
AI: TRACE 01-12-2017 15:21, 1: Using Http Client version 4.3+
AI: INFO 01-12-2017 15:21, 1: 'Channel.MaxTransmissionStorageCapacityInMB': null value is replaced with '10'
AI: TRACE 01-12-2017 15:21, 1: Windows performance counters are not relevant on this OS.
AI: INFO 01-12-2017 15:21, 1: Configuration file has been successfully found as resource
AI: INFO 01-12-2017 15:21, 1: 'MaxTelemetryBufferCapacity': null value is replaced with '500'
AI: INFO 01-12-2017 15:21, 1: 'FlushIntervalInSeconds': null value is replaced with '5'
AI: INFO 01-12-2017 15:21, 1: 'Channel.MaxTransmissionStorageCapacityInMB': null value is replaced with '10'
AI: TRACE 01-12-2017 15:21, 1: Windows performance counters are not relevant on this OS.
AI: TRACE 01-12-2017 15:21, 1: Registering PC 'DeadLockDetector'
AI: TRACE 01-12-2017 15:21, 1: Registering PC 'JvmHeapMemoryUsedPerformanceCounter'
AI: ERROR 01-12-2017 15:21, 1: Performance Counter JSDK_ProcessIOPerformanceCounter: Error in file '/proc/29987/io': Can not read
AI: ERROR 01-12-2017 15:21, 1: Performance Counter JSDK_TotalCpuPerformanceCounter: Error in file '/proc/stat': Can not read
AI: ERROR 01-12-2017 15:21, 1: Performance Counter JSDK_TotalMemoryPerformanceCounter: Error in file '/proc/meminfo': Can not read
AI: TRACE 01-12-2017 15:21, 1: Registering PC 'JSDK_ProcessMemoryPerformanceCounter'
AI: TRACE 01-12-2017 15:21, 1: Registering PC 'JSDK_ProcessCpuPerformanceCounter'
AI: TRACE 01-12-2017 15:21, 1: Registering PC 'JSDK_ProcessIOPerformanceCounter'
AI: TRACE 01-12-2017 15:21, 1: Registering PC 'JSDK_TotalCpuPerformanceCounter'
AI: TRACE 01-12-2017 15:21, 1: Registering PC 'JSDK_TotalMemoryPerformanceCounter'
AI: TRACE 01-12-2017 15:21, 1: Registering PC 'DeadLockDetector'
AI: TRACE 01-12-2017 15:21, 1: Failed to store performance counter 'DeadLockDetector', since there is already one
AI: TRACE 01-12-2017 15:21, 1: Registering PC 'JvmHeapMemoryUsedPerformanceCounter'
AI: TRACE 01-12-2017 15:21, 1: Failed to store performance counter 'JvmHeapMemoryUsedPerformanceCounter', since there is already one
AI: ERROR 01-12-2017 15:21, 1: Performance Counter JSDK_ProcessIOPerformanceCounter: Error in file '/proc/29987/io': Can not read
AI: ERROR 01-12-2017 15:21, 1: Performance Counter JSDK_TotalCpuPerformanceCounter: Error in file '/proc/stat': Can not read
AI: ERROR 01-12-2017 15:21, 1: Performance Counter JSDK_TotalMemoryPerformanceCounter: Error in file '/proc/meminfo': Can not read
AI: TRACE 01-12-2017 15:21, 1: Registering PC 'JSDK_ProcessMemoryPerformanceCounter'
AI: TRACE 01-12-2017 15:21, 1: Failed to store performance counter 'JSDK_ProcessMemoryPerformanceCounter', since there is already one
AI: TRACE 01-12-2017 15:21, 1: Registering PC 'JSDK_ProcessCpuPerformanceCounter'
AI: TRACE 01-12-2017 15:21, 1: Failed to store performance counter 'JSDK_ProcessCpuPerformanceCounter', since there is already one
AI: TRACE 01-12-2017 15:21, 1: Registering PC 'JSDK_ProcessIOPerformanceCounter'
AI: TRACE 01-12-2017 15:21, 1: Failed to store performance counter 'JSDK_ProcessIOPerformanceCounter', since there is already one
AI: TRACE 01-12-2017 15:21, 1: Registering PC 'JSDK_TotalCpuPerformanceCounter'
AI: TRACE 01-12-2017 15:21, 1: Failed to store performance counter 'JSDK_TotalCpuPerformanceCounter', since there is already one
AI: TRACE 01-12-2017 15:21, 1: Registering PC 'JSDK_TotalMemoryPerformanceCounter'
AI: TRACE 01-12-2017 15:21, 1: Failed to store performance counter 'JSDK_TotalMemoryPerformanceCounter', since there is already one
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 3.002 s
[INFO] Finished at: 2017-12-01T15:21:46+08:00
[INFO] Final Memory: 38M/294M
[INFO] ------------------------------------------------------------------------
AI: ERROR 01-12-2017 15:21, 20: Failed to send, unexpected error: com/microsoft/applicationinsights/core/dependencies/http/impl/execchain/RequestEntityProxy
AI: ERROR 01-12-2017 15:21, 19: Failed to send, unexpected error: com/microsoft/applicationinsights/core/dependencies/http/impl/execchain/RequestEntityProxy
AI: ERROR 01-12-2017 15:21, 19: Failed to send, unexpected error: com/microsoft/applicationinsights/core/dependencies/http/impl/execchain/RequestEntityProxy
AI: ERROR 01-12-2017 15:21, 20: Failed to send, unexpected error: com/microsoft/applicationinsights/core/dependencies/http/impl/execchain/RequestEntityProxy
AI: ERROR 01-12-2017 15:21, 20: Failed to send, unexpected error: com/microsoft/applicationinsights/core/dependencies/http/impl/execchain/RequestEntityProxy
AI: ERROR 01-12-2017 15:21, 20: Failed to send, unexpected error: com/microsoft/applicationinsights/core/dependencies/http/impl/execchain/RequestEntityProxy
AI: ERROR 01-12-2017 15:21, 20: Failed to send, unexpected error: com/microsoft/applicationinsights/core/dependencies/http/impl/execchain/RequestEntityProxy
AI: ERROR 01-12-2017 15:21, 20: Failed to send, unexpected error: com/microsoft/applicationinsights/core/dependencies/http/impl/execchain/RequestEntityProxy
AI: ERROR 01-12-2017 15:21, 20: Failed to send, unexpected error: com/microsoft/applicationinsights/core/dependencies/http/impl/execchain/RequestEntityProxy
AI: ERROR 01-12-2017 15:21, 20: Failed to send, unexpected error: com/microsoft/applicationinsights/core/dependencies/http/impl/execchain/RequestEntityProxy
AI: ERROR 01-12-2017 15:21, 20: Failed to send, unexpected error: com/microsoft/applicationinsights/core/dependencies/http/impl/execchain/RequestEntityProxy
AI: ERROR 01-12-2017 15:21, 20: Failed to send, unexpected error: com/microsoft/applicationinsights/core/dependencies/http/impl/execchain/RequestEntityProxy
AI: ERROR 01-12-2017 15:21, 20: Failed to send, unexpected error: com/microsoft/applicationinsights/core/dependencies/http/impl/execchain/RequestEntityProxy
AI: ERROR 01-12-2017 15:21, 20: Failed to send, unexpected error: com/microsoft/applicationinsights/core/dependencies/http/impl/execchain/RequestEntityProxy
AI: ERROR 01-12-2017 15:21, 20: Failed to send, unexpected error: com/microsoft/applicationinsights/core/dependencies/http/impl/execchain/RequestEntityProxy
AI: ERROR 01-12-2017 15:21, 20: Failed to send, unexpected error: com/microsoft/applicationinsights/core/dependencies/http/impl/execchain/RequestEntityProxy
AI: ERROR 01-12-2017 15:21, 20: Failed to send, unexpected error: com/microsoft/applicationinsights/core/dependencies/http/impl/execchain/RequestEntityProxy
AI: ERROR 01-12-2017 15:21, 20: Failed to send, unexpected error: com/microsoft/applicationinsights/core/dependencies/http/impl/execchain/RequestEntityProxy
AI: ERROR 01-12-2017 15:21, 20: Failed to send, unexpected error: com/microsoft/applicationinsights/core/dependencies/http/impl/execchain/RequestEntityProxy
AI: ERROR 01-12-2017 15:21, 20: Failed to send, unexpected error: com/microsoft/applicationinsights/core/dependencies/http/impl/execchain/RequestEntityProxy
AI: ERROR 01-12-2017 15:21, 20: Failed to send, unexpected error: com/microsoft/applicationinsights/core/dependencies/http/impl/execchain/RequestEntityProxy
AI: ERROR 01-12-2017 15:21, 20: Failed to send, unexpected error: com/microsoft/applicationinsights/core/dependencies/http/impl/execchain/RequestEntityProxy
AI: ERROR 01-12-2017 15:21, 20: Failed to send, unexpected error: com/microsoft/applicationinsights/core/dependencies/http/impl/execchain/RequestEntityProxy
AI: ERROR 01-12-2017 15:21, 20: Failed to send, unexpected error: com/microsoft/applicationinsights/core/dependencies/http/impl/execchain/RequestEntityProxy
AI: ERROR 01-12-2017 15:21, 19: Failed to send, unexpected error: com/microsoft/applicationinsights/core/dependencies/http/impl/execchain/RequestEntityProxy
AI: ERROR 01-12-2017 15:21, 20: Failed to send, unexpected error: com/microsoft/applicationinsights/core/dependencies/http/impl/execchain/RequestEntityProxy
AI: ERROR 01-12-2017 15:21, 19: Failed to send, unexpected error: com/microsoft/applicationinsights/core/dependencies/http/impl/execchain/RequestEntityProxy
AI: ERROR 01-12-2017 15:21, 20: Failed to send, unexpected error: com/microsoft/applicationinsights/core/dependencies/http/impl/execchain/RequestEntityProxy
AI: ERROR 01-12-2017 15:21, 19: Failed to send, unexpected error: com/microsoft/applicationinsights/core/dependencies/http/impl/execchain/RequestEntityProxy
AI: ERROR 01-12-2017 15:21, 20: Failed to send, unexpected error: com/microsoft/applicationinsights/core/dependencies/http/impl/execchain/RequestEntityProxy
AI: ERROR 01-12-2017 15:21, 20: Failed to send, unexpected error: com/microsoft/applicationinsights/core/dependencies/http/impl/execchain/RequestEntityProxy
AI: ERROR 01-12-2017 15:21, 20: Failed to send, unexpected error: com/microsoft/applicationinsights/core/dependencies/http/impl/execchain/RequestEntityProxy
AI: ERROR 01-12-2017 15:21, 20: Failed to send, unexpected error: com/microsoft/applicationinsights/core/dependencies/http/impl/execchain/RequestEntityProxy
AI: ERROR 01-12-2017 15:21, 20: Failed to send, unexpected error: com/microsoft/applicationinsights/core/dependencies/http/impl/execchain/RequestEntityProxy
AI: ERROR 01-12-2017 15:21, 20: Failed to send, unexpected error: com/microsoft/applicationinsights/core/dependencies/http/impl/execchain/RequestEntityProxy
AI: ERROR 01-12-2017 15:21, 20: Failed to send, unexpected error: com/microsoft/applicationinsights/core/dependencies/http/impl/execchain/RequestEntityProxy
AI: ERROR 01-12-2017 15:21, 19: Failed to send, unexpected error: 
......
```

The
```
com/microsoft/applicationinsights/core/dependencies/http/impl/execchain/RequestEntityProxy
AI: ERROR 01-12-2017 15:21, 19: Failed to send, unexpected error: 
```
just repeat a lot of times at the end.

**Comment by dhaval24** [comment] 2017-12-01 16:08
@jdneo these logs look very surprising. I haven't seen this kind of behavior in our SDK. Couple of quick questions:
1. Are you using AI in some proxy network?
2. Is this application running under some constrained network or container.
3. Is it possible for you to outline the detailed steps for us to replicate the problem on our end? i.e steps to setup a similar application on our end.

Essentially what I am seeing here is that there is some issue pushing telemetry items to the network and hence the SDK is trying to retry to send it after every 5 seconds which is the default until the retry attempts get exhausted and therefore you are seeing the delayed performance issue on instantiating the AI on your application.

**Comment by leikelman** [comment] 2017-12-01 20:42
I have experienced this same behavior.  We are using the application insights SDK inside one of our projects, which is used to monitor APIs.  The first time the telemetry class is initialized it takes much longer to initialize (usually 5-10 seconds), but all subsequent calls do not have this delay.  I thought this was by design, but now questioning this based on the responses above.

**Comment by dhaval24** [comment] 2017-12-01 23:42
@leikelman do you all see the constant retries in the log above as I am not able to replicate this on my end.

**Comment by leikelman** [comment] 2017-12-03 16:51
I will try enabling the additional logging when I am back in the office and let you know the outcome

**Comment by jdneo** [comment] 2017-12-04 00:40
Hi @dhaval24. It's in my company's network. I'm not quite sure whether it has any restrction or not.

**Comment by jdneo** [comment] 2017-12-05 00:58
@dhaval24 Sure. I'll try it when I back to home.

**Comment by dhaval24** [comment] 2017-12-21 17:54
@jdneo @leikelman please refer to #503 and #505 PR which fixes it. This should reduce the startup time significantly.

**Comment by jdneo** [comment] 2017-12-22 03:10
Thank you @dhaval24 . may I ask when and how can I have a try on those fix?

**Comment by dhaval24** [comment] 2017-12-22 06:04
@jdneo you can pull of the feature branch #505 and then build the sdk locally. You need to run the following gradle commands:
gradlew clean, gradlew assemble, gradlew test, gradlew build
The jars would be found inside the respective lib folders of the local cloned repository.

**Comment by dhaval24** [comment] 2017-12-27 22:36
@jdneo were you able to try these changes out? If not also note that these are now merged into the latest master, so you might try pulling and building from the latest master to give it a shot. Let me know how it goes.

**Comment by jdneo** [comment] 2017-12-28 01:38
@dhaval24 

I got error when executing ```.\gradlew assemble```:

```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':core:compileWindowsX64SharedLibraryWindowsCpp'.
> No tool chain is available to build for platform 'x64':
    - Tool chain 'visualCpp' (Visual Studio): Could not locate a Visual Studio installation, using the Windows registry and system path.
    - Tool chain 'gcc' (GNU GCC): Could not find C compiler 'gcc' in system path.
    - Tool chain 'clang' (Clang): Could not find C compiler 'clang' in system path.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED
```

BTW, I'm suing AI SDK in the maven dependency, the version I am using is v1.0.9

Thanks

**Comment by dhaval24** [comment] 2017-12-28 01:56
@jdneo if you are on windows platform you need visual studio 2015 installed with gcc and clang plugins enabled. We have some native dll's which needs these while running gradle assemble.

Further v1.0.9 version of the SDK would definitely have this issues. Even v2.0.0-BETA our latest version had this issue. I have merged the fixes to this issue just today and therefore no public release is out thert yet having this fixes. I just thought, you could give it a try by building it locally and see if there is a perf boost which I am sure should be there.

**Comment by jdneo** [comment] 2017-12-28 02:32
@dhaval24 I have VS 2017 installed, but I have no idea which toolsets I should add into it. Any suggestions?

**Comment by dhaval24** [comment] 2017-12-28 03:14
@jdneo I am not sure never tried with VS 2017. Though in VS 2015, I had visual C++ redistributable both x86 and x64 installed, enabled for gcc and c++ development I believe to the best I can recall but I think should be helpful. Let me know

**Comment by jdneo** [comment] 2018-01-15 04:03
No, I failed to build the jar file. But I can test it after the new version being released.

**Comment by dhaval24** [comment] 2018-06-18 20:29
@jdneo @xscript I would like you to revisit the thread and see if the issue still persists. We have done a bunch of performance optimization for startup time with 2.1.0 and above releases of SDK.

**Comment by jdneo** [comment] 2018-06-19 01:03
@dhaval24 I've tested locally. The performance looks better than `1.0.9` which we are using currently. Thanks

**Comment by dhaval24** [comment] 2018-06-19 14:32
@jdneo thank you very much for the update. I would highly recommend that you please update the SDK from 1.0.9 to 2.1.1 at the very least :)

**Comment by dhaval24** [comment] 2019-01-25 06:17
@jdneo I think the startup performance issues were optimized with all the recent versions of our SDKs. If you still face some issues like this with 2.3.0 version of our SDK please let us know. For now I will close this.

**Closed by dhaval24** 2019-01-25 06:17 UTC
Labels: Performance Issues, question
