### ISSUE TITLE
Spring Boot Logback send no logs to application insights

### ISSUE THREAD

**Issue by SirWayne** [microsoft/ApplicationInsights-Java#880] opened 2019-03-27 09:48 UTC
Currently with logback i see no tracing events in application insights. I use the latest version of the SDK.

My spring logback xml looks like

```
<configuration debug="false">
    <include resource="org/springframework/boot/logging/logback/defaults.xml"/>

    <appender name="aiAppender"
              class="com.microsoft.applicationinsights.logback.ApplicationInsightsAppender">
    </appender>

    <root level="INFO">
        <appender-ref ref="aiAppender"/>
    </root>

</configuration>
```

My pom.xml

```
        <dependency>
            <groupId>com.microsoft.azure</groupId>
            <artifactId>applicationinsights-logging-logback</artifactId>
            <version>2.3.1</version>
        </dependency>
        <dependency>
            <groupId>com.microsoft.azure</groupId>
            <artifactId>applicationinsights-spring-boot-starter</artifactId>
            <version>1.1.2</version>
        </dependency>
```

And set the ky in the application.properties

`azure.application-insights.instrumentation-key`

I set breakpoint at ApplicationInsightsAppender#setInstrumentationKey and saw this method is never executed. But the LogTelemetryClientProxy works without a key and is not broken.

How can i set the key?

**Comment by SirWayne** [comment] 2019-03-27 10:06
Found this solution

```
        <springProperty scope="context" name="INSTRUMENTATION_KEY"
                        source="azure.application-insights.instrumentation-key"/>

        <appender name="aiAppender"
                  class="com.microsoft.applicationinsights.logback.ApplicationInsightsAppender">
            <instrumentationKey>${INSTRUMENTATION_KEY}</instrumentationKey>
        </appender>
```

**Comment by dhaval24** [comment] 2019-03-27 14:10
@SirWayne thanks for opening the issue and mentioning the workaround. It looks like for some reason logback appender is not getting the ikey by default. Workaround should work fine and would be fully functional, however worthwhile for an investigation - why ikey is not getting picked by default.

**Comment by jdubois** [comment] 2019-05-20 15:44
I confirm the issue and the solution!

**Comment by trask** [comment] 2019-08-09 19:06
Thanks all. Closing this, consolidating into #1014.

**Closed by trask** 2019-08-09 19:06 UTC
Labels: Needs Investigation

**Comment by trask** [comment] 2019-08-20 23:33
Hi @jdubois, I'm trying to reproduce this (see my attempt at https://github.com/trask/issue-1014), can you give me any pointers how you were able to repro? Thanks!

**Comment by jdubois** [comment] 2019-08-22 17:26
Hi @trask ! I have generated a sample JHipster microservice at https://github.com/jdubois/application-insights-demo and then applied the same changes as your sample project to it: https://github.com/jdubois/application-insights-demo/commit/defb7b4729b36d350d36fbbc6dc9b30c2012308d

And indeed, that works!!! I'm guessing that in my original logback-spring.xml configuration (see https://github.com/jdubois/application-insights-demo/commit/defb7b4729b36d350d36fbbc6dc9b30c2012308d#diff-892a99aa999cfc571ab82396c32ba5de ) there was something that made the key disappear. As I was using the same versions as you for both the starter and Application Insights, I don't see any other explanation.

I'd love to have a better explanation: I remember I did debug the app, like @dhaval24 , and indeed the method wasn't called. But now I can't reproduce :-(

**Comment by trask** [comment] 2019-08-22 17:31
Thanks for trying :-). It's normal for that method to not get called, but the instrumentation key should then be added when sending the telemetry https://github.com/microsoft/ApplicationInsights-Java/blob/2.4.0/core/src/main/java/com/microsoft/applicationinsights/TelemetryClient.java#L410. Unless the logging appender is stuck in a different class loader and doesn't share the globally configured instrumentation key. But I'm not sure how / why that might be happening with the spring boot starter.

**Comment by jdubois** [comment] 2019-08-23 09:57
There are several different ways to run a JHipster application (see https://www.jhipster.tech/development/#running-java-server ) so maybe there's something there that triggered the issue, but I can't find it...
Another idea: I do use the same library versions as you for Application Insights, but JHipster has been upgraded since my original tests, so maybe some other library was the cause of the issue, and it's fixed now.
