### ISSUE TITLE
HTTP calls via feign clients are not reported as dependencies

### ISSUE THREAD

**Issue by tomaszglinski** [Microsoft/ApplicationInsights-Java#635] opened 2018-04-04 11:35 UTC
I tested both spring feign client as well as direct RestTemplate call, the latter is correctly reported as dependency, feign - not...

Do you have any hints how to enable it?

**Comment by dhaval24** [comment] 2018-04-04 15:14
@tomaszglinski you are experience correct behavior. The dependency collection of rest clients namely SpringRestTemplate and SpringBoot Feign Client depends on the underlying HTTP Library being used. Our current instrumentation instruments ApacheHttpClient. Therefore if the clients use ApacheHttpClient then it should work out. I would recommend using ApacheHttpClient 4.5.3 version if possible.

**Comment by tomaszglinski** [comment] 2018-04-05 07:41
Hi @dhaval24, as you saw in #637  I tried with ApacheHttpClient :)
I agree with your clarification. But I am wondering whether it would not be possible to add a great feature for feign (and feign-like) libs, meaning:
Application call feign using the business name of the called service, for example "users". Under the hood, the calls to "users" mean loadbalanced/retried/circuitbreaked calls to 3 instances of "users" service.
It would be great to see on the map, that my application calls "users" as an aggregated box, and the "users" box depends on 3 instances. Just like the SQL boxes on this image:

![image](https://user-images.githubusercontent.com/8693263/38353016-7311c8f8-38b5-11e8-9684-1f797671a57c.png)

**Comment by grlima** [comment] 2018-04-09 22:46
Dupe of #637

**Closed by grlima** 2018-04-09 22:46 UTC
Labels: question

**Comment by grava** [comment] 2020-03-12 12:40
Hi, I am trying with no luck to configure my spring boot app to use FeignClient to use OkHttp or Apache Http Client and send data to AppInsights. Can someone point me to a complete configuration to aaccomplish the above ? 
I tried with the application.yaml config using
feign:
 okhttp:
    enabled:true

but I cannot see any dependency in my AppInsights application map.

thanks !
