### ISSUE TITLE
Suspected memory leaks with 3.0.2

### ISSUE THREAD

**Issue by jcarnus** [microsoft/ApplicationInsights-Java#1632] opened 2021-04-16 17:10 UTC
Using the java agent, after few days, the memory usage is constantly growing. We are also facing such DB issue:
Cannot get a connection, pool error Timeout waiting for idle object.

What are the step required to give you data to debug ?

### To Reproduce
Just deploy our code

### System information
 - SDK Version: Java 1.8
 - OS type and version: Windows, AKS
 - Application Server type and version (if applicable):
 - Using spring-boot? No
 - Additional relevant libraries (with version, if applicable):

**Comment by trask** [comment] 2021-04-16 19:07
hi @jcarnus, can you capture a JVM heap dump?

If you can provide the heap dump to us somehow (trask.stalnaker@microsoft.com) I can review it. Or if you are unable to provide the heap dump to us, you can review it (I recommend Eclipse MemoryAnalyzer) and let us know what you find that can lead us to the cause.

**Comment by trask** [comment] 2021-06-14 18:36
Closing, there was a memory leak that was fixed in 3.1.1, please let us know if you upgrade to 3.1.1 and continue to see any issues.

**Closed by trask** 2021-06-14 18:36 UTC
