### ISSUE TITLE
Unable to send telemetry events when using custom channel

### ISSUE THREAD

**Issue by rahulpatchigolla** [Microsoft/ApplicationInsights-Java#611] opened 2018-03-17 16:48 UTC
I am trying to integrate AppInsights with Eclipse plugin in java.

We already have a telemetry pipeline in place for C# where the events are sent to a vortex pipeline which redirects telemetry to app insights.

The following settings work for me in C#.

```
TelemetryConfiguration appInsightsTelemetryConf = TelemetryConfiguration.Active;  
appInsightsTelemetryConf.InstrumentationKey = VortexApplicationInsightsInstrumentationKey; 
appInsightsTelemetryConf.TelemetryChannel.EndpointAddress = VortexAppInsightsEndPointAddress; 
this.telemetryClient = new TelemetryClient(appInsightsTelemetryConf);  

```

Below is the ApplicationInsights.xml which i use in my eclipse plugin which mimics the same configuration as above. 

```
<?xml version="1.0" encoding="utf-8"?>
<ApplicationInsights xmlns="http://schemas.microsoft.com/ApplicationInsights/2013/Settings" schemaVersion="2014-05-30">
  <InstrumentationKey>VortexApplicationInsightsInstrumentationKey</InstrumentationKey>
  <SDKLogger />
  <PerformanceCounters>
   <UseBuiltIn>False</UseBuiltIn>
  </PerformanceCounters>
  <Channel>
    <EndpointAddress>VortexAppInsightsEndPointAddress</EndpointAddress>
  </Channel>
</ApplicationInsights>
```

If I directly provide application insights instrumentation key, then I am able to log the events. But if I try to go through vortex pipeline, it doesn't work. Can you please help me out ? 

And on the side note i am also getting the below exception irrespective of the above cases. What should i do to prevent this ?

```
AI: ERROR 17-03-2018 18:47, 1: Failed to scan packages 'com.microsoft.applicationinsights': exception: 'org.eclipse.osgi.storage.url.BundleURLConnection cannot be cast to java.net.JarURLConnection'
AI: TRACE 17-03-2018 18:47, 1: Stack trace generated is java.lang.ClassCastException: org.eclipse.osgi.storage.url.BundleURLConnection cannot be cast to java.net.JarURLConnection
	at com.microsoft.applicationinsights.core.dependencies.annotation.AnnotationDetector.detect(AnnotationDetector.java:287)
	at com.microsoft.applicationinsights.internal.annotation.AnnotationPackageScanner.scanForClassAnnotations(AnnotationPackageScanner.java:58)
	at com.microsoft.applicationinsights.internal.config.TelemetryConfigurationFactory.getPerformanceModules(TelemetryConfigurationFactory.java:284)
	at com.microsoft.applicationinsights.internal.config.TelemetryConfigurationFactory.setTelemetryModules(TelemetryConfigurationFactory.java:175)
	at com.microsoft.applicationinsights.internal.config.TelemetryConfigurationFactory.initialize(TelemetryConfigurationFactory.java:107)
	at com.microsoft.applicationinsights.TelemetryConfiguration.getActive(TelemetryConfiguration.java:70)
	at com.microsoft.applicationinsights.TelemetryClient.<init>(TelemetryClient.java:83)
	at servicefabric.telemetry.TelemetryHelper.<init>(TelemetryHelper.java:26)
	at servicefabric.wizards.NewServiceFabricProjectWizard.performFinish(NewServiceFabricProjectWizard.java:99) 

```

This seems to similar to #553

**Comment by dhaval24** [comment] 2018-03-17 20:47
@rahulpatchigolla first of all the Eclipse plugin is maintained by tools team and currently I believe they haven't updated to the latest SDK version 2.0.1. 

Can you explain a detailed behavior ? do you see any exception apart from the above one. Can you capture the fiddler trace to see what is the response code you are getting from vortex and also from AI backend. 

Also how is your Java project build? Is it a maven / gradle based project? In that case i would prefer you use the typical maven/gradle configuration way instead of plugin. Here is the link https://docs.microsoft.com/en-us/azure/application-insights/app-insights-java-get-started

Regarding the error #553 I have provided a very indepth explanation there. Please go through the comments. 

What kind of Java application you have? Spring/SpringBoot/J2EE. Please be mindful Spring/SpringBoot Applications won't run with Eclipse plugin.

**Comment by rapatchi** [comment] 2018-03-18 11:26
Sorry for not being clear before. We have Service Fabric Eclipse Plugin which helps in creating and managing service fabric java applications. We want to collect telemetry of how people are using our plugin. The plugin does not use maven / gradle build system. So directly adding a dependency wasn't possible. So the approach i followed was by adding the core and web jars in my plugin's build and class path. 

The plugin is currently supported only on Linux and MacOS. I had trouble setting up fiddler on mac, but I was able to capture traffic on wireshark. I could see some back and forth communication happening between the vortex and my machine, but I could not figure out what the message is because it is encrypted. I was also able to collect so logs by running the plugin at debug level. In these traces I could see that connection is getting established. Sharing them here in case you can figure out anything from this (Replaced vortex's instrumentation key with `<Instrumentation-Key>`).
[debuglogs.txt](https://github.com/Microsoft/ApplicationInsights-Java/files/1822604/debuglogs.txt)
By AI backend do you mean in the portal ?. In portal i could not see any events coming up in metrics explorer (Which is the place the events used to come if i directly the app insights key).

And Also apart from the error which i got above i don't see anything in my traces. And regrading #553  as far as i understand the solution you mentioned is a problem specific to a spring boot application right ?

**Comment by dhaval24** [comment] 2018-03-18 18:15
Did you added the lates v2.0.1 version core and web jars? From the debuglogs, you sent I do not see any communication happening from Vortex to AI backend. I am not sure if this would be captured though or not because Vortex is talking to AI and your wireshark will capture outbound calls from the box. Though clearly it seems that from the logs, you are hitting a class cast exception. I am not sure why this is happening.

**Comment by rapatchi** [comment] 2018-03-20 03:11
I am using latest 2.0.1 version of core and web jars. I just wanted to know whenever send an event do we get back an ACK to client machine that we have sent the telemetry event to AI. Because i don't see any events like that in both sucess and failure cases. Also sharing the packets of Wireshark (I filtered the packets based on the IP address mentioned in the debug logs).
[filteredpackets.pcapng.zip](https://github.com/Microsoft/ApplicationInsights-Java/files/1827765/filteredpackets.pcapng.zip).

Is there any way we can disable getting the annotations as this is causing the class cast exception ?. If you can see in my applicationinsights.xml I disabled performance counters collection. But I still see a call to getPerformaceModules which in turn calls the getAnnotations function.

**Comment by rapatchi** [comment] 2018-03-20 07:54
Hi, 
I was able to sent events to the ApplicationInsights. I was looking into the wrong portal (We had two AI resources). I was looking into the wrong resource for the events. 

But there is still the problem of class cast exception. Can you help me out on this ?

**Comment by dhaval24** [comment] 2018-03-21 06:01
@rapatchi glad to know this that atleast you see the data. It seems like issue is specific to eclipse and happens when SDK tries to scan through performance counter module annotation and AnnotationDetector Library which is scans SDK which then throws ClassCastException. In order to further debug, I would need to know way how to reproduce this issue. Would you mind elaborating on the steps I can get this happen. I will suggest if you try this in plain eclipse webapp also.

**Comment by dhaval24** [comment] 2018-04-24 21:08
@rapatchi I am assuming that your concerns on sending the data to custom channel has been addressed. I am closing this issue as of now. If you have further questions please feel free to reopen if needed.

**Closed by dhaval24** 2018-04-24 21:08 UTC
Labels: question
