### ISSUE TITLE
Active TelemetryConfiguration initialized several times recursively - client then does not function

### ISSUE THREAD

**Issue by ialexandrov** [Microsoft/ApplicationInsights-Java#368] opened 2017-04-13 13:59 UTC
We are using AI logback appender with empty ApplicationInsights.xml config file. Additionally we create the new TelemetryClient instance in main method to send custom events.
This  leads to creation of 3 active configurations after which SDK does not function properly and does not send out any telemetry.

I've attached stack trace with recursive initialization of 3 active configurations

Explicitly disabling QuickPulse in xml configuration and removing explicit client instance creation helps.
Could you please consider this a critical issue? One will never know which changes in code/configuration will lead to client failure.
[StackTrace.txt](https://github.com/Microsoft/ApplicationInsights-Java/files/919803/StackTrace.txt)

**Comment by Dmitry-Matveev** [comment] 2017-04-15 01:39
We should consider fixing this in the upcoming release 1.0.8, unfortunately there is no date yet for this release and there are already several critical issues awaiting fixes in 1.0.8.
Anyway, I'll set 1.0.8 milestone for now.

Quick Pulse in Java SDK is broken as the moment as per Issue #360. It looks like you can keep it disabled as a workaround without the data/feature loss.

**Comment by dhaval24** [comment] 2017-11-18 06:04
@ialexandrov is this issue still persistent after our new releases of the SDK? If so please provide the steps to reproduce the issue. I haven't personally found this issue. Feel free to close the thread if this is no longer an issue.

**Comment by dhaval24** [comment] 2017-12-27 08:28
@ialexandrov #505 PR should be fixing the multiple initialization issue. Could you please have a look and let us know so we can close this one.

**Comment by grlima** [comment] 2018-01-09 19:49
Fixed with PR #505

**Closed by grlima** 2018-01-09 19:49 UTC
Labels: bug
