### ISSUE TITLE
AppInsights outbound metrics not capturing the URL of HTTP GET calls sent using  SPRING WEBCLIENT

### ISSUE THREAD

**Issue by Smaranikasarla** [microsoft/ApplicationInsights-Java#1276] opened 2020-07-09 16:22 UTC
While checking the performance of application on Application Insights, In the dependencies tab the outbound metrics of the HTTP GET information that are being made using spring Web client need to be captured including the URL.

But from what we observed, it is recording the complete HTTP  GET call information including the URL made through regular REST clients but not in the case of Spring WEBCLIENT. In the case of WEBCLIENT it is capturing the HTTP GET but NOT the URL of that call. So it is hard to distinguish those calls. This happens only in the case of GET request. Post request works fine. Attached the file for reference

### To Reproduce
1. Create a Spring WEBCLIENT GET request as below
```
@Autowired
@Qualifier(value = "defaultWebClient")
private WebClient defaultWebClient;

 private WebClient sampleWebClient;

@PostConstruct
public void initItemLookupService() {
   
sampleWebClient = defaultWebClient.mutate()
                .baseUrl("http://localhost:8080")
                .defaultHeaders(headerz -> headerz.put(<samplekey>, <samplevalue>))
                .build();
sampleWebClient.post()
                .uri("/sampleCall")
                .header(HttpHeaders.CONTENT_TYPE, MediaType.APPLICATION_JSON_VALUE)
                .body(Mono.just(empl), Sample.class)
                .retrieve()
                .bodyToMono(Sample.class);
}
```
#### Sample Application
If applicable, provide a sample application which reproduces the issue.

### System information
Please provide the following information:
 - SDK Version: applicationinsights-agent-3.0.0-PREVIEW.5.jar
 - Using spring-boot? YES V 5.2.6.Release
 - Additional relevant libraries (with version, if applicable):
```
Version 5.2.6
  <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-webflux</artifactId>
  </dependency>
```

### Logs
```
HTTP5:23:42.333 AMsbx-ops-test
HTTP5:23:42.333 AMsbx-ops-test
HTTP5:23:42.334 AMsbx-ops-test
INFORMATION5:23:42.335 AMsbx-ops-test removed from cache : Authorization -  : cause - EXPIRED
HTTP5:23:42.342 AMsbx-ops-test
POST /3cbcc3d3-094d-4006-9849-0d11d61f484d/oauth2/token
```
As seen in the above log, POST url is being captured but not the GET URL
<img width="825" alt="Screen Shot 2020-07-09 at 11 05 29 AM" src="https://user-images.githubusercontent.com/40274156/87065118-3daafe80-c1d6-11ea-8382-804d1291aa2f.png">

### Screenshots
<img width="822" alt="Screen Shot 2020-07-07 at 2 32 15 PM" src="https://user-images.githubusercontent.com/40274156/87065081-2f5ce280-c1d6-11ea-9c07-1bc612b4da65.png">

In the above screenshot, the HTTP GET calls using WEBCLIENT does not have the URL Captured but the other REST CLIENT urls are captured well.

**Comment by heyams** [comment] 2020-10-19 21:23
Can you upgrade to [PREVIEW.7](https://github.com/microsoft/ApplicationInsights-Java/releases/tag/3.0.0-PREVIEW.7)?  I'm not able to reproduce it using the latest release.  Please try it and let us know the outcome.  Thanks.

**Comment by trask** [comment] 2021-01-04 23:21
Closing, please let us know if you are still having this issue

**Closed by trask** 2021-01-04 23:21 UTC
Labels: Bug, Team-Triaged
