### ISSUE TITLE
ExceptionTelemetry with large / deep stack traces are silently omitted

### ISSUE THREAD

**Issue by LarsGielsok** [microsoft/ApplicationInsights-Java#482] opened 2017-12-08 16:52 UTC
When using the Logback appender ApplicationInsightsAppender and so indirectly the components of the applicationinsights-core artifact from
   com.microsoft.azure:applicationinsights-logging-logback:1.0.9
   com.microsoft.azure:applicationinsights-core:1.0.9
where is a problem with log statements that include an exception with deep / long stack traces (ExceptionTelemetry).

Deep stack traces are being serialized as event JSON object correctly which has been verified by debugging the applicationinsights-core code.
But when the resulting JSON of the parse stack (shown in Insights Analytics as "details.parsedStack" and stored in Java class ExceptionTelemetry.ExceptionData.ExceptionDetails.parsedStack) exceeds as certain size (which seems to be 32k according to https://github.com/Microsoft/ApplicationInsights-Home/blob/master/EndpointSpecs/Schemas/Docs/ExceptionData.md), the complete log statement is omitted and not shown in Azure Insights Analytics.

I'm not 100% sure if the ExceptionTelemetry is omitted by applicationinsights-core or by Azure Insights instance itself.
But everything indicates that Azure Insights is receiving the JSON and omitting it remotely.

Omitting an ExceptionTelemetry silently is a very problematic behaviour from a development and operations point of view.
The artifact applicationinsights-core or Application Insights itself should know and respect the Azure Insigts limits and provide a robust behaviour:
If stack traces exceed the given limits, at least the log statement without the deep "parsed stack trace" should be stored and shown in Analytics.
Otherwise application exceptions will never be recognized which is a no-go for a monitoring platform.

**Comment by dhaval24** [comment] 2017-12-08 18:00
@LarsGielsok, I see your point here and it is very valid. Here is my understanding:
1. Application Insights Java SDK - used to run on old schema definition which had lower limits of accepting the stack trace details apparently 1024 character until SDK v1.0.10 where we updated to new schema which supports 32k.
2. From the SDK v1.0.10 when the exception message exceeds the size of 32k then we truncate it to 32k and still report it to the portal.

Have you got a chance to try the Application Insights SDK v1.0.10?

**Comment by LarsGielsok** [comment] 2017-12-08 19:00
Hi,
Your understanding is correct.
Unfortunately, 1.0.10 is Not working with logback. There is already an
issue for that.


Am 08.12.2017 19:02 schrieb "Dhaval Doshi" <notifications@github.com>:

@LarsGielsok <https://github.com/larsgielsok>, I see your point here and it
is very valid. Here is my understanding:

   1. Application Insights Java SDK - used to run on old schema definition
   which had lower limits of accepting the stack trace details apparently 1024
   character until SDK v1.0.10 where we updated to new schema which supports
   32k.
   2. From the SDK v1.0.10 when the exception message exceeds the size of
   32k then we truncate it to 32k and still report it to the portal.

Have you got a chance to try the Application Insights SDK v1.0.10?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/Microsoft/ApplicationInsights-Java/issues/482#issuecomment-350330064>,
or mute the thread

**Comment by dhaval24** [comment] 2017-12-08 19:14
Yes there was an issue with sanitization and setting the severity level whose changes are already merged in master. So hopefully that should fix this issue also.

**Comment by LarsGielsok** [comment] 2017-12-09 10:14
when do you plan to release this fix? Is there any workaround in the meanwhile?

**Comment by dhaval24** [comment] 2017-12-09 19:10
@LarsGielsok we plan to release the new version by end of next week most probably if things go right. In the mean while I would be very happy if you would have a chance to build the SDK locally and try and test it out. In this way we would come to know if any issues still persist (however we haven't noticed it on our test applications). Here are the steps to build the SDK locally : 

1. Fork the repository.
2. Run the following gradle commands from the command prompt the location 
gradlew clean, gradlew assemble, gradlew test and gradlew build.
3. You would need JDK 1.7 / 1.8 and Gradle 3.5 to build this project.
4. core, web and agent jars would be found in the respective directories of the project.

Please give it a shot if you have some time. Also I would like to point you to #468 and #469 for our future SDK release plan and just in case you are interested to complete brief survey.

**Comment by dhaval24** [comment] 2017-12-13 18:20
@LarsGielsok were you able to try building the SDK locally? The Master branch is now most upto-date and you can build master directly.

**Comment by LarsGielsok** [comment] 2017-12-13 23:24
Hi Dhaval,

using 1.0.9 as well as the current master (1.0.11), the logback appender
generally works and pushes traces to Azure Insights (in 1.0.10 this was
broken as you know).
But unfortunately, with the current master, exceptions with large / deep
stack traces are still omitted.
Exception with short strack traces are shown in Insights. So pushing logs
to ExceptionTelemetry in general works.

Regards,
Lars

2017-12-13 19:20 GMT+01:00 Dhaval Doshi <notifications@github.com>:

**Comment by dhaval24** [comment] 2017-12-14 17:11
@LarsGielsok oh, I see.  We might have to dig more into this. We plan to release the SDK 2.0.0-BETA soon so I think it would be hard to lock down this particular issue into the upcoming release. I would investigate this further and update the thread. Hopefully we can get it down in 2.0.1 patch release. (Thank you very much for trying). In the mean while if you find some sort of possible solution which might be lying inside ExceptionTelemetry.java class feel free to send out a PR. Note that max size supported by the end point is 32k.

**Comment by dhaval24** [comment] 2018-01-03 17:49
@LarsGielsok there is a PR out there #507 which will fix this issue. Feel free to have a look if you wish to. The max size of exception depth we would allow is 10  (To be in sync with our other SDKs). Also the max size of the parsed stack which would be allowed is 32768 chars.

**Comment by dhaval24** [comment] 2018-01-11 17:23
@LarsGielsok thank you very much for this constructive feedback and taking time to try out the PR. It's much valuable and that's why the PR is not yet merged. Yes I agree with you that the size restriction might be for the entire Packet that gets sent to AI endpoint. Also it might be the case that the implementation of getStackFrameSize() might be too basic. Do you have any better suggestion on how we can efficiently compute the size of stackFrame() {i.e what all parameters to count for etc.} . Also the idea behind this was that if the size exceeds truncate with a self exception indicating truncation. 

Further, clearly your experiment by reducing the size to 20k shows that issue is pertaining to the size of the item. If you have any better approach on how to do this, it would be great. Looking forward to hear.

**Comment by dhaval24** [comment] 2018-01-12 00:21
@LarsGielsok btw I am also facing hard time to replicate the exact issue on my end. Is it possible for you to attach a trimmed down version of your code which is causing this issue?

**Comment by dhaval24** [comment] 2018-01-21 03:53
@LarsGielsok we did some investigation on this and found that our back-end has the current capacity to ingest a single payload no bigger than 65536 characters big. 
So this would probably boil down to a design discussion on how we could handle the exceptions. Because it is very possible that a single exception could have a deep stacktrace array which could fill up the limit or in other case there can be a chain of exceptions linked exception->cause->exception..... relationship. What would be the ideal way of truncation here needs to be thought off. Apologies there is no solution yet, but wanted to keep you informed.

**Comment by vlev** [comment] 2019-01-08 09:39
Hi guys,

I think one of the approaches to mitigate this issue could be a parameterization of maximum exception's graph length and trace depth (per exception). 

We could add two parameters in TelemetryConfiguration (also in XML and SB config): exceptionDepth and traceDepth.
ExceptionTelemetry.convertExceptionTree method is already able to cut the exceptions graph's length. 
Adding capability of cutting trace length should be relatively easy to implement. 

If you are ok with this approach, I could provide the PR.

**Comment by vlev** [comment] 2019-01-08 15:53
Also, I've found that RuntimeExceptionDecider (from module "agent") can use stackTrace property (which is actually treated as a cap on exceptions graph length). I guess this is another case where extra configuration is required.

**Comment by dhaval24** [comment] 2019-01-17 05:46
@vlev that seems very interesting approach. We always appreciate any contributions. I would suggest that you create another issue, and elaborate your apporach a bit more there. You can then create a PR for it. Your contribution would be greatly appreciated.

**Comment by gondar** [comment] 2019-05-06 15:23
Is there any news on this issue @dhaval24 we just recently found out that not all exceptions are logged to application insights. That was very confusing for us. Simple reproduction is just trying to log stackOverflow exception e.g compare following:
`public void logStackOverflow() {
        try {
            doInfiniteLoop();
        } catch (StackOverflowError ex) {
            log.info("Logging StackOverflow");
            log.error("StackOverflow", ex);
        }
    }

    private void doInfiniteLoop() {
        doInfiniteLoop();
    }

    public void logSimple() {
        try {
            throw new Exception("Oh Dear!");
        } catch (Exception ex) {
            log.info("Logging Simple");
            log.error("Simple", ex);
        }
    }`

**Comment by dhaval24** [comment] 2019-05-06 17:01
@gondar I have responded on the @vlev 's PR. @littleaj / @trask might have more context and can help you more : Let me know if the processor example provided there works for you.

**Closed** 2021-05-25 21:41 UTC
Labels: Bug, Team-Triaged
