### ISSUE TITLE
NULL check missing in agent instrumentation code

### ISSUE THREAD

**Issue by debugthings** [Microsoft/ApplicationInsights-Java#506] opened 2017-12-25 02:57 UTC
When the agent attempts to view the existing correlation headers it does not perform a NULL check [here](https://github.com/Microsoft/ApplicationInsights-Java/blob/36214d5c28eb975e008c5b7c60c4840fdd10ec20/agent/src/main/java/com/microsoft/applicationinsights/agent/internal/agent/HttpClientMethodVisitor.java#L66).

This can throw an exception during the filter pipeline and lead to an internal server error.

It is recommended that we add a check similar to [this one](https://github.com/Microsoft/ApplicationInsights-Java/blob/36214d5c28eb975e008c5b7c60c4840fdd10ec20/agent/src/main/java/com/microsoft/applicationinsights/agent/internal/agent/HttpClientMethodVisitor.java#L143-L146) to avoid a nullref exception.

It was see recently on a struts application using thew new 2.0.0-BETA SDK and form based security with j_security_check.

**Comment by nicolehaugen79** [comment] 2018-01-18 14:59
I have also hit this issue.  Here are the repro steps:

1.) Follow these steps to setup AI for dependencies: https://docs.microsoft.com/en-us/azure/application-insights/app-insights-java-agent

2.) Use the ToDo List sample app which is a Java SpringBoot app that uses the Azure Document DB library and App Insights library.

3.) Follow the ReadMe's steps to build and run the app.  When attempting to run the app, you'll get the following exception:

Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.microsoft.azure.documentdb.DocumentClient]: Factory method 'documentClient' threw exception; nested exception is java.lang.NullPointerException
        at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:189) ~[spring-beans-4.3.12.RELEASE.jar!/:4.3.12.RELEASE]
        at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:588) ~[spring-beans-4.3.12.RELEASE.jar!/:4.3.12.RELEASE]
        ... 88 common frames omitted
Caused by: java.lang.NullPointerException: null
        at com.microsoft.applicationinsights.web.internal.correlation.TelemetryCorrelationUtils.retrieveCorrelationContext(TelemetryCorrelationUtils.java:140) ~[applicationinsights-web-2.0.0-BETA.jar!/:na

**Comment by grlima** [comment] 2018-02-02 23:47
@nicolehaugen79 - is it possible you have not configured the necessary Beans to have the AppInsights filter properly configured. We were able to repro this issue when the filter was not properly configured in Spring Boot. See step 4 of this guide on how to configure AppInsights Filter in spring boot: https://github.com/AzureCAT-GSI/DevCamp/tree/master/HOL/java/06-appinsights

**Comment by grlima** [comment] 2018-02-02 23:48
Closing issue as the fix has been merged. #541

**Closed by grlima** 2018-02-02 23:48 UTC
Labels: bug
