### ISSUE TITLE
Telemetry filters on span events

### ISSUE THREAD

**Issue by ivan-zaitsev** [microsoft/ApplicationInsights-Java#3375] opened 2023-11-08 18:24 UTC
**Is your feature request related to a problem? Please describe.**

Currently only filtering on attributes is supported

https://github.com/microsoft/ApplicationInsights-Java/blob/547ec61e8cfe8b7dbe77de73c8c53d51c03377f5/agent/agent-tooling/src/main/java/com/microsoft/applicationinsights/agent/internal/processors/SpanExporterWithAttributeProcessor.java#L38-L47

**Describe the solution you would like**
It would be good to have filtering also on span events. For example, if span event contains some fields and it is specified as include or exclude option the span processor actions such as adding new attribute should be executed.

Example (azure blob storage deleteIfExists):

Code:
```
BlobContainerClient blobContainerClient = blobServiceClient.getBlobContainerClient("container");
blobContainerClient.deleteIfExists();
```

Produced spans:
```
SpanData{
    spanContext=ImmutableSpanContext{
        traceId=0, spanId=0, traceFlags=01, traceState=ArrayBasedTraceState{entries=[]}, remote=false, valid=true}, 
        parentSpanContext=ImmutableSpanContext{traceId=0, spanId=0, traceFlags=01, traceState=ArrayBasedTraceState{entries=[]}, remote=false, valid=true}, 
        resource=Resource{schemaUrl=https://opentelemetry.io/schemas/1.20.0, attributes={telemetry.sdk.language="java", telemetry.sdk.name="opentelemetry", telemetry.sdk.version="1.28.0"}}, 
        instrumentationScopeInfo=InstrumentationScopeInfo{name=azure-storage-blob, version=12.23.0, schemaUrl=https://opentelemetry.io/schemas/1.17.0, attributes={}}, 
        name=AzureBlobStorageCont.delete, kind=INTERNAL, startEpochNanos=0, endEpochNanos=0, 
        attributes=AttributesMap{data={
            az.namespace=Microsoft.Storage, thread.id=59, applicationinsights.internal.operation_name=DELETE /api/v1/operation, thread.name=http-nio-8080-exec-1, applicationinsights.internal.item_count=1
        }, 
        capacity=128, totalAddedValues=5}, totalAttributeCount=5,
        events=[ImmutableExceptionEventData{epochNanos=0, exception=
            com.azure.storage.blob.models.BlobStorageException: Status code 404, "<?xml version="1.0" encoding="utf-8"?><Error><Code>ContainerNotFound</Code><Message>The specified container does not exist.</Message></Error>", 
        additionalAttributes={}, spanLimits=SpanLimitsValue{maxNumberOfAttributes=128, maxNumberOfEvents=128, maxNumberOfLinks=128, maxNumberOfAttributesPerEvent=128, maxNumberOfAttributesPerLink=128, maxAttributeValueLength=2147483647}}], 
        totalRecordedEvents=1, links=[], totalRecordedLinks=0, status=ImmutableStatusData{statusCode=ERROR, description=}, hasEnded=true
    }

SpanData{
    spanContext=ImmutableSpanContext{
        traceId=0, spanId=0, traceFlags=01, traceState=ArrayBasedTraceState{entries=[]}, remote=false, valid=true}, 
        parentSpanContext=ImmutableSpanContext{traceId=0, spanId=0, traceFlags=01, traceState=ArrayBasedTraceState{entries=[]}, remote=false, valid=true}, 
        resource=Resource{schemaUrl=https://opentelemetry.io/schemas/1.20.0, attributes={telemetry.sdk.language="java", telemetry.sdk.name="opentelemetry", telemetry.sdk.version="1.28.0"}}, 
        instrumentationScopeInfo=InstrumentationScopeInfo{name=azure-storage-blob, version=12.23.0, schemaUrl=https://opentelemetry.io/schemas/1.17.0, attributes={}}, 
        name=HTTP DELETE, kind=CLIENT, startEpochNanos=0, endEpochNanos=0, 
        attributes=AttributesMap{data={
            az.namespace=Microsoft.Storage, http.user_agent=az-sp-sb/5.4.0 azsdk-java-azure-storage-blob/12.23.0, http.status_code=404, thread.id=61, 
            http.url=https://storage.blob.core.windows.net/container?restype=container, applicationinsights.internal.operation_name=DELETE /api/v1/operation, 
            thread.name=http-nio-8080-exec-3, http.method=DELETE, applicationinsights.internal.item_count=1, az.client_request_id=0, az.service_request_id=0
        }, 
        capacity=128, totalAddedValues=11}, totalAttributeCount=11, 
        events=[],
        totalRecordedEvents=0, links=[], totalRecordedLinks=0, status=ImmutableStatusData{statusCode=ERROR, description=}, hasEnded=true}
...
```

- First span attributes contain only operation name. and events contain the error. In this case it is not possible to create filter if operation is not successful, because useful information is located in events parameter.
- Second span contains http status parameter, and it is possible to filter that.

My use case is to add additional attribute if any of these spans are found. As azure marks these spans as "success = false", and I want to add additional attribute to mark this as "controlled error".

---

Also, for all attributes operation "and" is applied (all include filters should be true), it would be good to configure it somehow to have ability to specify some "or" conditions. Currently it is possible to do that only by creating duplicate sections for processors, what leads to complexity. This would give ability to filter multiple spans using only one processor. See example with azure blob storage deleteIfExists which produces multiple spans.

**Comment by ivan-zaitsev** [comment] 2023-11-09 11:59
Also, processors include/exclude have one matchType for all attributes. It would be good to add different matchType for each attribute.

Example: 

            {
                "type": "attribute",
                "include": {
                    "matchType": "strict",
                    "attributes": [
                        {
                            "key": "http.response.status_code",
                            "value": 401
                        },
                        {
                            "key": "http.request.method",
                            "value": "GET"  ---- How to regexp ?
                        }
                    ]
                },
                "actions": [
                    {
                        "action": "insert",
                        "key": "controlledError",
                        "value": true
                    }
                ],
                "id": "mark as not an error for status codes"
            }

As well as currently for all attributes operation "and" is applied, it would be good to configure it somehow to have ability to specify some "or" conditions. Currently it is possible to do that only by creating duplicate sections for processors.

**Comment by heyams** [comment] 2023-11-15 20:45
@ivan-zaitsev span #2 above, current telemetry processor supports it. 
```json
{
    "type": "attribute",
    "include": {
        "matchType": "strict",
        "attributes": [
            {
                "key": "http.status_code",
                "value": 404
            }
        ]
    },
    "actions": [
        {
            "action": "insert",
            "key": "controlledError",
            "value": true
        }
    ],
    "id": "mark as not an error for status codes"
}
```

Are you asking for supporting filtering `span.events` via telemetry processors?

**Comment by ivan-zaitsev** [comment] 2023-11-15 20:47
> Are you asking for supporting filtering span.events via telemetry processors?

Yes

**Comment by ivan-zaitsev** [comment] 2023-12-18 11:40
From different thread @heyams said that it won`t be supported.

It's sad that this won't be supported. If I would submit merge request, would you consider adding this feature?

I think it is pretty easy to add, because [EventData](https://github.com/open-telemetry/opentelemetry-java/blob/main/sdk/trace/src/main/java/io/opentelemetry/sdk/trace/data/EventData.java#) already contains attributes, and everything is already in place to handle attributes, only new processor similar to [SpanExporterWithAttributeProcessor](https://github.com/microsoft/ApplicationInsights-Java/blob/e3eccab9d4c7acc4e72662c3bc4ef48033e85c1b/agent/agent-tooling/src/main/java/com/microsoft/applicationinsights/agent/internal/processors/SpanExporterWithAttributeProcessor.java) should be added to process `span.getEvents().stream().forEach(event -> event.getAttributes())` instead of `span.getAttributes()`.

How i think it can be added: 
1. New ProcessorType value = EVENT_ATTRIBUTE should be added. Here: https://github.com/microsoft/ApplicationInsights-Java/blob/e3eccab9d4c7acc4e72662c3bc4ef48033e85c1b/agent/agent-tooling/src/main/java/com/microsoft/applicationinsights/agent/internal/configuration/Configuration.java#L127
2. New EventSpanExporterWithAttributeProcessor class should be added. Similar to this: [SpanExporterWithAttributeProcessor](https://github.com/microsoft/ApplicationInsights-Java/blob/e3eccab9d4c7acc4e72662c3bc4ef48033e85c1b/agent/agent-tooling/src/main/java/com/microsoft/applicationinsights/agent/internal/processors/SpanExporterWithAttributeProcessor.java

Then it would be possible to filter on event attributes like this:
```
{
  "sampling" : {
    "percentage" : 100
  },
  "preview" : {
    "processors": [
      {
        "id" : "processors/attribute/strict",
        "type": "event-attribute",                  --- new type
        "include": {
          "matchType": "strict",
          "attributes": [
            {
              "type": "string",
              "key": "exception.type",
              "value": "com.azure.storage.blob.models.BlobStorageException"
            }
          ]
        },
        "actions": [
          {
            "action": "insert",
            "key": "strictKey",
            "value": "strictValue"
          }
        ]
      }
    ]
  }
}
```

It is possible to filter on "exception.type" event attribute because it is added automatically by https://github.com/open-telemetry/opentelemetry-java/blob/ffd53c7d56f3d14cdb13e8489d18d3d14b71da33/sdk/trace/src/main/java/io/opentelemetry/sdk/trace/internal/data/ImmutableExceptionEventData.java#L67

**Comment by heyams** [comment] 2023-12-20 00:10
@ivan-zaitsev I'm going to work on the sample app using OTEL extensions. if it doesn't work, i will discuss it with my team and then get back to you.

**Comment by ivan-zaitsev** [comment] 2024-01-03 14:22
Hello @heyams 

Tried to create OTEL extension, but it didn't work. I can see that my custom `addTracerProviderCustomizer` and `addSpanExporterCustomizer` are executed before [SecondEntryPoint](https://github.com/microsoft/ApplicationInsights-Java/blob/118dc22004da68679a67e137329d580cd081aa3e/agent/agent-tooling/src/main/java/com/microsoft/applicationinsights/agent/internal/init/SecondEntryPoint.java#L101), and [tracer exporter processor ](https://github.com/microsoft/ApplicationInsights-Java/blob/118dc22004da68679a67e137329d580cd081aa3e/agent/agent-tooling/src/main/java/com/microsoft/applicationinsights/agent/internal/init/SecondEntryPoint.java#L515-L530) `AgentSpanExporter.export` is executed after my custom `SimpleSpanProcessor`. But by some reason tracer exporter does not export those changes.

Code example:


```
resources/META-INF/services/io.opentelemetry.sdk.autoconfigure.spi.AutoConfigurationCustomizerProvider

otel.OpentelemetryExporterCustomizer
```

```
package otel;

import java.util.Collection;

import io.opentelemetry.api.common.Attributes;
import io.opentelemetry.api.common.AttributesBuilder;
import io.opentelemetry.sdk.autoconfigure.spi.AutoConfigurationCustomizer;
import io.opentelemetry.sdk.autoconfigure.spi.AutoConfigurationCustomizerProvider;
import io.opentelemetry.sdk.common.CompletableResultCode;
import io.opentelemetry.sdk.trace.SdkTracerProviderBuilder;
import io.opentelemetry.sdk.trace.data.DelegatingSpanData;
import io.opentelemetry.sdk.trace.data.SpanData;
import io.opentelemetry.sdk.trace.export.SimpleSpanProcessor;
import io.opentelemetry.sdk.trace.export.SpanExporter;

public class OpentelemetryExporterCustomizer implements AutoConfigurationCustomizerProvider {

    @Override
    public int order() {
        return -1;
    }

    @Override
    public void customize(AutoConfigurationCustomizer autoConfiguration) {
        autoConfiguration.addTracerProviderCustomizer((tracer, otelConfig) -> wrapTracerProvider(tracer));
        autoConfiguration.addSpanExporterCustomizer((exporter, otelConfig) -> wrapSpanExporter(exporter));
    }

    private SdkTracerProviderBuilder wrapTracerProvider(SdkTracerProviderBuilder tracerProviderBuilder) {
        SpanExporter spanExporter = wrapSpanExporter(SpanExporter.composite());
        tracerProviderBuilder.addSpanProcessor(SimpleSpanProcessor.create(spanExporter));
        return tracerProviderBuilder;
    }

    private SpanExporter wrapSpanExporter(SpanExporter spanExporter) {
        return new ProcessorSpanExporter(spanExporter);
    }

    private static class ProcessorSpanExporter implements SpanExporter {

        private final SpanExporter delegate;

        private ProcessorSpanExporter(SpanExporter delegate) {
            this.delegate = delegate;
        }

        @Override
        public CompletableResultCode export(Collection<SpanData> spans) {
            return delegate.export(spans.stream().map(this::process).toList());
        }

        @Override
        public CompletableResultCode flush() {
            return delegate.flush();
        }

        @Override
        public CompletableResultCode shutdown() {
            return delegate.shutdown();
        }

        private SpanData process(SpanData span) {
            AttributesBuilder builder = Attributes.builder();
            builder.putAll(span.getAttributes());
            builder.put("test-key", "test-value");

            SpanData result = new ExtendedSpanData(span, builder.build());
            System.out.println(result);
            return result;
        }

    }

    public static class ExtendedSpanData extends DelegatingSpanData {

        private final Attributes attributes;

        public ExtendedSpanData(SpanData delegate, Attributes attributes) {
            super(delegate);
            this.attributes = attributes;
        }

        @Override
        public Attributes getAttributes() {
            return attributes;
        }

    }

}
```

Run app
```
java -jar app.jar -Dotel.javaagent.extensions=otel-extension.jar
```

**Comment by ivan-zaitsev** [comment] 2024-01-03 14:36
Figured it out. Usual otel extension creation guidelines with span exporters are not applicable here. `ApplicationInsights-Java` uses span processors as last sink for data exporting. Span processors do not return modified span as `SpanExporter` do, also `addSpanExporterCustomizer` exporters are not being used in `addTracerProviderCustomizer` flow, because of that any modification of span data in span exporters will not simply work. Therefore, to make it work the modification in span processors should be made.

Code example:

```
package otel;

import io.opentelemetry.context.Context;
import io.opentelemetry.sdk.autoconfigure.spi.AutoConfigurationCustomizer;
import io.opentelemetry.sdk.autoconfigure.spi.AutoConfigurationCustomizerProvider;
import io.opentelemetry.sdk.trace.ReadWriteSpan;
import io.opentelemetry.sdk.trace.ReadableSpan;
import io.opentelemetry.sdk.trace.SdkTracerProviderBuilder;
import io.opentelemetry.sdk.trace.SpanProcessor;

public class OpentelemetryExporterCustomizer implements AutoConfigurationCustomizerProvider {

    @Override
    public int order() {
        return -1;
    }

    @Override
    public void customize(AutoConfigurationCustomizer autoConfiguration) {
        autoConfiguration.addTracerProviderCustomizer((tracer, otelConfig) -> wrapTracerProvider(tracer));
    }

    private SdkTracerProviderBuilder wrapTracerProvider(SdkTracerProviderBuilder tracerProviderBuilder) {
        tracerProviderBuilder.addSpanProcessor(new SimpleSpanProcessor());
        return tracerProviderBuilder;
    }

    private static class SimpleSpanProcessor implements SpanProcessor {

        @Override
        public boolean isStartRequired() {
            return true;
        }

        @Override
        public void onStart(Context parentContext, ReadWriteSpan span) {
            span.setAttribute("test-key", "test-value");
        }

        @Override
        public boolean isEndRequired() {
            return false;
        }

        @Override
        public void onEnd(ReadableSpan span) {
        }

    }

}
```

**Comment by ivan-zaitsev** [comment] 2024-01-03 14:42
Also, I think this feature can simply be implemented by changing conditions in `SpanExporterWithAttributeProcessor`.

https://github.com/microsoft/ApplicationInsights-Java/blob/118dc22004da68679a67e137329d580cd081aa3e/agent/agent-tooling/src/main/java/com/microsoft/applicationinsights/agent/internal/processors/SpanExporterWithAttributeProcessor.java#L37-L49

```
include != null && !include.isMatch(span.getAttributes(), span.getName())
exclude != null && include.isMatch(span.getAttributes(), span.getName())
```

Can be changed to:
```
include != null && !isMatch(span, include)
exclude != null && isMatch(span, exclude)

boolean isMatch(SpanData span, AttributeProcessorFilter filter) {
    return include.isMatch(span.getAttributes(), span.getName()) || span.getEvents().stream().anyMatch(event -> filter.matches(event.getAttributes()));
}
```

This way `SpanExporterWithAttributeProcessor` will check not only span attributes, but also event attributes.

**Comment by heyams** [comment] 2024-01-03 18:27
Happy new year! Will get back to you soon. Sorry was out of office during the holidays. Thank you for trying :)

**Comment by heyams** [comment] 2024-01-04 21:24
@ivan-zaitsev I tried something similar [here](https://github.com/Azure-Samples/ApplicationInsights-Java-Samples/pull/272/files#diff-e46c9f1942d74ae86abfab988570b94ceedf94c153bfbcca6a4a2d15141b152d). 

My extension code gets applied, but it requires some code change in the Java agent in order to make it full-functional. 
Please stay tune and I will try to work on the java agent to make this sample works for your use case.

**Comment by ivan-zaitsev** [comment] 2024-01-04 21:35
Hello @heyams 

Thank you for your help. 
Interesting, everything seems similar to my first example. But in my case it didn't work when I checked logs in applications insights. I think that all `SpanExporters` which are added by `addSpanExporterCustomizer` have no effect on the actual http exporter which is configured as span processor - [here](https://github.com/microsoft/ApplicationInsights-Java/blob/118dc22004da68679a67e137329d580cd081aa3e/agent/agent-tooling/src/main/java/com/microsoft/applicationinsights/agent/internal/init/SecondEntryPoint.java#L515-L530).

**Comment by heyams** [comment] 2024-01-05 18:27
@ivan-zaitsev yes, that's the part I need to fix in our java agent. But `addTracerProviderCustomizer` works.

**Comment by ivan-zaitsev** [comment] 2024-01-16 07:40
Hello @heyams, any update on this? Seems that there no other way at the moment to add any custom span processing on top of this java agent.

**Comment by heyams** [comment] 2024-01-16 18:27
@ivan-zaitsev no, we're working on it.. It's a bit tricky though. I will make sure i test it and then confirm it's working in my sample.. then once this is released next week, you can use it. you have been super helpful assisting me getting to the bottom of this. I appreciate your patience.

**Comment by heyams** [comment] 2024-01-16 23:18
@ivan-zaitsev good news! it seems to be working. https://github.com/Azure-Samples/ApplicationInsights-Java-Samples/pull/272 will generate this payload:

```json
{
  "ver": 1,
  "name": "RemoteDependency",
  "time": "2024-01-16T22:55:00.503Z",
  "iKey": "<REDACTED>",
  "tags": {
    "ai.internal.sdkVersion": "java:3.5-SNAPSHOT",
    "ai.operation.id": "d1d540898b5bc6697637561c9dea25db",
    "ai.cloud.roleInstance": "<REDACTED>"
  },
  "data": {
    "baseType": "RemoteDependencyData",
    "baseData": {
      "ver": 2,
      "id": "018c905b75ea7b3f",
      "name": "mySpan",
      "type": "InProc",
      "duration": "00:00:10.297740",
      "success": true,
      "properties": {
        "controlledError": "true", **// this is added via the Telemetry Processor**
        "myCustomAttributeKey2": "myCustomAttributeValue2", **// added via the extension via the Sample above**
        "myCustomAttributeKey": "myCustomAttributeValue"
      }
    }
  }
}
```

You can reproduce it if you follow my [readme ](https://github.com/Azure-Samples/ApplicationInsights-Java-Samples/blob/9209aa4e4d47db21997b3aacd93840c572b58cc3/opentelemetry-api/java-agent/TelemetryFilteredBaseOnSpanEvents/README.md).

It will be part of 3.5 GA release probably next week if no delay. I'll give you an update.

**Comment by heyams** [comment] 2024-02-02 21:56
@ivan-zaitsev just a heads up: 3.5 GA release is delayed to the week of Feb 21. We are waiting for a couple of fixes in upstream to be released in OpenTelemetry 2.1. Thank you for your patience.

**Comment by heyams** [comment] 2024-02-29 22:21
[3.5.0](https://github.com/microsoft/ApplicationInsights-Java/releases/tag/v3.5.0) is live.

**Comment by ivan-zaitsev** [comment] 2024-03-01 10:31
> [3.5.0](https://github.com/microsoft/ApplicationInsights-Java/releases/tag/v3.5.0) is live today.

Thanks, it means we can close this issue?

**Comment by heyams** [comment] 2024-03-01 17:33
> > [3.5.0](https://github.com/microsoft/ApplicationInsights-Java/releases/tag/v3.5.0) is live today.
> 
> Thanks, it means we can close this issue?

i can close it for you. i will update the sample too. thank you!

**Closed by heyams** 2024-03-01 17:33 UTC
Labels: Needs: Attention :wave:

**Comment by heyams** [comment] 2024-03-07 01:59
@ivan-zaitsev I've updated the sample app using the latest java agent. https://github.com/Azure-Samples/ApplicationInsights-Java-Samples/pull/272. It is working as expected. Please follow the readme for detail on build and package, kusto query instructions.

**Comment by ivan-zaitsev** [comment] 2024-03-07 06:15
@heyams Thank you.
