### ISSUE TITLE
Sampling Override causes calls to "http:/" (applicationinsights-agent-3.0.3.jar)

### ISSUE THREAD

**Issue by KaiserKon** [microsoft/ApplicationInsights-Java#1631] opened 2021-04-16 10:23 UTC
I wanted to try out the Sampling Override feature to suppress the collection of telemetry for a specific url ending.  
To achieve this, I used the following code snippet in my applicationinsights.json.
```json
"preview": {
    "sampling": {
      "overrides": [
        {
          "attributes": [
            {
              "key": "http.url",
              "value": "https?://[\\w\\d\\S]+/admin/prometheus",
              "matchType": "regexp"
            }
          ],
          "percentage": 0
        }
      ]
    }
```
This snippet worked as expected and suppressed all the requests to "/admin/prometheus", but at the same time it started producing errors. Under closer inspection all the errors where caused by an HTTP GET call to "http:/".  
I tried to use several different strings for the value and also switched the matchType to strict, but got always the same behavior.  

Is this behavior already known or am I doing something wrong?

### Service information
- JAVA 11
- Spring-boot 2.2.6
- applicationinsights-agent-3.0.3

**Comment by trask** [comment] 2021-04-16 19:10
hi @KaiserKon! are you getting exception stack traces for these errors? if so can you provide one of them so we can better understand where the issue is coming from? or is it some other kind of error you are seeing?

**Comment by KaiserKon** [comment] 2021-04-19 07:27
hey @trask i saw the problem first over the application map and that I get a lot of http http calls, which result in an 505 error code. I also enabled the self-diagnostics today to do more research. This led me to the following warning message:
```
WARN  o.a.http.impl.auth.HttpAuthenticator - NEGOTIATE authentication error: Invalid name provided (Mechanism level: KrbException: Cannot locate default realm)
```

**Comment by KaiserKon** [comment] 2021-04-19 08:04
Nevermind the warning. I tried out the sampling override with a second service, got the same "http:/" calls but no warning. So the warning is probably something else I have to look into.
So in that case I unfortunately don't really have any error stack traces or anything except the end-to-end transaction details, which do not really help much i guess.
![image](https://user-images.githubusercontent.com/8202075/115201642-d8d1ec80-a0f5-11eb-8300-77207a755913.png)

**Comment by KaiserKon** [comment] 2021-04-19 09:48
Okay, I also tried to disable the auto-collection of micrometer completely by using the following code snippet in my json file:
```json
"instrumentation": {
    "logging": {
      "level": "INFO"
    },
    "micrometer": {
      "enabled": false
    }
  }
```
This resulted in the same behavior. So it probably isn't connected to the sampling override feature.

**Comment by trask** [comment] 2021-05-05 04:51
> I mean it isn't really an error/exception right? It's just something that calls an invalide url ("http:/") wich leads to a failed HTTP request. Question is who is producing that http request.

Ya, this sounds right. Any luck tracking down who is producing that http request?

**Comment by KaiserKon** [comment] 2021-05-05 07:16
Unfortunately no luck so far. I tried it with several other services, which include micrometer. All of them produced the same problem whenever I "touched" micrometer in the agent config. Because of some personal time restrains, I also just implemented a temporary workaround, wich just filters out all the "http:/" calls.
Do you have any suggestions as to what I can to narrow the problem down further?

**Comment by trask** [comment] 2021-05-05 20:23
> Do you have any suggestions as to what I can to narrow the problem down further?

Are you able to reproduce it locally? If so, you could try putting a conditional breakpoint in the http client. I can also point you to where you could put breakpoint lower down in the agent code if needed.

Btw, were you able to use sampling override to filter them out? e.g.

```
{
  "preview": {
    "sampling": {
      "overrides": [
        {
          "attributes": [
            {
              "key": "http.url",
              "value": "http:/",
              "matchType": "strict"
            }
          ],
          "percentage": 0
        }
      ]
    }
  }
}
```

**Comment by KaiserKon** [comment] 2021-05-06 05:14
> Btw, were you able to use sampling override to filter them out?

That's exactly what I am currently using as a workaround.

**Comment by KaiserKon** [comment] 2021-05-07 12:26
> Are you able to reproduce it locally? If so, you could try putting a conditional breakpoint in the http client. I can also point you to where you could put breakpoint lower down in the agent code if needed.

I tried to reproduce it locally today, but unfortunately everything works as intended on my local machine.

**Comment by trask** [comment] 2021-06-17 03:53
Let us know if you find anything.

Closing in the meantime, but please feel free to post further comment or create a new issue.

**Closed by trask** 2021-06-17 03:53 UTC
