### ISSUE TITLE
Failed to register 'ApplicationInsightsWebFilter'

### ISSUE THREAD

**Issue by benlam62** [Microsoft/ApplicationInsights-Java#283] opened 2016-06-15 01:38 UTC
Hi folks, I fail to register 'ApplicationInsightsWebFilter' when running locally on my Tomcat 7 server with the following exception. How can it be fixed?

I: INFO 15-06-2016 09:30, 13: Registering WebApp with name 'azure-documentdb-java-sample'
AI: ERROR 15-06-2016 09:30, 13: Failed to register 'ApplicationInsightsWebFilter', exception: 'com/microsoft/applicationinsights/agent/internal/coresync/AgentNotificationsHandler'
AI: INFO 15-06-2016 09:30, 13: Configuration file 'ApplicationInsights.xml' was NOT found by default class loader
AI: INFO 15-06-2016 09:30, 13: Configuration file has been successfully found in: 'C:\Users\benlam\Documents\eclipse\workspaces.metadata.plugins\org.eclipse.wst.server.core\tmp0\wtpwebapps\azure-documentdb-java-sample\WEB-INF\lib\ApplicationInsights.xml'
Jun 15, 2016 9:30:34 AM org.apache.catalina.core.StandardContext filterStart
SEVERE: Exception starting filter ApplicationInsightsWebFilter
java.lang.NoClassDefFoundError: Could not initialize class org.apache.http.impl.conn.ManagedHttpClientConnectionFactory
    at org.apache.http.impl.conn.PoolingHttpClientConnectionManager$InternalConnectionFactory.<init>(PoolingHttpClientConnectionManager.java:494)
    at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.<init>(PoolingHttpClientConnectionManager.java:149)
    at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.<init>(PoolingHttpClientConnectionManager.java:138)
    at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.<init>(PoolingHttpClientConnectionManager.java:114)
    at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.<init>(PoolingHttpClientConnectionManager.java:105)
    at com.microsoft.applicationinsights.internal.channel.common.ApacheSender43.<init>(ApacheSender43.java:45)
    at com.microsoft.applicationinsights.internal.channel.common.ApacheSenderFactory.create(ApacheSenderFactory.java:40)
    at com.microsoft.applicationinsights.internal.channel.common.TransmissionNetworkOutput.<init>(TransmissionNetworkOutput.java:86)
    at com.microsoft.applicationinsights.internal.channel.common.TransmissionNetworkOutput.create(TransmissionNetworkOutput.java:77)
    at com.microsoft.applicationinsights.channel.concrete.inprocess.InProcessTelemetryChannelFactory.create(InProcessTelemetryChannelFactory.java:46)
    at com.microsoft.applicationinsights.channel.concrete.inprocess.InProcessTelemetryChannel.initialize(InProcessTelemetryChannel.java:258)
    at com.microsoft.applicationinsights.channel.concrete.inprocess.InProcessTelemetryChannel.<init>(InProcessTelemetryChannel.java:143)
    at com.microsoft.applicationinsights.internal.config.TelemetryConfigurationFactory.setChannel(TelemetryConfigurationFactory.java:357)
    at com.microsoft.applicationinsights.internal.config.TelemetryConfigurationFactory.initialize(TelemetryConfigurationFactory.java:100)
    at com.microsoft.applicationinsights.TelemetryConfiguration.getActive(TelemetryConfiguration.java:72)
    at com.microsoft.applicationinsights.web.internal.WebRequestTrackingFilter.init(WebRequestTrackingFilter.java:132)
    at org.apache.catalina.core.ApplicationFilterConfig.initFilter(ApplicationFilterConfig.java:281)
    at org.apache.catalina.core.ApplicationFilterConfig.getFilter(ApplicationFilterConfig.java:262)
    at org.apache.catalina.core.ApplicationFilterConfig.<init>(ApplicationFilterConfig.java:107)
    at org.apache.catalina.core.StandardContext.filterStart(StandardContext.java:4775)
    at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5452)
    at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
    at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1559)
    at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1549)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)

Jun 15, 2016 9:30:34 AM org.apache.catalina.core.StandardContext startInternal
SEVERE: Error filterStart
Jun 15, 2016 9:30:34 AM org.apache.catalina.core.StandardContext startInternal
SEVERE: Context [/azure-documentdb-java-sample] startup failed due to previous errors

**Comment by ilyaomsft** [comment] 2016-06-21 11:03
**Hello,**

Could you please check the following:
1. Can you activate the app without using the Application Insights Java SDK?
2. Are you using the Application Insights Java SDK Agent, or any other Java Agent?

**Comment by benlam62** [comment] 2016-06-22 01:51
1. Yes
2. Yes, I am using the agent provided by Microsoft.

**Comment by benlam62** [comment] 2016-06-22 15:04
I actually try to enable the app insight to the sample J2EE project published at https://github.com/Azure-Samples/documentdb-java-todo-app but throw the above exception.

**Comment by ilyaomsft** [comment] 2016-06-23 09:58
Please try the following:

1. Create a file named **AI-Agent.xml** and place it in the same folder as the agent JAR file
2. Set the content of the xml file:

```xml
<?xml version="1.0" encoding="utf-8"?>
<ApplicationInsightsAgent>
    <Instrumentation>
        <BuiltIn enabled="true">
            <HTTP enabled="false"/>
        </BuiltIn>
    </Instrumentation>
</ApplicationInsightsAgent>
```
Please let me know if it works

**Comment by oak-tree** [comment] 2016-07-27 19:42
Seems like I have the same issue: 
AI: ERROR 27-07-2016 15:38, 1: Failed to register 'ApplicationInsightsWebFilter', exception: 'com/microsoft/applicationinsights/agent/internal/coresync/AgentNotificationsHandler'

I followed the instruction in both 
https://azure.microsoft.com/en-us/documentation/articles/app-insights-java-get-started/
https://azure.microsoft.com/en-us/documentation/articles/app-insights-java-trace-logs/

`Trace` seems to work but all other not 


`web.xml`

```
<filter>
	  <filter-name>ApplicationInsightsWebFilter</filter-name>
	  <filter-class>
	    com.microsoft.applicationinsights.web.internal.WebRequestTrackingFilter
	  </filter-class>
	</filter>
	<filter-mapping>
	   <filter-name>ApplicationInsightsWebFilter</filter-name>
	   <url-pattern>/*</url-pattern>
	</filter-mapping>
```

**Comment by OriYosefiMSFT** [comment] 2016-08-18 07:51
This line is not really an error but rather a misleading trace:

> AI: ERROR 18-08-2016 03:45, 15: Failed to register 'ApplicationInsightsWebFilter', exception: 'com/microsoft/applicationinsights/agent/internal/coresync/AgentNotificationsHandler'

It only means that the agent is not runnng and is not used. I have opened #317 to change the misleading trace. 

The following exception does seem like an issue though:

> java.lang.NoClassDefFoundError: Could not initialize class org.apache.http.impl.conn.ManagedHttpClientConnectionFactory 

I will look into it

**Comment by Dmitry-Matveev** [comment] 2017-02-02 02:24
I think this issue was addressed in 1.0.7 by packaging all the necessary dependencies (including apache connection classes) into the Core JAR of JAVA SDK, this class should not always be available for AI Java SDK consumption.

**Closed by Dmitry-Matveev** 2017-02-02 02:24 UTC

**Comment by JunQianZ** [comment] 2017-12-16 08:46
I met this issue, my localhost website used to work. after add the application insight SDK, it showed 404 web page error， as below.  
![image](https://user-images.githubusercontent.com/7043827/34068923-42d9a9fc-e280-11e7-8002-96485f0f1422.png)

and the error messages in tomcat is same as above, 
 Registering WebApp with name 'altoro'
AI: ERROR 16-12-2017 09:20, 14: Failed to register 'ApplicationInsightsWebFilter', exception: 'com/microsoft/applicationinsights/agent/internal/coresync/AgentNotificationsHandler'
12月 16, 2017 9:20:38 上午 org.apache.catalina.core.StandardContext filterStart
SEVERE: Exception starting filter ApplicationInsightsWebFilter
java.lang.NoClassDefFoundError: javax/xml/bind/JAXBException
	at com.microsoft.applicationinsights.internal.config.TelemetryConfigurationFactory.<init>(TelemetryConfigurationFactory.java:65)
	at com.microsoft.applicationinsights.internal.config.TelemetryConfigurationFactory.<clinit>(TelemetryConfigurationFactory.java:54)
	at com.microsoft.applicationinsights.TelemetryConfiguration.getActive(TelemetryConfiguration.java:72)
	at com.microsoft.applicationinsights.web.internal.WebRequestTrackingFilter.init(WebRequestTrackingFilter.java:132)
	at org.apache.catalina.core.ApplicationFilterConfig.initFilter(ApplicationFilterConfig.java:279)
	at org.apache.catalina.core.ApplicationFilterConfig.getFilter(ApplicationFilterConfig.java:260)
	at org.apache.catalina.core.ApplicationFilterConfig.<init>(ApplicationFilterConfig.java:105)
	at org.apache.catalina.core.StandardContext.filterStart(StandardContext.java:4950)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5652)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:145)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1694)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1684)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.base/java.lang.Thread.run(Thread.java:844)
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.JAXBException
	at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1892)
	at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1735)
	... 16 more

and I checked my AI , it is of 1.0.3 . so any suggestion? thanks.

**Comment by JunQianZ** [comment] 2017-12-16 08:50
@Dmitry-Matveev  @benlam62 could you please show advice on how to solve it? thanks.

**Comment by dhaval24** [comment] 2017-12-16 18:29
Please try to update AI SDK to 1.0.10 and try again. Hopefully this issue is no longer there.

**Comment by koolkravi** [comment] 2019-02-12 20:40
@JunQianZ    did you able to fix your issue.
at run time i am getting jaxb class not found error.  ia m using spring boot and java10.

error trace.
Exception in thread "main" java.lang.NoClassDefFoundError: javax/xml/bind/JAXBException
	at com.microsoft.applicationinsights.internal.config.JaxbAppInsightsConfigurationBuilder.build(JaxbAppInsightsConfigurationBuilder.java:49)
	at com.microsoft.applicationinsights.internal.config.TelemetryConfigurationFactory.initialize(TelemetryConfigurationFactory.java:125)
	at com.microsoft.applicationinsights.TelemetryConfiguration.getActive(TelemetryConfiguration.java:70)
	at com.microsoft.applicationinsights.TelemetryClient.<init>(TelemetryClient.java:83)
	at com.microsoft.applicationinsights.internal.common.LogTelemetryClientProxy.<init>(LogTelemetryClientProxy.java:72)
	at com.microsoft.applicationinsights.log4j.v2.ApplicationInsightsAppender.<init>(ApplicationInsightsAppender.java:137)
	at com.microsoft.applicationinsights.log4j.v2.ApplicationInsightsAppender$Builder.build(ApplicationInsightsAppender.java:97)
	at com.microsoft.applicationinsights.log4j.v2.ApplicationInsightsAppender$Builder.build(ApplicationInsightsAppender.java:50)
	at org.apache.logging.log4j.core.config.plugins.util.PluginBuilder.build(PluginBuilder.java:123)
	at org.apache.logging.log4j.core.config.AbstractConfiguration.createPluginObject(AbstractConfiguration.java:959)
	at org.apache.logging.log4j.core.config.AbstractConfiguration.createConfiguration(AbstractConfiguration.java:899)
	at org.apache.logging.log4j.core.config.AbstractConfiguration.createConfiguration(AbstractConfiguration.java:891)
	at org.apache.logging.log4j.core.config.AbstractConfiguration.doConfigure(AbstractConfiguration.java:514)
	at org.apache.logging.log4j.core.config.AbstractConfiguration.initialize(AbstractConfiguration.java:238)
	at org.apache.logging.log4j.core.config.AbstractConfiguration.start(AbstractConfiguration.java:250)
	at org.apache.logging.log4j.core.LoggerContext.setConfiguration(LoggerContext.java:547)
	at org.apache.logging.log4j.core.LoggerContext.reconfigure(LoggerContext.java:619)
	at org.apache.logging.log4j.core.LoggerContext.reconfigure(LoggerContext.java:636)
	at org.apache.logging.log4j.core.LoggerContext.start(LoggerContext.java:231)
	at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:153)
	at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:45)
	at org.apache.logging.log4j.LogManager.getContext(LogManager.java:194)
	at org.apache.commons.logging.LogAdapter$Log4jLog.<clinit>(LogAdapter.java:155)
	at org.apache.commons.logging.LogAdapter$Log4jAdapter.createLog(LogAdapter.java:122)
	at org.apache.commons.logging.LogAdapter.createLog(LogAdapter.java:89)
	at org.apache.commons.logging.LogFactory.getLog(LogFactory.java:67)
	at org.apache.commons.logging.LogFactory.getLog(LogFactory.java:59)
	at org.springframework.boot.SpringApplication.<clinit>(SpringApplication.java:194)
	at com.example.helloworld.HelloworldApplication.main(HelloworldApplication.java:17)
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.JAXBException
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:582)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:190)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:499)
	... 29 more

**Comment by koolkravi** [comment] 2019-02-12 20:48
added below ppom dependecy to fix "java.lang.NoClassDefFoundError: javax/xml/bind/JAXBException"
                 <dependency>
			<groupId>javax.xml.bind</groupId>
			<artifactId>jaxb-api</artifactId>
			<version>2.3.0</version>
		</dependency>
