### ISSUE TITLE
place AppInsight xml in spring boot embedded tomcat container , All possible ways of having xml file inside class path. throws exception

### ISSUE THREAD

**Issue by M-Muni** [microsoft/ApplicationInsights-Java#472] opened 2017-11-29 13:34 UTC
i see no logs coming inside the search, my filter is set and im able to see device connected with AI. but no trace,request came in search. 
Also i found no ERROR in log messages.

**Comment by dhaval24** [comment] 2017-11-29 18:01
@M-Muni can you please add more details to this issue. What is your setup for AI. It is unclear wether your question is that you cannot see a request being executed on the AI-portal  / Log statement being missed to be reported on the portal.  I would like to see more details on how to reproduce the issue.

**Comment by M-Muni** [comment] 2017-11-30 06:31
i am trying to integrate AI in my spring boot application. i am . using log4j2.xml 
![image](https://user-images.githubusercontent.com/34096285/33416800-6b71b3aa-d5c4-11e7-9b33-180640be21ae.png)

log4j2.xml:

`<?xml version="1.0" encoding="UTF-8"?>
<Configuration packages="com.logger">
  <Appenders>
    <File name="rolling" fileName="/gateway.log">
      <PatternLayout>
        <Pattern>%d %p %c{1.} [%t] %m%n</Pattern>
      </PatternLayout>
    </File>
    <AIAppenderlog4j2 name="aiAppender" />    
    <Async name="Async">
      <AppenderRef ref="rolling"/>
    </Async>
  </Appenders>
  <Loggers>
    <Root level="info">
      <AppenderRef ref="aiAppender" />
      <AppenderRef ref="Async" />
    </Root>
  </Loggers>
</Configuration>`

ApplicationInsights.xml
`<?xml version="1.0" encoding="utf-8"?>
    <ApplicationInsights xmlns="http://schemas.microsoft.com/ApplicationInsights/2013/Settings" schemaVersion="2014-05-30">
 
 
 
      <InstrumentationKey>542</InstrumentationKey>
 
 
 
      <TelemetryModules>
        <Add type="com.microsoft.applicationinsights.web.extensibility.modules.WebRequestTrackingTelemetryModule"/>
      </TelemetryModules>
     
     <Channel>
    
    <DeveloperMode>true</DeveloperMode>
  </Channel>
 
      <TelemetryInitializers>
        <Add type="com.microsoft.applicationinsights.web.extensibility.initializers.WebOperationIdTelemetryInitializer"/>
        <Add type="com.microsoft.applicationinsights.web.extensibility.initializers.WebOperationNameTelemetryInitializer"/>
         <Add type="com.microsoft.applicationinsights.web.extensibility.initializers.WebSessionTelemetryInitializer"/>
        <Add type="com.microsoft.applicationinsights.web.extensibility.initializers.WebUserTelemetryInitializer"/>
        <Add type="com.microsoft.applicationinsights.web.extensibility.initializers.WebUserAgentTelemetryInitializer"/>
      </TelemetryInitializers>
 
      
 
</ApplicationInsights>
`
it is a gradle project and in build.gradle i am excluding ApplicationInsight.xml files as i want to give runtime changes on them.
jar {
  manifest {
    attributes 'Main-Class': 'Application'
    }
	
    //rootSpec.exclude("ApplicationInsights.xml")
    baseName = 'file-gateway'
   }

AI not picks up the ApplicationInsight.xml even if i give them in classpath
java -jar build/libs/file-gateway.jar --spring.config.location=classpath:/apps/conf/ApplicationInsight.xml .

java -jar build/libs/file-gateway.jar --spring.config.location=file:/apps/conf/ApplicationInsight.xml .


But with fat jar (with out exclusion of ApplicationInsight.xml  ) it works fine, AI picks up the xml perfectly and i can see server added in Ai portal .

Even i tried via code, but i see no appending with AI
`    @Bean
    public String telemetryConfig() {
        if(!filterName.equalsIgnoreCase("mockAIFilter"))
        {
            String telemetryKey = appInsightKey;
            if (telemetryKey != null) {
            	
            	System.out.println("Telemetry is Set" + appInsightKey);
            		//TelemetryConfiguration telemetry = TelemetryConfiguration.createDefault(); //.setInstrumentationKey(appInsightKey);;
            		//telemetry.setInstrumentationKey(appInsightKey);
            		TelemetryConfiguration.getActive().setInstrumentationKey(appInsightKey);
                
            }
            return telemetryKey;
        }
        else
            return null;
    }`

i appreciate any work around or solution in place .

**Comment by dhaval24** [comment] 2017-11-30 16:17
@M-Muni in case of Spring boot, you need to programatically configure some parts along with the xml. here is how you can do it : https://github.com/AzureCAT-GSI/DevCamp/tree/master/HOL/java/06-appinsights

I have never personally tried excluding the xml file from the Jar, as far as I believe that the configuration modules of AI were designed to have the xml file in war/jar file. However, we will try to replicate it on our end and see if it is possible.

**Comment by dhaval24** [comment] 2017-12-04 16:27
@M-Muni were you able to give a try to above link? Does the problem still persist? #477 might be what you are looking for, and if so please let us know.

**Comment by M-Muni** [comment] 2017-12-08 09:11
I tired with #477 ,  but again spring resources read that applicaitoninsights.xml . 

`	AI: INFO 08-12-2017 14:32, 1: Did not find configuration file 'ApplicationInsights.xml' in 'file:/libs/file-gateway.jar!/BOOT-INF/lib/asm-tree-5.0.3.jar!'
AI: INFO 08-12-2017 14:32, 1: Did not find configuration file 'ApplicationInsights.xml' in 'file:/libs/file-gateway.jar!/BOOT-INF/lib/asm-5.0.3.jar!'
AI: INFO 08-12-2017 14:32, 1: Did not find configuration file 'ApplicationInsights.xml' in 'file:/libs/file-gateway.jar!/BOOT-INF/lib/jnr-x86asm-1.0.2.jar!'
AI: INFO 08-12-2017 14:32, 1: Did not find configuration file 'ApplicationInsights.xml' in 'file:/libs/file-gateway.jar!/BOOT-INF/lib/jnr-constants-0.9.0.jar!'
AI: WARN 08-12-2017 14:32, 1: Configuration file 'ApplicationInsights.xml' could not be found
AI: ERROR 08-12-2017 14:32, 19: WebApp name is not found, unable to register WebApp
AI: INFO 08-12-2017 14:32, 19: Successfully registered the filter 'ApplicationInsightsWebFilter'
Configuration file has been successfully found in: '%s'/apps/Symantec/shasta/gateway/conf/ApplicationInsights.xml
`
**Configuration file got picked up. but it didn't reflect in AI.**



Here is my confLoader file
`
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.InputStream;
import java.net.URI;
import java.net.URISyntaxException;
import java.net.URL;
import java.net.URLClassLoader;
import java.security.CodeSource;
import java.util.HashSet;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.stereotype.Component;

import com.microsoft.applicationinsights.internal.config.ConfigurationFileLocator;
import com.microsoft.applicationinsights.internal.config.TelemetryConfigurationFactory;

@Component
public class ConfigurationFIleLoader {
	private static final Logger logger = LoggerFactory.getLogger(ConfigurationFIleLoader.class);

	
	
	 
	 public InputStream getConfigurationFile() {

		 System.out.println(applicationInsightLocation + " : " + configurationFile);
	        String configurationFile=null;
	        InputStream inputStream;

	        // first try to get from dir defined explicitly in system property insights.configurationFile
	        String configDirFromProperty = "dummy";//System.getProperty(applicationInsightLocation);
	        if (configDirFromProperty != null) {
	            configurationFile =  "/apps/conf/ApplicationInsights.xml";//getConfigurationAbsolutePath(configDirFromProperty);
	        } else {

	            inputStream = ConfigurationFileLocator.class.getClassLoader().getResourceAsStream(configurationFile);
	            if (inputStream != null) {
	               System.out.println("Configuration file has been successfully found as resource");
	                return inputStream;
	            }

	            // Trying to load configuration as a resource.
	            configurationFile = getConfigurationFromCurrentClassLoader();

	            // If not found as a resource, trying to load from the executing jar directory
	            if (configurationFile == null) {
	                configurationFile = getConfigurationFromLibraryLocation();

	                // If still not found try to get it from the class path
	                if (configurationFile == null) {
	                    configurationFile = getConfFromClassPath();
	                }
	            }
	        }

	        if (configurationFile != null) {
	           System.out.println( "Configuration file has been successfully found in: '%s'" +  configurationFile);
	            try {
	                return new FileInputStream(configurationFile);
	            } catch (FileNotFoundException e) {
	                System.out.println( "Configuration file '%s' could not be opened for reading" + configurationFile);
	            }
	        } else {
	            System.out.println( "Configuration file '%s' could not be found" + configurationFile);
	        }
	        return null;
	    }
	 
	 private static void logException(Throwable t, String message) {
	        if (t.getCause() != null) {
	            System.out.println( "Failed to find configuration file, exception while fetching from %s: '%s'" + message + t.getCause().getMessage());
	        } else {
	            System.out.println( "Failed to find configuration file, exception while fetching from %s: '%s'" + message + t.getMessage());
	        }
	    }

	    private String getConfigurationFromCurrentClassLoader() {
	        try {
	            ClassLoader classLoader = ConfigurationFileLocator.class.getClassLoader();
	            String configurationFile = null;
	            URL resourceUrl = classLoader.getResource(configurationFile);
	            if (resourceUrl != null) {
	                File filePath = normalizeUrlToFile(resourceUrl);
	                if (filePath != null) {
	                    configurationFile = filePath.toString();
	                }
	            }

	           System.out.println(
	                    "Configuration file '%s' was %sfound by default class loader"+
	                    configurationFile +
	                    configurationFile == null ? "NOT " : "");

	            return configurationFile;
	        } catch (Throwable t) {
	            logException(t, "current class loader");
	        }

	        return null;
	    }

	    private String getConfigurationFromLibraryLocation() {
	        try {
	            CodeSource codeSource = ConfigurationFileLocator.class.getProtectionDomain().getCodeSource();
	            if (codeSource == null) {
	                return null;
	            }

	            String jarFullPath = codeSource.getLocation().toURI().getPath();
	            File jarFile = new File(jarFullPath);

	            if (jarFile.exists()) {
	                String jarDirectory = jarFile.getParent();
	                String configurationPath = getConfigurationAbsolutePath(jarDirectory);
	                if (configurationPath != null) {
	                    return configurationPath;
	                }
	            } else {
	                System.out.println( "Can not access folder '%s'" + jarFullPath);
	            } System.out.println();
	        } catch (Throwable t) {
	            logException(t, "library location");
	        }
	        return null;
	    }

	    private String getConfFromClassPath() {
	        try {
	            ClassLoader classLoader = TelemetryConfigurationFactory.class.getClassLoader();
	            if (!(classLoader instanceof URLClassLoader)) {
	                return null;
	            }

	            HashSet<String> checkedUrls = new HashSet<String>();

	            URL[] urls = ((URLClassLoader) classLoader).getURLs();
	            for (URL url : urls) {
	                File filePath = normalizeUrlToFile(url);

	                if (filePath == null) {
	                    continue;
	                }

	                if (filePath.isFile()) {
	                    filePath = filePath.getParentFile();
	                }

	                String configurationPath = filePath.toString();

	                if (checkedUrls.contains(configurationPath)) {
	                    continue;
	                }

	                String configurationFile = getConfigurationAbsolutePath(configurationPath);
	                if (configurationFile != null) {
	                    return configurationFile;
	                } else {
	                    checkedUrls.add(configurationPath);
	                }
	            }
	        } catch (Throwable t) {
	            logException(t, "class path");
	        }
	        return null;
	    }

	    private String getConfigurationAbsolutePath(String path) {
	        File configFile = new File(path, configurationFile);

	        System.out.println("path :" + path + "conf :" + configurationFile);
	        if (configFile.exists()) {
	            return configFile.getAbsolutePath();
	        }

	       System.out.println( "Did not find configuration file '%s' in '%s'" +  configurationFile + path);


	        return null;
	    }

	    private File normalizeUrlToFile(URL url) {
	        URI uri;
	        try {
	            uri = url.toURI();
	        } catch (URISyntaxException e) {
	           System.out.println( "Failed to convert URL '%s' to URI " + url);
	            return null;
	        }

	        return new File(uri.getSchemeSpecificPart());
	    }
}
`

**Comment by dhaval24** [comment] 2017-12-09 18:00
If I understand this issue correctly, you tried to incorporate the code changes from this PR into Spring Component class in your application, but my point here was that you would have to build the source code locally by pulling the latest master. Here is the reason for this : 

This is a part of initialization phase when the configuration for AI is loaded. Now even if you add additional code to your application, the AI SDK Jars residing in your application are still the old ones and has the unchanged initialization logic and hence the logs.  Here are simple steps to build the application:
1. Clone / fork the repository
2. Build master by running -- gradlew clean, gradlew assemble, gradlew test, gradlew build
3. The core, web and agent jars would be inside their respective folders.

And just FYI : The code in the PR suggests that the property be passed as the following parameter
"applicationinsights.configurationDirectory"

Let me know if this helps! or I might be totally mistaken here.

**Comment by M-Muni** [comment] 2017-12-13 11:19
Hi Dhaval,


i see the following warning while build the latest PR

> Configure project :core 
IMPORTANT: Environment variable 'JAVA_JRE_7' is not defined - Install JRE 7 and set 'JAVA_JRE_7' to prevent runtime compatibility issues!
Native binaries build is only supported on Windows systems; native components will not be built.

> Configure project :distributions 
IMPORTANT: Environment variable 'JAVA_JRE_7' is not defined - Install JRE 7 and set 'JAVA_JRE_7' to prevent runtime compatibility issues!

> Configure project :samples 
IMPORTANT: Environment variable 'JAVA_JRE_7' is not defined - Install JRE 7 and set 'JAVA_JRE_7' to prevent runtime compatibility issues!



Also i see java compatible error with it. Is it possible for you to change the versioning there?

JDK 7
This version of the JDK is no longer current
Java 7 is outdated ,

**Comment by M-Muni** [comment] 2017-12-13 13:34
jar created by following way:
ApplicationInsights-Java-master: gradle clean
ApplicationInsights-Java-master: gradle build

my application run in java1.8
gradle version 4.4
i got the following error when i integrate applicationInsight-java-snapshot-jars:
**bootstrap class path not set in conjunction with -source 1.7**

could you build the PR in java 1.8 and let us know!?

**Comment by dhaval24** [comment] 2017-12-13 18:19
@M-Muni all the changes in that PR are also now merged with the Master, so you can directly build Master.  As far as I know that we will build JARS with JDK 1.7 to provide backward compatibility. However, if you have JAVA_HOME set to JDK 1.8 then Jars would build fine, though you will see this warnings you can ignore them. As far as I know we are currently on Gradle 3.5 (we eventually plan to go up, but not yet). @littleaj can comment on this more.

**Comment by M-Muni** [comment] 2017-12-14 10:29
No node picked up by AI.

i took the master and made a gradle build, here i found  the following jars 
applicationinsights-agent-2.0.0-BETA-SNAPSHOT.jar,
applicationinsights-core-2.0.0-BETA-SNAPSHOT.jar
applicationinsights-logging-log4j2-2.0.0-BETA-SNAPSHOT.jar
applicationinsights-web-2.0.0-BETA-SNAPSHOT.jar

i added above jars under build path and removed  the below jar from build path.

< compile (group: 'com.microsoft.azure', name: 'applicationinsights-web', version: "1.+"){ transitive = false }
 compile group: 'com.microsoft.azure', name: 'applicationinsights-logging-log4j2', version: '1.0.+'
compile (group: 'com.microsoft.azure', name: 'applicationinsights-core', version: "1.+"){ transitive = false } >

Here is the bean creation to set external file.

< String fileName="/apps/conf/ApplicationInsights.xml"
 @Bean
      public ConfigurationFileLocator confLocator()
      {
        
             System.out.println("fileName " + fileName);
           return new ConfigurationFileLocator(fileName);
      } >


**logs:**
AI: INFO 14-12-2017 15:31, 1: Configuration file 'ApplicationInsights.xml' was NOT found by default class loader
AI: WARN 14-12-2017 15:31, 1: Failed to find configuration file, exception while fetching from library location: 'null'
AI: INFO 14-12-2017 15:31, 1: Did not find configuration file 'ApplicationInsights.xml' in 'file:/Users/file-gateway-1/build/libs/file-gateway.jar!/BOOT-INF/classes!'


gradle version=3.5
java=1.8


All i am looking for is a springboot-embedded-tomcat project jar which will take AI.xml from outside.

Or , how to push external xml to springboot-embedded-tomcat container where jar resides, the external xml would be ApplicationInsights.xml.

Appreciate any help.

**Comment by M-Muni** [comment] 2017-12-14 10:30
No node picked up by AI.

i took the master and made a gradle build, here i found  the following jars 
applicationinsights-agent-2.0.0-BETA-SNAPSHOT.jar,
applicationinsights-core-2.0.0-BETA-SNAPSHOT.jar
applicationinsights-logging-log4j2-2.0.0-BETA-SNAPSHOT.jar
applicationinsights-web-2.0.0-BETA-SNAPSHOT.jar

i added above jars under build path and removed  the below jar from build path.

< compile (group: 'com.microsoft.azure', name: 'applicationinsights-web', version: "1.+"){ transitive = false }
 compile group: 'com.microsoft.azure', name: 'applicationinsights-logging-log4j2', version: '1.0.+'
compile (group: 'com.microsoft.azure', name: 'applicationinsights-core', version: "1.+"){ transitive = false } >

Here is the bean creation to set external file.

< String fileName="/apps/conf/ApplicationInsights.xml"
 @Bean
      public ConfigurationFileLocator confLocator()
      {
        
             System.out.println("fileName " + fileName);
           return new ConfigurationFileLocator(fileName);
      } >


**logs:**
AI: INFO 14-12-2017 15:31, 1: Configuration file 'ApplicationInsights.xml' was NOT found by default class loader
AI: WARN 14-12-2017 15:31, 1: Failed to find configuration file, exception while fetching from library location: 'null'
AI: INFO 14-12-2017 15:31, 1: Did not find configuration file 'ApplicationInsights.xml' in 'file:/Users/file-gateway-1/build/libs/file-gateway.jar!/BOOT-INF/classes!'


gradle version=3.5
java=1.8


All i am looking for is a springboot-embedded-tomcat project jar which will take AI.xml from outside.

Or , how to push external xml to springboot-embedded-tomcat container where jar resides, the external xml would be ApplicationInsights.xml.

Appreciate any help.

**Comment by M-Muni** [comment] 2017-12-14 10:30
No node picked up by AI.

i took the master and made a gradle build, here i found  the following jars 
applicationinsights-agent-2.0.0-BETA-SNAPSHOT.jar,
applicationinsights-core-2.0.0-BETA-SNAPSHOT.jar
applicationinsights-logging-log4j2-2.0.0-BETA-SNAPSHOT.jar
applicationinsights-web-2.0.0-BETA-SNAPSHOT.jar

i added above jars under build path and removed  the below jar from build path.

< compile (group: 'com.microsoft.azure', name: 'applicationinsights-web', version: "1.+"){ transitive = false }
 compile group: 'com.microsoft.azure', name: 'applicationinsights-logging-log4j2', version: '1.0.+'
compile (group: 'com.microsoft.azure', name: 'applicationinsights-core', version: "1.+"){ transitive = false } >

Here is the bean creation to set external file.

< String fileName="/apps/conf/ApplicationInsights.xml"
 @Bean
      public ConfigurationFileLocator confLocator()
      {
        
             System.out.println("fileName " + fileName);
           return new ConfigurationFileLocator(fileName);
      } >


**logs:**
AI: INFO 14-12-2017 15:31, 1: Configuration file 'ApplicationInsights.xml' was NOT found by default class loader
AI: WARN 14-12-2017 15:31, 1: Failed to find configuration file, exception while fetching from library location: 'null'
AI: INFO 14-12-2017 15:31, 1: Did not find configuration file 'ApplicationInsights.xml' in 'file:/Users/file-gateway-1/build/libs/file-gateway.jar!/BOOT-INF/classes!'


gradle version=3.5
java=1.8


All i am looking for is a springboot-embedded-tomcat project jar which will take AI.xml from outside.

Or , how to push external xml to springboot-embedded-tomcat container where jar resides, the external xml would be ApplicationInsights.xml.

Appreciate any help.

**Comment by dhaval24** [comment] 2017-12-14 23:11
@M-Muni if I understand correctly you can pass this as a command line argument:

-applicationinsights.configurationDirectory = "path of ApplicationInsights.xml" reside and the application should pick up. I haven't tried it personally but I believe based on the code should be working.

**Comment by M-Muni** [comment] 2017-12-15 05:55
@dhaval24  , i tried that too.
1. java -jar build/libs/file-gateway.jar -applicationinsights.configurationDirectory="/apps/conf/"
2. java -jar build/libs/file-gateway.jar -applicationinsights.configurationDirectory="/apps/conf/ApplicationInsights.xml"

Still AI didn't picked ApplicationInsights.xml
AI always looks for ApplicationInsights.xml  file under **JarName.jar!/BOOT-INF/lib/**  folder.

**Comment by M-Muni** [comment] 2017-12-28 09:46
@dhaval24 any chance to see the above issue?

**Comment by dhaval24** [comment] 2017-12-28 18:41
@M-Muni I am sorry as I did not got any chance to have a look at this yet.

**Comment by dhaval24** [comment] 2018-06-18 20:33
@M-Muni have you tried ApplicationInsights-SpringBoot-Starter? If not please give it a shot. I think it should resolve this problem entirely.

**Comment by littleaj** [comment] 2019-07-31 18:27
@M-Muni do you still see this issue with the latest version, 2.4.0?

**Closed** 2020-06-10 03:14 UTC
Labels: Question, Team-Triaged, help wanted
