### ISSUE TITLE
Application insights Spring boot starter showing circular reference error?

### ISSUE THREAD

**Issue by ken-hum** [Microsoft/ApplicationInsights-Java#691] opened 2018-06-20 13:08 UTC
Hi all, I am trying to use application insights spring booter as part of my spring application. I believe to have correctly created the Application Insight resource in Azure Portal. Also the instrumentation key is properly put in the application.properties.

Spring Version:  :: Spring Boot ::       (v1.5.10.RELEASE)
Java = open JDK 1.8

Upon boot, i get this? Any hints?

2018-06-20T12:54:00.845,ERROR,org.springframework.boot.SpringApplication-771,main,"Application startup failed"
org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'com.microsoft.applicationinsights.boot.ApplicationInsightsTelemetryAutoConfiguration': Unsatisfied dependency expressed through method 'setTelemetryModules' parameter 0; nested exception is org.springframework.beans.factory.BeanCurrentlyInCreationException: Error creating bean with name 'performanceCounterContainer': Requested bean is currently in creation: Is there an unresolvable circular reference?
        at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredMethodElement.inject(AutowiredAnnotationBeanPostProcessor.java:667) ~[spring-beans-4.3.13.RELEASE.jar!/:4.3.13.RELEASE]
        at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:88) ~[spring-beans-4.3.13.RELEASE.jar!/:4.3.13.RELEASE]
        at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessPropertyValues(AutowiredAnnotationBeanPostProcessor.java:366) ~[spring-beans-4.3.13.RELEASE.jar!/:4.3.13.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1264) ~[spring-beans-4.3.13.RELEASE.jar!/:4.3.13.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:553) ~[spring-beans-4.3.13.RELEASE.jar!/:4.3.13.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:483) ~[spring-beans-4.3.13.RELEASE.jar!/:4.3.13.RELEASE]
        at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306) ~[spring-beans-4.3.13.RELEASE.jar!/:4.3.13.RELEASE]
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230) ~[spring-beans-4.3.13.RELEASE.jar!/:4.3.13.RELEASE]
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302) ~[spring-beans-4.3.13.RELEASE.jar!/:4.3.13.RELEASE]
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197) ~[spring-beans-4.3.13.RELEASE.jar!/:4.3.13.RELEASE]
        at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:372) ~[spring-beans-4.3.13.RELEASE.jar!/:4.3.13.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1173) ~[spring-beans-4.3.13.RELEASE.jar!/:4.3.13.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1067) ~[spring-beans-4.3.13.RELEASE.jar!/:4.3.13.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:513) ~[spring-beans-4.3.13.RELEASE.jar!/:4.3.13.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:483) ~[spring-beans-4.3.13.RELEASE.jar!/:4.3.13.RELEASE]
        at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306) ~[spring-beans-4.3.13.RELEASE.jar!/:4.3.13.RELEASE]
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230) ~[spring-beans-4.3.13.RELEASE.jar!/:4.3.13.RELEASE]
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302) ~[spring-beans-4.3.13.RELEASE.jar!/:4.3.13.RELEASE]
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197) ~[spring-beans-4.3.13.RELEASE.jar!/:4.3.13.RELEASE]
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:296) ~[spring-beans-4.3.13.RELEASE.jar!/:4.3.13.RELEASE]
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197) ~[spring-beans-4.3.13.RELEASE.jar!/:4.3.13.RELEASE]
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:761) ~[spring-beans-4.3.13.RELEASE.jar!/:4.3.13.RELEASE]
        at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:867) ~[spring-context-4.3.13.RELEASE.jar!/:4.3.13.RELEASE]
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:543) ~[spring-context-4.3.13.RELEASE.jar!/:4.3.13.RELEASE]
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:693) [spring-boot-1.5.10.RELEASE.jar!/:1.5.10.RELEASE]
        at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:360) [spring-boot-1.5.10.RELEASE.jar!/:1.5.10.RELEASE]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:303) [spring-boot-1.5.10.RELEASE.jar!/:1.5.10.RELEASE]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1118) [spring-boot-1.5.10.RELEASE.jar!/:1.5.10.RELEASE]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1107) [spring-boot-1.5.10.RELEASE.jar!/:1.5.10.RELEASE]
        at com.nuance.clu.service.StartService.main(StartService.java:18) [classes!/:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_171]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_171]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_171]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_171]
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48) [Start-1.0-SNAPSHOT.jar:?]
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:87) [Start-1.0-SNAPSHOT.jar:?]
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:50) [Start-1.0-SNAPSHOT.jar:?]
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51) [Start-1.0-SNAPSHOT.jar:?]
Caused by: org.springframework.beans.factory.BeanCurrentlyInCreationException: Error creating bean with name 'performanceCounterContainer': Requested bean is currently in creation: Is there an unresolvable circular reference?
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.beforeSingletonCreation(DefaultSingletonBeanRegistry.java:347) ~[spring-beans-4.3.13.RELEASE.jar!/:4.3.13.RELEASE]
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:223) ~[spring-beans-4.3.13.RELEASE.jar!/:4.3.13.RELEASE]
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302) ~[spring-beans-4.3.13.RELEASE.jar!/:4.3.13.RELEASE]
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197) ~[spring-beans-4.3.13.RELEASE.jar!/:4.3.13.RELEASE]
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:296) ~[spring-beans-4.3.13.RELEASE.jar!/:4.3.13.RELEASE]
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202) ~[spring-beans-4.3.13.RELEASE.jar!/:4.3.13.RELEASE]
        at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:208) ~[spring-beans-4.3.13.RELEASE.jar!/:4.3.13.RELEASE]
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.addCandidateEntry(DefaultListableBeanFactory.java:1316) ~[spring-beans-4.3.13.RELEASE.jar!/:4.3.13.RELEASE]
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.findAutowireCandidates(DefaultListableBeanFactory.java:1282) ~[spring-beans-4.3.13.RELEASE.jar!/:4.3.13.RELEASE]
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveMultipleBeans(DefaultListableBeanFactory.java:1180) ~[spring-beans-4.3.13.RELEASE.jar!/:4.3.13.RELEASE]
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1096) ~[spring-beans-4.3.13.RELEASE.jar!/:4.3.13.RELEASE]
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1066) ~[spring-beans-4.3.13.RELEASE.jar!/:4.3.13.RELEASE]
        at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredMethodElement.inject(AutowiredAnnotationBeanPostProcessor.java:659) ~[spring-beans-4.3.13.RELEASE.jar!/:4.3.13.RELEASE]
        ... 37 more

**Comment by dhaval24** [comment] 2018-06-21 22:44
@ken-hum  I tried to reproduce this issue on the plain springboot app with springboot 1.5.10 and jdk8 and I was not able to find this when I did mvn clean package. 
Is it possible for you to upload a sample / trimmed down version of your app for further diagnosis?

**Comment by dhaval24** [comment] 2018-06-30 19:13
@pietrobr and @ken-hum I am still not able to reproduce this . This time I exactly followed tutorial which I published word by word with SpringBoot 1.5.10 version and JDK 1.8. My application successfully starts and I am also able to see all the telemetry on the portal. I am attaching the sample app which I created here. You can try it out by inserting your instrumentation key and hit `mvn clean package `
and `mvn spring-boot:run`

**Comment by dhaval24** [comment] 2018-06-30 19:17
[demo.zip](https://github.com/Microsoft/ApplicationInsights-Java/files/2152116/demo.zip)

Here is the sample app I had tried to reproduce the issue mentioned (exactly following the tutorial)

**Comment by dhaval24** [comment] 2018-07-01 20:02
@pietrobr no worries. Glad it helped

**Comment by ken-hum** [comment] 2018-07-03 17:28
Hi dhaval24, the demo you've sent is a webapp. I am getting the error on a core-app.
We just got out from call with Rahul Gupta and Chandresh Govani (from Microsoft) talking about this issue. I will update you with a trimmed app very soon.

**Comment by dhaval24** [comment] 2018-07-03 17:31
@ken-hum makes sense. Is your application a spring-boot rest service instead? Sorry, I am a bit confused when you say it's a core app.

**Comment by zhouchong90** [comment] 2018-07-04 17:18
I have the same issue too.
my pom:
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>

	<parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>2.0.3.RELEASE</version>
		<relativePath/> 
	</parent>

	<properties>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
		<project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
		<java.version>1.8</java.version>
	</properties>

	<dependencies>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter</artifactId>
		</dependency>
		<dependency>
			<groupId>com.microsoft.azure</groupId>
			<artifactId>azure-storage</artifactId>
			<version>7.0.0</version>
		</dependency>
		<dependency>
			<groupId>io.projectreactor</groupId>
			<artifactId>reactor-core</artifactId>
			<version>3.1.8.RELEASE</version>
		</dependency>

		<dependency>
			<groupId>org.projectlombok</groupId>
			<artifactId>lombok</artifactId>
			<version>1.18.0</version>
			<scope>provided</scope>
		</dependency>

		
        <dependency>
            <groupId>com.microsoft.azure</groupId>
            <artifactId>applicationinsights-spring-boot-starter</artifactId>
            <version>1.0.0-BETA</version>
        </dependency>
        
            
            
            
        
		<dependency>
			<groupId>com.microsoft.azure</groupId>
			<artifactId>applicationinsights-logging-logback</artifactId>
			<version>[2.0,)</version>
		</dependency>

		
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-test</artifactId>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>io.projectreactor</groupId>
			<artifactId>reactor-test</artifactId>
			<version>3.1.8.RELEASE</version>
			<scope>test</scope>
		</dependency>

		<dependency>
			<groupId>org.testng</groupId>
			<artifactId>testng</artifactId>
			<version>6.14.3</version>
			<scope>test</scope>
		</dependency>
	</dependencies>

	<build>
		<plugins>
			<plugin>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-maven-plugin</artifactId>
			</plugin>
		</plugins>
	</build>


</project>

And I configured logback-spring.xml to be
<?xml version="1.0" encoding="UTF-8"?>
<configuration>
    <property name="LOG_DIR" value="logs"/>

    <appender name="STDOUT" class="ch.qos.logback.core.ConsoleAppender">
        <encoder>
            <pattern>
                %d{yyyy/MM/dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n
            </pattern>
        </encoder>
    </appender>

    <appender name="aiAppender"
              class="com.microsoft.applicationinsights.logback.ApplicationInsightsAppender">
    </appender>

    <springProfile name="dev">
        <root level="info">
            <appender-ref ref="STDOUT"/>
            <appender-ref ref="aiAppender"/>
        </root>
    </springProfile>

    <springProfile name="prod">
        <root level="ERROR">
            <appender-ref ref="aiAppender"/>
        </root>
    </springProfile>

</configuration>

It shows the circular bean error.

**Comment by dhaval24** [comment] 2018-07-04 18:58
@zhouchong90 are you getting the exact same issue as @ken-hum ? I am trying to reproduce the issue on my end and am still not successful. I have also configured logback in my sample project which I have uploaded in the thread and I can see all the traces coming to AI portal. My application also boots up as normal. 

However one change :  Instead of using `<version>[2.0,)</version>` in my pom.xml I have specified the exact version number of logback - `<version>2.1.1</version>` to avoid any sort of classpath hell.  Could you please try this and let me know. If that doesn't work out I would suggest uploading a trim down version of your application to debug further.

**Comment by ken-hum** [comment] 2018-07-05 13:50
[TrimmedStart.zip](https://github.com/Microsoft/ApplicationInsights-Java/files/2166804/TrimmedStart.zip)

Hi Dhaval24, I've attached the sample app that reproduced that error. thanks

**Comment by dhaval24** [comment] 2018-07-05 15:04
@ken-hum thank you very much for providing the trimmed down version of the app. I will take a look soon.

**Comment by zhouchong90** [comment] 2018-07-05 17:12
@dhaval24 Somehow changing the version made it work! And when I change it back to <version>[2.0,)</version>, it still works correctly. I don't understand why, but thanks!

**Comment by dhaval24** [comment] 2018-07-06 03:34
@ken-hum I have deleted your post. Please ensure that it doesn't contain any sensitive information.

**Comment by ken-hum** [comment] 2018-07-13 13:59
Hi Dhaval, any updates?? thanks

**Comment by dhaval24** [comment] 2018-07-13 18:12
@ken-hum I haven't got a chance to dig deep for the exact root cause of this issue. As soon as I have a chance to determine the root cause I will update the thread.

**Comment by dhaval24** [comment] 2018-07-19 22:39
@ken-hum I have created a PR to fix this. It should be fixed in our next release. Thanks

**Comment by ken-hum** [comment] 2018-07-23 18:13
Hi Dhaval24, i tried the fix from branch. The spring service is now able to start.

However, it fails right away with another error:
2018-07-23 14:11:08.343  INFO 14696 --- [           main] o.s.c.support.DefaultLifecycleProcessor  : Starting beans in phase 0
2018-07-23 14:11:08.638  INFO 14696 --- [           main] com.sample.StartService                  : Started StartService in 5.356 seconds (JVM running for 6.121)
actuatorMetricReader
auditEventRepository
auditEventsEndpoint
auditListener
autoConfigurationReportEndpoint
azure.application-insights-com.microsoft.applicationinsights.boot.ApplicationInsightsProperties
beansEndpoint
com.microsoft.applicationinsights.boot.ApplicationInsightsModuleConfiguration
com.microsoft.applicationinsights.boot.ApplicationInsightsTelemetryAutoConfiguration
configurationPropertiesReportEndpoint
counterBuffers
counterService
deviceInfoContextInitializer
diskSpaceHealthIndicator
diskSpaceHealthIndicatorProperties
dumpEndpoint
endpointMBeanExporter
endpoints-org.springframework.boot.actuate.endpoint.EndpointProperties
endpoints.jmx-org.springframework.boot.actuate.autoconfigure.EndpointMBeanExportProperties
envInfoContributor
environmentEndpoint
gaugeBuffers
gaugeService
healthAggregator
healthEndpoint
heartBeatModule
heartBeatProviderInterface
infoEndpoint
internalLogger
jsonComponentModule
jvmPerformanceCountersModule
loggersEndpoint
management.health.status-org.springframework.boot.actuate.autoconfigure.HealthIndicatorProperties
management.info-org.springframework.boot.actuate.autoconfigure.InfoContributorProperties
managementServerProperties
mbeanExporter
mbeanServer
metricReaderPublicMetrics
metricWritersMetricExporter
metricsEndpoint
objectNamingStrategy
org.springframework.boot.actuate.autoconfigure.AuditAutoConfiguration
org.springframework.boot.actuate.autoconfigure.AuditAutoConfiguration$AuditEventRepositoryConfiguration
org.springframework.boot.actuate.autoconfigure.EndpointAutoConfiguration
org.springframework.boot.actuate.autoconfigure.EndpointMBeanExportAutoConfiguration
org.springframework.boot.actuate.autoconfigure.HealthIndicatorAutoConfiguration
org.springframework.boot.actuate.autoconfigure.HealthIndicatorAutoConfiguration$DiskSpaceHealthIndicatorConfiguration
org.springframework.boot.actuate.autoconfigure.InfoContributorAutoConfiguration
org.springframework.boot.actuate.autoconfigure.ManagementServerPropertiesAutoConfiguration
org.springframework.boot.actuate.autoconfigure.MetricExportAutoConfiguration
org.springframework.boot.actuate.autoconfigure.MetricExportAutoConfiguration$MetricExportPropertiesConfiguration
org.springframework.boot.actuate.autoconfigure.MetricExportAutoConfiguration$StatsdConfiguration
org.springframework.boot.actuate.autoconfigure.MetricRepositoryAutoConfiguration
org.springframework.boot.actuate.autoconfigure.MetricRepositoryAutoConfiguration$FastMetricServicesConfiguration
org.springframework.boot.actuate.autoconfigure.PublicMetricsAutoConfiguration
org.springframework.boot.actuate.autoconfigure.TraceRepositoryAutoConfiguration
org.springframework.boot.autoconfigure.AutoConfigurationPackages
org.springframework.boot.autoconfigure.condition.BeanTypeRegistry
org.springframework.boot.autoconfigure.context.ConfigurationPropertiesAutoConfiguration
org.springframework.boot.autoconfigure.context.PropertyPlaceholderAutoConfiguration
org.springframework.boot.autoconfigure.info.ProjectInfoAutoConfiguration
org.springframework.boot.autoconfigure.internalCachingMetadataReaderFactory
org.springframework.boot.autoconfigure.jackson.JacksonAutoConfiguration
org.springframework.boot.autoconfigure.jmx.JmxAutoConfiguration
org.springframework.boot.autoconfigure.web.WebClientAutoConfiguration
org.springframework.boot.context.properties.ConfigurationPropertiesBindingPostProcessor
org.springframework.boot.context.properties.ConfigurationPropertiesBindingPostProcessor.store
org.springframework.context.annotation.internalAutowiredAnnotationProcessor
org.springframework.context.annotation.internalCommonAnnotationProcessor
org.springframework.context.annotation.internalConfigurationAnnotationProcessor
org.springframework.context.annotation.internalRequiredAnnotationProcessor
org.springframework.context.annotation.internalScheduledAnnotationProcessor
org.springframework.context.event.internalEventListenerFactory
org.springframework.context.event.internalEventListenerProcessor
org.springframework.scheduling.annotation.SchedulingConfiguration
processPerformanceCountersModule
propertySourcesPlaceholderConfigurer
quickPulse
sdkVersionContextInitializer
shutdownEndpoint
spring.info-org.springframework.boot.autoconfigure.info.ProjectInfoProperties
spring.metrics.export-org.springframework.boot.actuate.metrics.export.MetricExportProperties
springBootTelemetryInitializer
startService
systemPublicMetrics
telemetryChannel
telemetryClient
telemetryConfiguration
traceEndpoint
traceRepository
2018-07-23 14:11:08.702  INFO 14696 --- [       Thread-6] s.c.a.AnnotationConfigApplicationContext : Closing org.springframework.context.annotation.AnnotationConfigApplicationContext@4b9af9a9: startup date [Mon Jul 23 14:11:04 EDT 2018]; root of context hierarchy
2018-07-23 14:11:08.706  INFO 14696 --- [       Thread-6] o.s.c.support.DefaultLifecycleProcessor  : Stopping beans in phase 0
2018-07-23 14:11:08.713  INFO 14696 --- [       Thread-6] o.s.j.e.a.AnnotationMBeanExporter        : Unregistering JMX-exposed beans on shutdown
2018-07-23 14:11:08.720  INFO 14696 --- [ulseCoordinator] c.m.a.c.d.http.impl.execchain.RetryExec  : I/O exception (java.net.SocketException) caught when processing request to {s}->https://rt.services.visualstudio.com:443: Socket closed
2018-07-23 14:11:08.720  INFO 14696 --- [ulseCoordinator] c.m.a.c.d.http.impl.execchain.RetryExec  : Retrying request to {s}->https://rt.services.visualstudio.com:443

**Comment by dhaval24** [comment] 2018-07-23 18:19
@ken-hum I haven't seen this before. Seems like you are having some trouble reaching the end point of AI. are you running your service under some sort of proxy? Do you face the issue in the same service that you had uploaded ?

**Comment by ken-hum** [comment] 2018-07-23 18:32
In fact. I think we're good. The app actually does nothing beside startup. and then it shut down right away. So it is the expected behavior. So all is good and thanks for the fix

**Comment by dhaval24** [comment] 2018-07-23 23:14
@ken-hum could you test in your real application if the fix works for you there and let us know?

**Closed** 2018-07-23 23:15 UTC
Labels: SpringBoot, question

**Comment by ken-hum** [comment] 2018-07-24 16:57
Sure. I tried the snapshot in my app and it works OOB(out of box). At least for vital signs... Once I start testing it further such as telemetry and all and if i find any other issues, I will open another issue ticket. Thanks
