### ISSUE TITLE
Document how to successfully send data for apps which terminate early (flush/wait usage)

### ISSUE THREAD

**Issue by MatthewDavidCampbell** [Microsoft/ApplicationInsights-Java#529] opened 2018-01-15 15:18 UTC
Using Java 9 and the 1.0.10 line of Application Insights....

Must be missing a fundamental concept with the configuration of the telemetry client.  With the following Test snippet:

     InternalLogger.INSTANCE.initialize("CONSOLE", new HashMap<String, String>());
     String instrumentationKey = "<some key>";

     TelemetryConfiguration configuration = new TelemetryConfiguration();
     configuration.setInstrumentationKey(instrumentationKey);

     Map<String, String> settings = new HashMap<String,String>();
     settings.put("EndpointAddress","https://dc.services.visualstudio.com/v2/track");
     settings.put("DeveloperMode", "true");
     settings.put("MaxTelemetryBufferCapacity", "500");
     settings.put("FlushIntervalInSeconds", "1");
     settings.put("MaxTransmissionStorageFilesCapacityInMB","1");

     configuration.setChannel(new InProcessTelemetryChannel(settings));

     TelemetryClient telemetry = new TelemetryClient(configuration);

     telemetry.trackEvent("Doing some event");

If the channel isn't set then nothing is sent which is only shown by piping the internal logger to the console.  Not able to find any public information about how telemetry channels ought to be rigged to send to my Azure Application Insights instance?  Assuming if one is working with J2EE this stuff is automatically setup with interceptors.  But what about from a plain-old Java process?

**Comment by dhaval24** [comment] 2018-01-15 19:12
@MatthewDavidCampbell I used your exact same code and tried to replicate the issue and at the very first I got a socket timed out exception. Now I did only a small modification to the above code - added a Thread.sleep(10000) {sleep of 10000 milli-seconds} and the event flowed out to the AI portal. 

The reason is as follows - if your code terminates immediately after calling the track() method, it prematurely terminates the thread spawned to send the telemetry and therefore items don't end up to the backend. I recommend adding some wait before the code terminates. Hope this helps and yes there should be better documentation.

PS: Please not the that our SDK currently doesn't fully support Java 9, especially Java Agent for dependency tracking. If you have ideas on how to fix the issue there it would be great. 

#460

**Comment by MatthewDavidCampbell** [comment] 2018-01-15 20:50
LOL.  Should have read the exception in context: "connection pool shut down".  Thanks for the info!

**Comment by dhaval24** [comment] 2018-01-15 21:08
No worries. I will keep this issue open for now as a pending doc change subject to current status on official microsoft docs for application insights.

**Comment by grlima** [comment] 2018-02-14 17:12
Dupe of #484

**Closed by grlima** 2018-02-14 17:12 UTC
Labels: Documentation Changes
