### ISSUE TITLE
Unitless Heap Memory Used

### ISSUE THREAD

**Issue by HeikoH** [Microsoft/ApplicationInsights-Java#463] opened 2017-11-10 17:46 UTC
`Heap Memory Used` metric should show `MiB`, same as `Private Bytes`

![image](https://user-images.githubusercontent.com/2171931/32671317-c1e5c4fc-c5fb-11e7-9894-6b52247ad842.png)

**Comment by HeikoH** [comment] 2017-11-10 17:47
(this is using Application Insights for Java)

**Comment by dhaval24** [comment] 2017-11-15 06:02
@HeikoH thanks for opening the issue. Can you correct me if I am wrong. Mib is the unit missing in the Heap Memory used chart, is this what you meant?

**Comment by HeikoH** [comment] 2017-11-15 06:25
yes

**Comment by dhaval24** [comment] 2017-11-15 06:27
@HeikoH sounds good. I will check back to see if this is UI inconsistency or SDK related issue. Is there any other issue that you are facing too for the SDK ?

**Comment by dhaval24** [comment] 2017-11-19 03:28
@HeikoH I confirmed with the team and found that this is by design. Our UI does not have any special case for Memory Metrics aside from the Memory Performance Counters (e.g. Process Private Bytes). The performance counter which are marked as customPerformance counter does not have any Units associated with it. The list includes :  DeadLockDetectorPerformanceCounter, GCPerformanceCounter, JvmHeapMemoryUsedPerformanceCounter, JmxMetricPerformanceCounter, WindowsPerformanceCounterAsMetric.  Therefore I am closing this issues for now, please feel free to reopen with more questions if you have.

**Closed by dhaval24** 2017-11-19 03:28 UTC
Labels: bug, question
