### ISSUE TITLE
Expose configuration of MaxTransmissionStorageFilesCapacityInMB

### ISSUE THREAD

**Issue by stevendick-swissre** [microsoft/ApplicationInsights-Java#1691] opened 2021-05-18 09:41 UTC
Not sure if this is a feature request or possibly related to a bug.

### Context

Some of our development teams are reporting the following error from the App Insights agent:

`2021-03-24 09:06:06.270Z ERROR c.m.a.i.c.c.TransmissionFileSystemOutput - Persistent storage max capacity has been reached; currently at 10504164 bytes. Telemetry will be lost, please consider increasing the value of MaxTransmissionStorageFilesCapacityInMB property in the configuration file.`

So on the surface this looks like an easy fix - just increase the `MaxTransmissionStorageFilesCapacityInMB` setting, but this isn't exposed as configurable with the agent flavour of App Insights for Java.

### Desired outcome

Now I'm not sure if it would make sense to expose `MaxTransmissionStorageFilesCapacityInMB` or if this reported error could indicate something else is going wrong.

### Additional context
This error has been reported when we restart Kafka-based services that are replaying a large amount of data to 'catch up' to the last known state. Could we be generating a huge number of Kafka metrics captured by the App Insights agent that is overflowing the max file buffer size before the next transmission to Azure?

**Comment by trask** [comment] 2021-05-18 19:06
hey @stevendick-swissre!

> or if this reported error could indicate something else is going wrong

yes, typically the issue is that the network connection has been failing for a while (trying to send telemetry to the ingestion service / portal), which is what causes writing to disk in the first place.

we improved that message, and the messages around network connection failures, in 3.0.3, can you try with that release (or later), and if you are still seeing issues, can you attach the full applicationinsights.log?

**Comment by stevendick-swissre** [comment] 2021-05-19 08:45
We're in the process of upgrading to v3.0.3 so we'll come back again if we still have questions around the buffering to file.

**Comment by trask** [comment] 2021-06-17 03:50
Closing, but please feel free to post further comment or a new issue.

**Closed by trask** 2021-06-17 03:50 UTC
