### ISSUE TITLE
Seeing 'TransmissionNetworkOutput - Failed to send' exception in app using App Insights Java Agent (3.0 Preview 5)

### ISSUE THREAD

**Issue by andrejpk** [microsoft/ApplicationInsights-Java#1301] opened 2020-08-20 13:46 UTC
### Expected behavior
I expect my app to run with the App Insights Java Agent (3.0 preview 5) integrated without any errors or warnings if my application and environment are configured properly.

### Actual behavior
Seeing this error repeatedly in my container console logs:
```logs
2020-08-17 18:17:46.111Z ERROR c.m.a.i.c.c.TransmissionNetworkOutput - Failed to send
java.net.SocketTimeoutException: Read timed out
        at java.base/java.net.SocketInputStream.socketRead0(Native Method)
        at java.base/java.net.SocketInputStream.socketRead(Unknown Source)
        at java.base/java.net.SocketInputStream.read(Unknown Source)
        at java.base/java.net.SocketInputStream.read(Unknown Source)
        at java.base/sun.security.ssl.SSLSocketInputRecord.read(Unknown Source)
        at java.base/sun.security.ssl.SSLSocketInputRecord.readHeader(Unknown Source)
        at java.base/sun.security.ssl.SSLSocketInputRecord.bytesInCompletePacket(Unknown Source)
        at java.base/sun.security.ssl.SSLSocketImpl.readApplicationRecord(Unknown Source)
        at java.base/sun.security.ssl.SSLSocketImpl$AppInputStream.read(Unknown Source)
        at org.apache.http.impl.io.SessionInputBufferImpl.streamRead(SessionInputBufferImpl.java:137)
        at org.apache.http.impl.io.SessionInputBufferImpl.fillBuffer(SessionInputBufferImpl.java:153)
        at org.apache.http.impl.io.SessionInputBufferImpl.readLine(SessionInputBufferImpl.java:282)
        at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:138)
        at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:56)
        at org.apache.http.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:259)
        at org.apache.http.impl.DefaultBHttpClientConnection.receiveResponseHeader(DefaultBHttpClientConnection.java:163)
        at org.apache.http.impl.conn.CPoolProxy.receiveResponseHeader(CPoolProxy.java:165)
        at org.apache.http.protocol.HttpRequestExecutor.doReceiveResponse(HttpRequestExecutor.java:273)
        at org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:125)
        at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:272)
        at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:185)
        at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
        at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:111)
        at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:108)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:56)
        at com.microsoft.applicationinsights.internal.channel.common.ApacheSender43.sendPostRequest(ApacheSender43.java:75)
        at com.microsoft.applicationinsights.internal.channel.common.TransmissionNetworkOutput.sendSync(TransmissionNetworkOutput.java:159)
        at com.microsoft.applicationinsights.internal.channel.common.ActiveTransmissionNetworkOutput$1.run(ActiveTransmissionNetworkOutput.java:80)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.base/java.lang.Thread.run(Unknown Source)
```

These seem to happen at regular round 10 second time points (a sampling from my logs)
```logs
2020-08-17 23:22:40.371Z ERROR c.m.a.i.c.c.TransmissionNetworkOutput - Failed to send
2020-08-17 23:22:50.366Z ERROR c.m.a.i.c.c.TransmissionNetworkOutput - Failed to send
2020-08-17 23:23:00.311Z ERROR c.m.a.i.c.c.TransmissionNetworkOutput - Failed to send
2020-08-17 23:23:10.371Z ERROR c.m.a.i.c.c.TransmissionNetworkOutput - Failed to send
2020-08-17 23:23:30.353Z ERROR c.m.a.i.c.c.TransmissionNetworkOutput - Failed to send
2020-08-17 23:23:40.329Z ERROR c.m.a.i.c.c.TransmissionNetworkOutput - Failed to send
2020-08-17 23:24:00.356Z ERROR c.m.a.i.c.c.TransmissionNetworkOutput - Failed to send
2020-08-17 23:24:10.366Z ERROR c.m.a.i.c.c.TransmissionNetworkOutput - Failed to send
2020-08-17 23:26:10.371Z ERROR c.m.a.i.c.c.TransmissionNetworkOutput - Failed to send
2020-08-17 23:26:20.351Z ERROR c.m.a.i.c.c.TransmissionNetworkOutput - Failed to send
2020-08-17 23:26:30.377Z ERROR c.m.a.i.c.c.TransmissionNetworkOutput - Failed to send
2020-08-17 23:26:40.367Z ERROR c.m.a.i.c.c.TransmissionNetworkOutput - Failed to send
2020-08-17 23:26:50.373Z ERROR c.m.a.i.c.c.TransmissionNetworkOutput - Failed to send
2020-08-17 23:27:40.388Z ERROR c.m.a.i.c.c.TransmissionNetworkOutput - Failed to send
2020-08-17 23:27:50.400Z ERROR c.m.a.i.c.c.TransmissionNetworkOutput - Failed to send
2020-08-17 23:28:00.310Z ERROR c.m.a.i.c.c.TransmissionNetworkOutput - Failed to send
2020-08-17 23:29:00.351Z ERROR c.m.a.i.c.c.TransmissionNetworkOutput - Failed to send
2020-08-17 23:29:10.415Z ERROR c.m.a.i.c.c.TransmissionNetworkOutput - Failed to send
2020-08-17 23:29:20.363Z ERROR c.m.a.i.c.c.TransmissionNetworkOutput - Failed to send
2020-08-17 23:29:30.367Z ERROR c.m.a.i.c.c.TransmissionNetworkOutput - Failed to send
2020-08-17 23:30:50.376Z ERROR c.m.a.i.c.c.TransmissionNetworkOutput - Failed to send
2020-08-17 23:31:10.352Z ERROR c.m.a.i.c.c.TransmissionNetworkOutput - Failed to send
2020-08-17 23:31:20.349Z ERROR c.m.a.i.c.c.TransmissionNetworkOutput - Failed to send
2020-08-17 23:32:10.371Z ERROR c.m.a.i.c.c.TransmissionNetworkOutput - Failed to send
2020-08-17 23:32:30.345Z ERROR c.m.a.i.c.c.TransmissionNetworkOutput - Failed to send
2020-08-17 23:33:10.351Z ERROR c.m.a.i.c.c.TransmissionNetworkOutput - Failed to send
2020-08-17 23:33:40.371Z ERROR c.m.a.i.c.c.TransmissionNetworkOutput - Failed to send
2020-08-17 23:34:10.345Z ERROR c.m.a.i.c.c.TransmissionNetworkOutput - Failed to send
2020-08-17 23:34:20.388Z ERROR c.m.a.i.c.c.TransmissionNetworkOutput - Failed to send
2020-08-17 23:34:30.363Z ERROR c.m.a.i.c.c.TransmissionNetworkOutput - Failed to send
2020-08-17 23:35:00.355Z ERROR c.m.a.i.c.c.TransmissionNetworkOutput - Failed to send
2020-08-17 23:35:10.338Z ERROR c.m.a.i.c.c.TransmissionNetworkOutput - Failed to send
2020-08-17 23:35:30.360Z ERROR c.m.a.i.c.c.TransmissionNetworkOutput - Failed to send
2020-08-17 23:36:00.377Z ERROR c.m.a.i.c.c.TransmissionNetworkOutput - Failed to send
2020-08-17 23:36:50.333Z ERROR c.m.a.i.c.c.TransmissionNetworkOutput - Failed to send
2020-08-17 23:37:10.337Z ERROR c.m.a.i.c.c.TransmissionNetworkOutput - Failed to send
2020-08-17 23:37:30.379Z ERROR c.m.a.i.c.c.TransmissionNetworkOutput - Failed to send
2020-08-17 23:37:40.363Z ERROR c.m.a.i.c.c.TransmissionNetworkOutput - Failed to send
2020-08-17 23:38:30.375Z ERROR c.m.a.i.c.c.TransmissionNetworkOutput - Failed to send
2020-08-17 23:38:40.365Z ERROR c.m.a.i.c.c.TransmissionNetworkOutput - Failed to send
2020-08-17 23:39:10.355Z ERROR c.m.a.i.c.c.TransmissionNetworkOutput - Failed to send
2020-08-17 23:39:30.324Z ERROR c.m.a.i.c.c.TransmissionNetworkOutput - Failed to send
2020-08-17 23:41:00.347Z ERROR c.m.a.i.c.c.TransmissionNetworkOutput - Failed to send
2020-08-17 23:41:10.351Z ERROR c.m.a.i.c.c.TransmissionNetworkOutput - Failed to send
2020-08-17 23:41:50.327Z ERROR c.m.a.i.c.c.TransmissionNetworkOutput - Failed to send
2020-08-17 23:42:00.327Z ERROR c.m.a.i.c.c.TransmissionNetworkOutput - Failed to send
2020-08-17 23:42:10.348Z ERROR c.m.a.i.c.c.TransmissionNetworkOutput - Failed to send
2020-08-17 23:42:20.375Z ERROR c.m.a.i.c.c.TransmissionNetworkOutput - Failed to send
2020-08-17 23:42:30.363Z ERROR c.m.a.i.c.c.TransmissionNetworkOutput - Failed to send
2020-08-17 23:43:00.369Z ERROR c.m.a.i.c.c.TransmissionNetworkOutput - Failed to send
2020-08-17 23:43:10.337Z ERROR c.m.a.i.c.c.TransmissionNetworkOutput - Failed to send
2020-08-17 23:43:20.327Z ERROR c.m.a.i.c.c.TransmissionNetworkOutput - Failed to send
2020-08-17 23:44:30.366Z ERROR c.m.a.i.c.c.TransmissionNetworkOutput - Failed to send
2020-08-17 23:44:40.363Z ERROR c.m.a.i.c.c.TransmissionNetworkOutput - Failed to send
2020-08-17 23:48:20.365Z ERROR c.m.a.i.c.c.TransmissionNetworkOutput - Failed to send
2020-08-17 23:48:30.364Z ERROR c.m.a.i.c.c.TransmissionNetworkOutput - Failed to send
2020-08-17 23:53:50.374Z ERROR c.m.a.i.c.c.TransmissionNetworkOutput - Failed to send
2020-08-17 23:59:50.336Z ERROR c.m.a.i.c.c.TransmissionNetworkOutput - Failed to send
2020-08-19 20:14:10.337Z ERROR c.m.a.i.c.c.TransmissionNetworkOutput - Failed to send
```

Outbound network access is allowed and it appears that telemetry is still flowing since I'm still getting app logs. 

### To Reproduce

- Container built using ```FROM  openjdk:11-jre```
- The App Insights Java Agent 3.0 Preview 5 is in the /app/lib folder of my container
- my app jar is in the /app folder
- Start command is: ```java -javaagent:/app/lib/applicationinsights-agent.jar -jar "/$file_name"``` (where $file_name is the name of my  app jar)
- Run the container and the above error appears in my logs

#### Sample Application
Not application-specific that I can tell.. I can create a sample app if this is needed.

### System information
Please provide the following information:
 - SDK Version:
 - OS type and version:
 - Application Server type and version (if applicable):
 - Using spring-boot?
 - Additional relevant libraries (with version, if applicable):

### Logs
I'll work on getting this but will take some extra steps to get this deployed

### Screenshots
n/a

**Comment by MS-jgol** [comment] 2020-09-11 19:11
@andrejpk Can you please make sure that the JVM is configured properly:
java -javaagent:path/to/applicationinsights-agent-3.0.0-PREVIEW.jar -jar <myapp.jar>

More info on this: https://docs.microsoft.com/en-us/azure/azure-monitor/app/java-standalone-arguments

**Comment by andrejpk** [comment] 2020-09-12 12:14
Hi @MS-jgol, yes, that's the command line we are using. The agent still seems to mostly work. The messages come when traffic on the service picks up.

**Comment by ToBeKedge** [comment] 2020-11-20 10:41
Hi,

We have same problem on our AppService (stack Tomcat-8.5 or stack java-8)!

On our side, we use two PREVIEW versions (3 and 7) and the problem is the same but we have also some other messages:

```
2020-11-19T18:44:41.974072286Z 2020-11-19 18:44:41.962Z ERROR c.m.a.i.c.c.TransmissionNetworkOutput - Failed to send, socket exception
2020-11-19T18:44:41.976995820Z java.net.SocketException: Connection reset
2020-11-19T18:44:41.977011520Z 	at java.net.SocketInputStream.read(SocketInputStream.java:210)
2020-11-19T18:44:41.977037420Z 	at java.net.SocketInputStream.read(SocketInputStream.java:141)
2020-11-19T18:44:41.977041420Z 	at sun.security.ssl.InputRecord.readFully(InputRecord.java:465)
2020-11-19T18:44:41.977045320Z 	at sun.security.ssl.InputRecord.read(InputRecord.java:503)
2020-11-19T18:44:41.977066221Z 	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:975)
2020-11-19T18:44:41.977069921Z 	at sun.security.ssl.SSLSocketImpl.readDataRecord(SSLSocketImpl.java:933)
2020-11-19T18:44:41.977073321Z 	at sun.security.ssl.AppInputStream.read(AppInputStream.java:105)
2020-11-19T18:44:41.977076721Z 	at org.apache.http.impl.io.SessionInputBufferImpl.streamRead(SessionInputBufferImpl.java:137)
2020-11-19T18:44:41.977080321Z 	at org.apache.http.impl.io.SessionInputBufferImpl.fillBuffer(SessionInputBufferImpl.java:153)
2020-11-19T18:44:41.977083721Z 	at org.apache.http.impl.io.SessionInputBufferImpl.readLine(SessionInputBufferImpl.java:282)
2020-11-19T18:44:41.977087221Z 	at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:138)
2020-11-19T18:44:41.977090821Z 	at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:56)
2020-11-19T18:44:41.977117821Z 	at org.apache.http.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:259)
2020-11-19T18:44:41.977123221Z 	at org.apache.http.impl.DefaultBHttpClientConnection.receiveResponseHeader(DefaultBHttpClientConnection.java:163)
2020-11-19T18:44:41.977126321Z 	at org.apache.http.impl.conn.CPoolProxy.receiveResponseHeader(CPoolProxy.java:165)
2020-11-19T18:44:41.977129521Z 	at org.apache.http.protocol.HttpRequestExecutor.doReceiveResponse(HttpRequestExecutor.java:273)
2020-11-19T18:44:41.977132521Z 	at org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:125)
2020-11-19T18:44:41.977135621Z 	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:272)
2020-11-19T18:44:41.977138721Z 	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:185)
2020-11-19T18:44:41.977141921Z 	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
2020-11-19T18:44:41.977144921Z 	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:111)
2020-11-19T18:44:41.977148021Z 	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
2020-11-19T18:44:41.977152922Z 	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
2020-11-19T18:44:41.977156322Z 	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:108)
2020-11-19T18:44:41.977159422Z 	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:56)
2020-11-19T18:44:41.977162522Z 	at com.microsoft.applicationinsights.internal.channel.common.ApacheSender43.sendPostRequest(ApacheSender43.java:75)
2020-11-19T18:44:41.977165822Z 	at com.microsoft.applicationinsights.internal.channel.common.TransmissionNetworkOutput.sendSync(TransmissionNetworkOutput.java:159)
2020-11-19T18:44:41.977169122Z 	at com.microsoft.applicationinsights.internal.channel.common.ActiveTransmissionNetworkOutput$1.run(ActiveTransmissionNetworkOutput.java:80)
2020-11-19T18:44:41.977172222Z 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
2020-11-19T18:44:41.977175322Z 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
2020-11-19T18:44:41.977194122Z 	at java.lang.Thread.run(Thread.java:748)
```
or 
```
2020-11-18T17:35:58.352054587Z 2020-11-18 17:35:58.341Z ERROR c.m.a.i.c.c.TransmissionNetworkOutput - Failed to send, wrong host address or cannot reach address due to network issues
2020-11-18T17:35:58.352122487Z java.net.UnknownHostException: dc.services.visualstudio.com
2020-11-18T17:35:58.352402789Z 	at java.net.InetAddress.getAllByName0(InetAddress.java:1281)
2020-11-18T17:35:58.352412089Z 	at java.net.InetAddress.getAllByName(InetAddress.java:1193)
2020-11-18T17:35:58.352416189Z 	at java.net.InetAddress.getAllByName(InetAddress.java:1127)
2020-11-18T17:35:58.352420189Z 	at org.apache.http.impl.conn.SystemDefaultDnsResolver.resolve(SystemDefaultDnsResolver.java:45)
2020-11-18T17:35:58.352424289Z 	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:112)
2020-11-18T17:35:58.352428189Z 	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:359)
2020-11-18T17:35:58.352440290Z 	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:381)
2020-11-18T17:35:58.352453190Z 	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:237)
2020-11-18T17:35:58.352457790Z 	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:185)
2020-11-18T17:35:58.352461590Z 	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
2020-11-18T17:35:58.352465190Z 	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:111)
2020-11-18T17:35:58.352469190Z 	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
2020-11-18T17:35:58.352472990Z 	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
2020-11-18T17:35:58.352476990Z 	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:108)
2020-11-18T17:35:58.352480890Z 	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:56)
2020-11-18T17:35:58.352484690Z 	at com.microsoft.applicationinsights.internal.channel.common.ApacheSender43.sendPostRequest(ApacheSender43.java:75)
2020-11-18T17:35:58.352488590Z 	at com.microsoft.applicationinsights.internal.channel.common.TransmissionNetworkOutput.sendSync(TransmissionNetworkOutput.java:159)
2020-11-18T17:35:58.352492390Z 	at com.microsoft.applicationinsights.internal.channel.common.ActiveTransmissionNetworkOutput$1.run(ActiveTransmissionNetworkOutput.java:80)
2020-11-18T17:35:58.352496190Z 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
2020-11-18T17:35:58.352501490Z 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
2020-11-18T17:35:58.352505390Z 	at java.lang.Thread.run(Thread.java:748)
```
For the last one, the stacktrace is repeated always if the AppService instance is not restarted (we work with 2 instances).

Have you any idea where the problem comes from? Or any options to investigate this issue?

Best regards,

Cyril

**Comment by vtrusevich-incomm** [comment] 2021-01-28 10:35
Having the same issue. Also noticed that it works on one slot and fails on others within the same app service.

Are there any updates on the fix?

**Comment by kryalama** [comment] 2021-01-28 17:35
@vtrusevich-incomm could you please confirm what version of Application Insights agent are you currently using? If you are facing `java.net.UnknownHostException: dc.services.visualstudio.com`  could you please try logging into the machine and try `nslookup HOSTNAME`.  Else I am suspecting there might be some firewall blocking the requests to end point.

**Comment by Amarender-KR** [comment] 2021-01-29 18:41
Hi Team,

we are experiencing the similar issue and we are using the latest jar (applicationinsights-agent-3.0.2.jar).. Can someone please help in resolving the issue. 

It's an intermittent behavior.

Log Information
----------------
2021-01-28 21:36:34.626-05 ERROR c.m.a.i.c.c.TransmissionNetworkOutput - Failed to send
java.net.SocketTimeoutException: Read timed out
at java.base/java.net.SocketInputStream.socketRead0(Native Method)
at java.base/java.net.SocketInputStream.socketRead(SocketInputStream.java:115)
at java.base/java.net.SocketInputStream.read(SocketInputStream.java:168)
at java.base/java.net.SocketInputStream.read(SocketInputStream.java:140)
at java.base/sun.security.ssl.SSLSocketInputRecord.read(SSLSocketInputRecord.java:448)
at java.base/sun.security.ssl.SSLSocketInputRecord.bytesInCompletePacket(SSLSocketInputRecord.java:68)
at java.base/sun.security.ssl.SSLSocketImpl.readApplicationRecord(SSLSocketImpl.java:1104)
at java.base/sun.security.ssl.SSLSocketImpl$AppInputStream.read(SSLSocketImpl.java:823)
at org.apache.http.impl.io.SessionInputBufferImpl.streamRead(SessionInputBufferImpl.java:137)
at org.apache.http.impl.io.SessionInputBufferImpl.fillBuffer(SessionInputBufferImpl.java:153)
at org.apache.http.impl.io.SessionInputBufferImpl.readLine(SessionInputBufferImpl.java:282)
at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:138)
at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:56)
at org.apache.http.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:259)
at org.apache.http.impl.DefaultBHttpClientConnection.receiveResponseHeader(DefaultBHttpClientConnection.java:163)
at org.apache.http.impl.conn.CPoolProxy.receiveResponseHeader(CPoolProxy.java:165)
at org.apache.http.protocol.HttpRequestExecutor.doReceiveResponse(HttpRequestExecutor.java:273)
at org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:125)
at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:272)
at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:185)
at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:111)
at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:108)
at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:56)
at com.microsoft.applicationinsights.internal.channel.common.ApacheSender43.sendPostRequest(ApacheSender43.java:79)
at com.microsoft.applicationinsights.internal.channel.common.TransmissionNetworkOutput.sendSync(TransmissionNetworkOutput.java:162)
at com.microsoft.applicationinsights.internal.channel.common.ActiveTransmissionNetworkOutput$1.run(ActiveTransmissionNetworkOutput.java:80)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:834)

**Comment by trask** [comment] 2021-01-29 19:22
hi @Amarender-KR, if this is only sporadic, telemetry will be stored locally and re-sent later once the connection is stable again

**Comment by Dhanasimmaraja-Subramani** [comment] 2021-03-09 09:49
@trask  
similar socket issue and not sure about the root cause.  
2021-02-04 10:37:18.766-06 INFO  c.m.applicationinsights.agent - ApplicationInsights Java Agent 3.0.1 started successfully
2021-02-05 01:06:54.443-06 ERROR c.m.a.i.c.c.TransmissionNetworkOutput - Failed to send, socket exception
java.net.SocketException: Connection reset
	at java.net.SocketInputStream.read(SocketInputStream.java:210)
	at java.net.SocketInputStream.read(SocketInputStream.java:141)
	at sun.security.ssl.InputRecord.readFully(InputRecord.java:465)
	at sun.security.ssl.InputRecord.read(InputRecord.java:503)
please say the local telemetry path and any way  to identify why its happening.

**Comment by trask** [comment] 2021-03-11 06:39
hi all!

if you are seeing this issue, and if you are able, can you try with [3.0.3-BETA](https://github.com/microsoft/ApplicationInsights-Java/releases/tag/3.0.3-BETA) to see if things improve?

we have increased the SSL handshake timeout in 3.0.3-BETA, in hopes of reducing the occurrence of this.

also, the same comment as above still applies, that if you are seeing this sporadically, the telemetry will be stored locally (under java.io.tmpdir) and re-sent later once the connection is stable again

**Comment by Dhanasimmaraja-Subramani** [comment] 2021-03-11 09:23
Thanks @trask will try and let you know.

**Comment by trask** [comment] 2021-04-05 20:18
3.0.3 is released: https://github.com/microsoft/ApplicationInsights-Java/releases/tag/3.0.3

**Closed by trask** 2021-04-05 20:18 UTC
Labels: Team-Triaged
