### ISSUE TITLE
HTTPClient Dependency Telemetry not working when using a Scheduled Bean

### ISSUE THREAD

**Issue by dslack** [Microsoft/ApplicationInsights-Java#831] opened 2019-03-06 07:27 UTC
### Expected behavior
Whenever we make an RestTemplate using HTTPClient call, we expect to see the dependency telemetry within Application Insights.

### Actual behavior
No Telemetry is recorded.  

### To Reproduce
Using a SampleBean class, with the Scheduled annotation: 
@Scheduled(initialDelay=5000, fixedDelay=100000)
public void init() {...}

Within the method, make a simple RestTemplate call to a second WebService (a separate Spring Boot application, with Application Insights enabled).  On the scheduled time, second WebService sees the request, reports its own Telemetry, but, a Dependency telemetry is not recorded from the first WebService.

#### Sample Application
I included a run.cmd file to auto build/run the two webservices (attaching the javaagent).  If you watch the log output, you'll see that the Demo application outputs the response from the Dummy application, however, no Telemetry is generated.  If you navigate to 'http://localhost:9090/test' - you'll see the dependency telemetry generated as expected.

### System information
Please provide the following information:
 - SDK Version: 2.3.0
 - OS type and version: Windows
 - Application Server type and version (if applicable):
 - Using spring-boot? Yes
 - Additional relevant libraries (with version, if applicable):

### Observations
What I'm seeing, after jumping into the app insights java SDK is that when an HTTP request is sent via a Scheduled Bean, it never actually gets to the 'httpMethodFinished' method that the agent is supposed to execute after retrieving all the appropriate telemetry data.  When I execute a controller from the browser (which also makes a RestTemplate call), I do see that the 'httpMethodFinished' method is executed (via setting a breakpoint within that specific code base). 

[applicationInsightsDependencyScheduled.zip](https://github.com/Microsoft/ApplicationInsights-Java/files/2934958/applicationInsightsDependencyScheduled.zip)

**Comment by dhaval24** [comment] 2019-03-06 16:15
@dslack thanks for creating this issue and uploading the sample app. I am going to take a look at this one and get back with my comments.

**Comment by dslack** [comment] 2019-03-12 07:29
@dhaval24 

Was just wondering if there was any traction on this?  We've written up some workarounds, but, would ideally like to replace with a MS solution.

**Comment by dhaval24** [comment] 2019-03-12 15:18
@dslack as discussed offline yes I was able to reproduce the issue locally. Thank you for sharing the sample application. It looks like there might be a potential bug in the SDK. Besides that as mentioned, I also see some potential dangerous configuration issues in your sample code. 

** I would ask you to please refrain from adding ApplicationInsights.xml file when you are using ApplicationInsights SpringBoot starter in a springboot application**. 

The starter is designed to replace xml and provide configuration of SDK in Spring Boot friendly way. Besides that, adding the xml can also cause side effects in configuration that can be at times very hard to debug. 

For the fix, I will keep you posted.

**Comment by dhaval24** [comment] 2019-03-27 14:22
This should be fixed with #860 . @dslack if you would like to try this, you can build the latest master and see if the problem is resolved. We will be releasing beta version of the new sdk with this capability by the end of this month.

**Comment by dhaval24** [comment] 2019-03-31 18:26
@dslack this should be fixed now.  The latest release: https://github.com/Microsoft/ApplicationInsights-Java/releases/latest has this fix. Please use:
1. Application Insights Springboot starter 1.2.0-BETA
2. Application Insights Java Agent 2.4.0-BETA
Please follow this article on additional changes which needs to be done in the code base for context to propagate properly. 
https://github.com/Microsoft/ApplicationInsights-Java/wiki/Distributed-Tracing-in-Asynchronous-Java-Applications#context-propagation-in-scheduled-events

I will close this issue for now.  Please reopen if the issue persists.

**Closed by dhaval24** 2019-03-31 18:26 UTC
Labels: SpringBoot, bug
