### ISSUE TITLE
Agent exception running in Azure function v4

### ISSUE THREAD

**Issue by ibrahim-abdellaoui** [microsoft/ApplicationInsights-Java#2863] opened 2023-01-19 15:16 UTC
### Expected behavior
Logs to always be sent to Application insights, the issue now is that they don't get sent always.
this issue happened after upgrading to Azure function runtime v4 from v3 

### Actual behavior
sometimes the Logs don't appear in Application Insights, and instead, we see the following exception in the logs 
```
Exception in thread "BatchItemProcessor_WorkerThread-1" java.lang.NullPointerException
Exception in thread "BatchItemProcessor_WorkerThread-1" java.lang.NullPointerException
at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1690)
at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1690)
at com.azure.monitor.opentelemetry.exporter.implementation.configuration.ConnectionString.parse(ConnectionString.java:36)
at com.azure.monitor.opentelemetry.exporter.implementation.configuration.ConnectionString.parse(ConnectionString.java:36)
at com.azure.monitor.opentelemetry.exporter.implementation.pipeline.TelemetryPipeline.send(TelemetryPipeline.java:41)
at com.azure.monitor.opentelemetry.exporter.implementation.pipeline.TelemetryPipeline.send(TelemetryPipeline.java:41)
at com.azure.monitor.opentelemetry.exporter.implementation.pipeline.TelemetryItemExporter.internalSendByConnectionString(TelemetryItemExporter.java:126)
at com.azure.monitor.opentelemetry.exporter.implementation.pipeline.TelemetryItemExporter.internalSendByConnectionString(TelemetryItemExporter.java:126)
at com.azure.monitor.opentelemetry.exporter.implementation.pipeline.TelemetryItemExporter.send(TelemetryItemExporter.java:83)
at com.azure.monitor.opentelemetry.exporter.implementation.pipeline.TelemetryItemExporter.send(TelemetryItemExporter.java:83)
at com.microsoft.applicationinsights.agent.internal.telemetry.BatchItemProcessor$Worker.exportCurrentBatch(BatchItemProcessor.java:279)
at com.microsoft.applicationinsights.agent.internal.telemetry.BatchItemProcessor$Worker.exportCurrentBatch(BatchItemProcessor.java:279)
at com.microsoft.applicationinsights.agent.internal.telemetry.BatchItemProcessor$Worker.run(BatchItemProcessor.java:177)
at com.microsoft.applicationinsights.agent.internal.telemetry.BatchItemProcessor$Worker.run(BatchItemProcessor.java:177)
at java.base/java.lang.Thread.run(Thread.java:829)
at java.base/java.lang.Thread.run(Thread.java:829)
```
### To Reproduce
```java
var TelemetryClient telemetryClient = new TelemetryClient();
telemetryClient.trackTrace(message, severityLevel, properties);
```
In the functions Settings
```
APPLICATIONINSIGHTS_CONNECTION_STRING="InstrumentationKey=xxxxxxxxxxxx;IngestionEndpoint=https://westeurope-5.in.applicationinsights.azure.com/;LiveEndpoint=https://westeurope.livediagnostics.monitor.azure.com/"
```
#### Sample Application
If applicable, provide a sample application which reproduces the issue.

### System information
Please provide the following information:
 - SDK Version: using azure functions library 3.0.0 and azure functions maven plugin 1.22.0, Azure function runtime v4
 - OS type and version: Windows
 - Application Server type and version (if applicable):
 - Using spring-boot? no
 - Additional relevant libraries (with version, if applicable): using Azure function runtime v4 

### Logs
[Turn on SDK logs](https://docs.microsoft.com/en-us/azure/application-insights/app-insights-java-troubleshoot#debug-data-from-the-sdk) and attach/paste them to the issue. If using an application server, also attach any relevant server logs.

_Be sure to remove any private information from the logs before posting!_

**Comment by trask** [comment] 2023-01-19 21:54
hi @ibrahim-abdellaoui! are you using azure functions consumption or dedicated plan? linux or windows?

**Comment by trask** [comment] 2023-01-20 03:43
@ibrahim-abdellaoui I was able to reproduce this. It looks like a bug that was fixed in Application Insights Java v3.4.4 but hasn't been rolled out to Azure Functions quite yet. I believe it will be available in Azure Functions in the next couple of weeks, I'll double check and get back to you.

**Comment by ibrahim-abdellaoui** [comment] 2023-01-20 08:04
@trask I'm using azure functions consumption plan on windows. I noticed something interesting today after I updated the extention bundle in `host.json` file from `[2.*, 3.0.0)` to `[3.3.0, 4.0.0)` the issue seems to be resolved. I saw in the logs that before it was using extention version 2.xx and now it's using version 3.17

**Comment by trask** [comment] 2023-01-20 17:50
@ibrahim-abdellaoui thanks, glad it's working for you now!

Azure Functions 4.15.1 is currently rolling out which contains Application Insights Java Integration Preview 2, which has many improvements over the existing Preview, including way better cold start performance.

I'll post back here once it's rolled out and the [onboarding doc](https://learn.microsoft.com/en-us/azure/azure-monitor/app/monitor-functions#distributed-tracing-for-java-applications-public-preview) is updated with new instructions for Preview 2.

**Comment by ibrahim-abdellaoui** [comment] 2023-01-21 10:25
@trask Thank you for taking the time on this issue

**Comment by trask** [comment] 2023-02-09 16:51
Public Preview 2 is live for Azure Functions Application Insights Java agent integration:

https://learn.microsoft.com/en-us/azure/azure-monitor/app/monitor-functions#distributed-tracing-for-java-applications-public-preview

**Closed** 2023-02-24 19:11 UTC
Labels: Needs: Author Feedback
