### ISSUE TITLE
Getting exception InstrumentationKeyResolver: failed to resolve instrumentation key

### ISSUE THREAD

**Issue by rosenbom** [microsoft/ApplicationInsights-Java#1296] opened 2020-07-30 18:17 UTC
Hello, 
I've installed and configured ApplicationInsights Java agent 3.0.0 preview 5. Few times a day I'm noticing the following exception thrown:
2020-07-30 11:25:14.487-04 ERROR c.m.a.w.i.c.InstrumentationKeyResolver - InstrumentationKeyResolver: failed to resolve instrumentation key: <**my instrumentation key**>
com.microsoft.applicationinsights.web.internal.correlation.ApplicationIdResolutionException: java.util.concurrent.ExecutionException: java.net.ConnectException
	at com.microsoft.applicationinsights.web.internal.correlation.CdsProfileFetcher.fetchApplicationId(CdsProfileFetcher.java:103)
	at com.microsoft.applicationinsights.web.internal.correlation.InstrumentationKeyResolver.resolveInstrumentationKey(InstrumentationKeyResolver.java:80)
	at com.microsoft.applicationinsights.agent.internal.AppIdSupplier.get(AppIdSupplier.java:15)
	at io.opentelemetry.auto.bootstrap.instrumentation.aiappid.AiAppId.getAppId(AiAppId.java:35)
	at com.microsoft.applicationinsights.agent.Exporter.exportRequest(Exporter.java:124)
	at com.microsoft.applicationinsights.agent.Exporter.export(Exporter.java:113)
	at com.microsoft.applicationinsights.agent.Exporter.export(Exporter.java:76)
	at io.opentelemetry.sdk.trace.export.SimpleSpanProcessor.onEnd(SimpleSpanProcessor.java:80)
	at io.opentelemetry.sdk.trace.MultiSpanProcessor.onEnd(MultiSpanProcessor.java:59)
	at io.opentelemetry.sdk.trace.RecordEventsReadableSpan.endInternal(RecordEventsReadableSpan.java:440)
	at io.opentelemetry.sdk.trace.RecordEventsReadableSpan.end(RecordEventsReadableSpan.java:422)
	at com.webmethods.rtl.event.RemoteDeliverer.onMessage(RemoteDeliverer.java:292)
	at com.webmethods.rtl.msg.ListenerProxy.onMessage(ListenerProxy.java:90)
	at com.webmethods.rtl.msg.jms.JMSDestination$Subscriber.onMessage(JMSDestination.java:267)
	at com.webmethods.portal.jms.db.impl.JMSDispatcherThread.run(JMSDispatcherThread.java:156)
Caused by: java.util.concurrent.ExecutionException: java.net.ConnectException
	at org.apache.http.concurrent.BasicFuture.getResult(BasicFuture.java:70)
	at org.apache.http.concurrent.BasicFuture.get(BasicFuture.java:80)
	at org.apache.http.impl.nio.client.FutureWrapper.get(FutureWrapper.java:70)
	at com.microsoft.applicationinsights.web.internal.correlation.CdsProfileFetcher.internalFetchAppProfile(CdsProfileFetcher.java:142)
	at com.microsoft.applicationinsights.web.internal.correlation.CdsProfileFetcher.fetchApplicationId(CdsProfileFetcher.java:101)
	... 14 common frames omitted
Caused by: java.net.ConnectException: null
	at org.apache.http.nio.pool.RouteSpecificPool.timeout(RouteSpecificPool.java:168)
	at org.apache.http.nio.pool.AbstractNIOConnPool.requestTimeout(AbstractNIOConnPool.java:584)
	at org.apache.http.nio.pool.AbstractNIOConnPool$InternalSessionRequestCallback.timeout(AbstractNIOConnPool.java:851)
	at org.apache.http.impl.nio.reactor.SessionRequestImpl.timeout(SessionRequestImpl.java:183)
	at org.apache.http.impl.nio.reactor.DefaultConnectingIOReactor.processTimeouts(DefaultConnectingIOReactor.java:210)
	at org.apache.http.impl.nio.reactor.DefaultConnectingIOReactor.processEvents(DefaultConnectingIOReactor.java:155)
	at org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor.execute(AbstractMultiworkerIOReactor.java:348)
	at org.apache.http.impl.nio.conn.PoolingNHttpClientConnectionManager.execute(PoolingNHttpClientConnectionManager.java:194)
	at org.apache.http.impl.nio.client.CloseableHttpAsyncClientBase$1.run(CloseableHttpAsyncClientBase.java:64)
	at java.lang.Thread.run(Thread.java:748)

Not sure how to troubleshoot it. 

Regards,
Dmitry

**Comment by multicaststorm** [comment] 2020-08-06 11:57
I am also getting this

**Comment by MS-jgol** [comment] 2020-09-10 19:37
@multicaststorm Thank you for the insight!
@rosenbom Have you tried looking into the jvm configuration? Can you please confirm that the issue is fixed?

**Comment by rosenbom** [comment] 2020-09-10 23:14
> @multicaststorm Thank you for the insight!
> @rosenbom Have you tried looking into the jvm configuration? Can you please confirm that the issue is fixed?
I haven't tried configuring JVM but I thought it should work via ApplicationInsights.json
My scenario is monitoring Integration Packages on a WebMethods Integration Server (product by Software AG).

**Comment by MS-jgol** [comment] 2020-09-11 17:15
@rosenbom 
Can you check that this doc to make sure that the path is set correctly for your JVM:
https://docs.microsoft.com/en-us/azure/azure-monitor/app/java-standalone-arguments

**Comment by trask** [comment] 2020-09-12 20:39
@multicaststorm

> The annoying thing is that I was already setting this in the `ApplicationInsights.json`...but it doesn't seem to use it:
> 
> ```
> {
>   "instrumentationSettings": {
>     "connectionString": "InstrumentationKey=00000-00000-00000-00000",
>     "preview": {
>       "httpProxy": {
>         "host": "...",
>         "port": ...
>       }
>     }
>   }
> }
> ```

I'm curious for any other details you can provide about this, I double-checked and it's working for me.

**Comment by multicaststorm** [comment] 2020-10-02 11:33
@trask 

I have rechecked the behaviour I was seeing.

When I _**don't**_ set the http proxy (either in `ApplicationInsights.json` or jvm system properties), then predicatably the agent fails to send any telemetry:

> org.apache.http.conn.HttpHostConnectException: Connect to dc.services.visualstudio.com:443 [dc.services.visualstudio.com/13.69.66.140] failed: Connection timed out: connect
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:159)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:359)
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:381)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:237)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:185)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:111)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:108)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:56)
	at com.microsoft.applicationinsights.internal.channel.common.ApacheSender43.sendPostRequest(ApacheSender43.java:75)
	at com.microsoft.applicationinsights.internal.channel.common.TransmissionNetworkOutput.sendSync(TransmissionNetworkOutput.java:159)
	at com.microsoft.applicationinsights.internal.channel.common.ActiveTransmissionNetworkOutput$1.run(ActiveTransmissionNetworkOutput.java:80)

Then when I set just the `ApplicationInsights.json` proxy settings:
```
{
  "instrumentationSettings": {
    "connectionString": "InstrumentationKey=00000-00000-00000-00000",
    "preview": {
      "httpProxy": {
        "host": "myproxy.com",
        "port": 8080
      }
    }
  }
}
```

My telemetry _**does**_ get through, however I start seeing these logs appearing (when my code is calling a http dependency):

> com.microsoft.applicationinsights.web.internal.correlation.ApplicationIdResolutionException: java.util.concurrent.ExecutionException: java.net.ConnectException
	at com.microsoft.applicationinsights.web.internal.correlation.CdsProfileFetcher.fetchApplicationId(CdsProfileFetcher.java:105)
	at com.microsoft.applicationinsights.web.internal.correlation.InstrumentationKeyResolver.resolveInstrumentationKey(InstrumentationKeyResolver.java:80)
	at com.microsoft.applicationinsights.agent.internal.AppIdSupplier.get(AppIdSupplier.java:15)
	at io.opentelemetry.javaagent.shaded.instrumentation.api.aiappid.AiAppId.getAppId(AiAppId.java:36)
	at io.opentelemetry.javaagent.shaded.instrumentation.api.aiappid.AiHttpTraceContext.injectImpl(AiHttpTraceContext.java:104)
	at io.opentelemetry.javaagent.shaded.instrumentation.api.aiappid.AiHttpTraceContext.inject(AiHttpTraceContext.java:88)
	at io.opentelemetry.javaagent.shaded.io.opentelemetry.context.propagation.DefaultContextPropagators$MultiTextMapPropagator.inject(DefaultContextPropagators.java:137)
	at io.opentelemetry.javaagent.shaded.instrumentation.api.tracer.HttpClientTracer.startScope(HttpClientTracer.java:87)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1499)
	at java.base/java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:527)
	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:334)
	at com.mycode.RestClientComponent.run(RestClientComponent.java:39)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.util.concurrent.ExecutionException: java.net.ConnectException
	at org.apache.http.concurrent.BasicFuture.getResult(BasicFuture.java:70)
	at org.apache.http.concurrent.BasicFuture.get(BasicFuture.java:80)
	at org.apache.http.impl.nio.client.FutureWrapper.get(FutureWrapper.java:70)
	at com.microsoft.applicationinsights.web.internal.correlation.CdsProfileFetcher.internalFetchAppProfile(CdsProfileFetcher.java:144)
	at com.microsoft.applicationinsights.web.internal.correlation.CdsProfileFetcher.fetchApplicationId(CdsProfileFetcher.java:103)
	... 13 common frames omitted
Caused by: java.net.ConnectException: null
	at org.apache.http.nio.pool.RouteSpecificPool.timeout(RouteSpecificPool.java:168)
	at org.apache.http.nio.pool.AbstractNIOConnPool.requestTimeout(AbstractNIOConnPool.java:584)
	at org.apache.http.nio.pool.AbstractNIOConnPool$InternalSessionRequestCallback.timeout(AbstractNIOConnPool.java:851)
	at org.apache.http.impl.nio.reactor.SessionRequestImpl.timeout(SessionRequestImpl.java:183)
	at org.apache.http.impl.nio.reactor.DefaultConnectingIOReactor.processTimeouts(DefaultConnectingIOReactor.java:210)
	at org.apache.http.impl.nio.reactor.DefaultConnectingIOReactor.processEvents(DefaultConnectingIOReactor.java:155)
	at org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor.execute(AbstractMultiworkerIOReactor.java:348)
	at org.apache.http.impl.nio.conn.PoolingNHttpClientConnectionManager.execute(PoolingNHttpClientConnectionManager.java:194)
	at org.apache.http.impl.nio.client.CloseableHttpAsyncClientBase$1.run(CloseableHttpAsyncClientBase.java:64)
	... 1 common frames omitted


To resolve the issue, I found that additionally setting jvm https settings resolved the issue:
```    
System.setProperty("https.proxyHost","myproxy.com");
System.setProperty("https.proxyPort","8080");
```

My assumption is that the `CdsProfileFetcher` need the http**s** proxy settings and is not using the http proxy setting from the `ApplicationInsights.json`

**Comment by Brunoga-MS** [comment] 2020-12-07 11:55
Hi there,
is this still an issue? Today, I had to configure a classic proxy inside the ApplicationInsights.json which did not work with the Log Analytics gateway (aka OMS Gateway).
My customer would like to not allow server to navigate the internet and prefer to use the Log Analytics Gateway which is already in place for the classic Linux monitoring agent.

Thx.

**Comment by Brunoga-MS** [comment] 2020-12-07 13:43
forgot to mention that we are using the 3.0.0.version as per download link (https://github.com/microsoft/ApplicationInsights-Java/releases/download/3.0.0/applicationinsights-agent-3.0.0.jar)

**Comment by trask** [comment] 2020-12-17 03:21
hi @Brunoga-MS, this should be resolved in 3.0.0, several config options changed from 3.0.0.PREVIEW.7 to 3.0.0 (GA), can you double check the configuration options: https://docs.microsoft.com/en-us/azure/azure-monitor/app/java-standalone-config#http-proxy and post your `applicationinsights.json` file if still having issue?

**Comment by raytapan** [comment] 2020-12-24 23:48
Hello,
I've installed and configured ApplicationInsights Java agent 3.0.0 for my java app running on azure app service. Few times a day I'm noticing the following exception thrown:

2020-12-24 15:32:30.977-08 ERROR c.m.a.i.perfcounter.JniPCConnector - Failed to fetch current process instance name, process counters for for the process level will not be activated.
2020-12-24 15:32:31.024-08 WARN  c.m.a.i.perfcounter.JniPCConnector - Performance coutner registration failed for Processor \ % Processor Time [_Total]
2020-12-24 15:32:31.024-08 ERROR c.m.a.i.p.ProcessBuiltInPerformanceCountersFactory - Failed to create WindowsPerformanceCounterAsPC: 'java.lang.Exception: Cannot translate instance name: Unknown current instance name'
2020-12-24 15:32:48.463-08 INFO  c.m.applicationinsights.agent - ApplicationInsights Java Agent started successfully
2020-12-24 15:33:17.090-08 ERROR c.m.a.w.i.c.InstrumentationKeyResolver - InstrumentationKeyResolver - failed to resolve instrumentation key: 70f8c11f-81cc-427f-ae26-ebf628f7c2dd
2020-12-24 15:33:17.184-08 ERROR c.m.a.w.i.c.InstrumentationKeyResolver - InstrumentationKeyResolver: failed to resolve instrumentation key: <my instrumentation jey>
java.nio.BufferUnderflowException: null
	at java.nio.HeapByteBuffer.get(HeapByteBuffer.java:154)
	at org.apache.http.nio.util.SimpleInputBuffer.read(SimpleInputBuffer.java:109)
	at org.apache.http.nio.entity.ContentInputStream.read(ContentInputStream.java:63)
	at sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:284)
	at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:326)
	at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:178)
	at java.io.InputStreamReader.read(InputStreamReader.java:184)
	at java.io.Reader.read(Reader.java:140)
	at org.apache.http.util.EntityUtils.toString(EntityUtils.java:225)
	at org.apache.http.util.EntityUtils.toString(EntityUtils.java:306)
	at com.microsoft.applicationinsights.web.internal.correlation.CdsProfileFetcher.internalFetchAppProfile(CdsProfileFetcher.java:165)
	at com.microsoft.applicationinsights.web.internal.correlation.CdsProfileFetcher.fetchApplicationId(CdsProfileFetcher.java:110)
	at com.microsoft.applicationinsights.web.internal.correlation.InstrumentationKeyResolver.resolveInstrumentationKey(InstrumentationKeyResolver.java:80)
	at com.microsoft.applicationinsights.agent.internal.AppIdSupplier.get(AppIdSupplier.java:36)
	at io.opentelemetry.javaagent.shaded.instrumentation.api.aiappid.AiAppId.getAppId(AiAppId.java:25)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:140)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:490)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:678)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:408)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:853)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1587)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)
2020-12-24 15:37:01.165-08 ERROR c.m.a.i.perfcounter.JniPCConnector - Failed to fetch current process instance name, process counters for for the process level will not be activated.
2020-12-24 15:37:01.196-08 WARN  c.m.a.i.perfcounter.JniPCConnector - Performance coutner registration failed for Processor \ % Processor Time [_Total]
2020-12-24 15:37:01.196-08 ERROR c.m.a.i.p.ProcessBuiltInPerformanceCountersFactory - Failed to create WindowsPerformanceCounterAsPC: 'java.lang.Exception: Cannot translate instance name: Unknown current instance name'
2020-12-24 15:37:18.571-08 INFO  c.m.applicationinsights.agent - ApplicationInsights Java Agent started successfully
2020-12-24 15:37:47.761-08 ERROR c.m.a.w.i.c.InstrumentationKeyResolver - InstrumentationKeyResolver - failed to resolve instrumentation key: 70f8c11f-81cc-427f-ae26-ebf628f7c2dd

**Comment by trask** [comment] 2021-03-24 05:47
hi @raytapan, I'm hoping the `java.nio.BufferUnderflowException` issue is resolved now in [3.0.3-BETA.2](https://github.com/microsoft/ApplicationInsights-Java/releases/tag/3.0.3-BETA.2)

**Comment by raytapan** [comment] 2021-03-24 17:05
@trask Thanks for taking care and letting me know. I will have a stab at it and keep you posted.

**Comment by trask** [comment] 2021-04-05 20:18
3.0.3 is released: https://github.com/microsoft/ApplicationInsights-Java/releases/tag/3.0.3

**Closed by trask** 2021-04-05 20:18 UTC
Labels: Team-Triaged
