### ISSUE TITLE
Unhandled exceptions lead to a never ending stream of exception reports

### ISSUE THREAD

**Issue by tobiasdiez** [microsoft/ApplicationInsights-Java#515] opened 2018-01-05 17:37 UTC
We are running into a strange problem. Sometimes, when an unhandled exception occurs, it it logged multiple times (> 10.000 times) until the azure service hits it daily limit. 
I tried to replicate the problem but was not successful, but I want to share my analysis nonetheless in the hope that somebody has an idea about the cause.

The code in question is pretty straightforward:
````java
        Future<?> future = executorService.submit(runnable);
        while (true) {
            try {
                future.get();
                return;
            } catch (InterruptedException ignored) {
                // Ignored
            } catch (ExecutionException e) {
                LOGGER.error("Problem executing command", e);
            }
}
````
https://github.com/JabRef/jabref/blob/d6435d56ddef570a6b00927c8e8aa241d1f24a0b/src/main/java/org/jabref/JabRefExecutorService.java#L104-L114

If an exception happens in the `runnable`, then it is catched and logged via log4j. The ApplicationInsights service is [registered as an appender](https://github.com/JabRef/jabref/blob/d6435d56ddef570a6b00927c8e8aa241d1f24a0b/src/main/resources/log4j2.xml#L20-L23) and thus errors are getting reported in azure. That works perfectly but in the above code. For some reason, the very same exception is send to azure endless times. 
The same thing also happens with the [fallback exception handler](https://github.com/JabRef/jabref/blob/master/src/main/java/org/jabref/FallbackExceptionHandler.java), which is also just a call to the logger.

The problem does not occur every time (I tried to trigger it manually but was not successful) but happens every couple of days in production (with different exceptions). The only common factor seems to be that the original exception is thrown on a different thread then where the log happens.

A copy of the reported properties:
````
Logger Name: org.jabref.JabRefExecutorService
Thread Name: FileUpdateMonitor (or another thread except the main one)
Method Name: executeInterruptableTaskAndWait
Line Number: 112
Source Type: Log4j:
Class Name: org.jabref.JabRefExecutorService 
File Name: JabRefExecutorService.java
````
If you want to have a look at the original data, the azure account is registered on tobias at tobiasdiez de.

**Comment by dhaval24** [comment] 2018-01-07 18:02
@tobiasdiez this seems to be very strange. So if I get this correctly, when catching exceptions by yourself in the code, you use Log4j to report them as logs to AI. However, when there is an unhandled exception that occurs, there are no logger calls, and AI reports this as ExceptionTelemety item. 

Sorry, I am bit confused with the different threads that you mentioned. If you can clarify that a bit would be great. Also are you finding this problem with 2.0.0-BETA version of the SDK ?

@grlima @littleaj we would like to have a look around the ExceptionTelemetry story as this kind of issues can be nasty.

**Comment by tobiasdiez** [comment] 2018-01-08 00:23
Thanks for your assistance and sorry for being not clear enough. The situation is the following:
- Exception is thrown somewhere (A)
- and latter catched somewhere else (B)
- There it is only passed to Log4j via `Log.error`.
- AI is registered as a log appender in Log4j and thus is notified about the error and sends it to your severs.

In general, this works like a charm. However, is some rare instance AI reports this one exception as thousands identical errors. The only joint feature in these exceptional cases seems to be that throwing the exception (A) occurs on a different thread then the logging (B). Maybe the ExceptionTelemetry you mention kicks in (still in thread A) although the exception is already handled in thread B? (but this does not really explains why it is logged several thousand times)

**Comment by dhaval24** [comment] 2018-01-08 00:41
@tobiasdiez thank you for the explanation. This seems to be puzzling. Yes I agree in the worst case there should be two instances of this noted to AI. One using exception telemtry and other as Trace sent from Log4j. It should definitely not be thousands to an extent that you hit the daily limit. This can be a complicated threading issue which I cannot assert for sure (may be a thread starts running and is never stopped, just speculating!) and this can be on either side AI SDK end or may be on your code base just not sure. It would be hard to debug unless we get an exact reproduction.  Still I will look at the ExceptionTelemetry and Log4j code to see if something is going wrong there. Just to clarify - Are you seeing multiple Log4J traces for same exception or multiple exception telemetry objects? Could you attach the snapshot taken from your analytics portal, by running a query - "traces | where timestap > ago (5h) | summarize count() "

After running the above query please also run - "traces | take 10" to see all of them are exactly similar.  PS: These instructions are only if they are occurring for Log4J errors.

**Comment by tobiasdiez** [comment] 2018-01-08 01:49
Thanks for looking at this issue!

If errors are logged as errors in log4j, then they also appear in the `exceptions` table. In particular, all these duplicate errors occur there (and not as traces). I appended the result of `exceptions | take 10` during in the time period with a lot of exceptions (it's a csv file, but renamed to txt in order to upload it to github). As you see the data is the same except that the timestamp changes and the itemid is increased for each reported error.
Here is also a screenshot of the counts:
![image](https://user-images.githubusercontent.com/5037600/34656663-935b0a3e-f41d-11e7-9801-56b23fcad7da.png)
So I was slightly wrong: the reported exceptions do stop at some point (even before hitting the data limit but are still many).
[query_data.txt](https://github.com/Microsoft/ApplicationInsights-Java/files/1610425/query_data.txt)

**Comment by dhaval24** [comment] 2018-01-08 01:55
@tobiasdiez from the telemetry csv I see that you are using Java SDK version 1.0.9. Could you please update to 2.0.0-BETA and try this out? We implemented the new schema and fixed several sanitization issues in this version so may be this problem might have been eliminated as our backend now respects new schema better. Let me know if this is possible for you.

**Comment by tobiasdiez** [comment] 2018-01-08 10:42
We currently can't upgrade to the beta because of https://github.com/Microsoft/ApplicationInsights-Java/issues/497. However, we will try out beta 2.0.1 as soon as it is released!

**Comment by dhaval24** [comment] 2018-01-08 18:35
got it! We would try and see if this issue replicates at our end and keep it open here so if someone else has found steps to replicate they can help.

**Comment by dhaval24** [comment] 2018-03-03 17:56
@tobiasdiez do you still see this issue anywhere in 2.0.1 version of the SDK? I haven't been able to reproduce a similar problem in my setup.

**Comment by tobiasdiez** [comment] 2018-03-03 18:27
It may still take a few weeks until we release a new version of our app with the new 2.0.1 version. I'll keep you updated!

**Comment by dhaval24** [comment] 2018-03-03 18:28
👍

**Comment by dhaval24** [comment] 2018-04-26 14:46
@tobiasdiez have you ever seen this with our latest SDKs ? If not please let us know so we can close this.

**Comment by tobiasdiez** [comment] 2018-04-26 16:32
Today, we've finally released a new version of our application using the updated AI-SDK. Thus I can say more about it after the users tested the new version in the next couple of days.

**Comment by tobiasdiez** [comment] 2018-05-30 17:03
Sadly, the problem still persists even with the most recent version of the framework.

I tried to further investigate but I'm running out of ideas. The problem is that exceptions that trigger the bug do not contain stack trace information. 
From all reported exceptions
![image](https://user-images.githubusercontent.com/5037600/40735080-86126628-643a-11e8-9182-57df79420997.png)
only a very small fraction of "real" exceptions has information about the failing method (`method != "Unknown"`)
![image](https://user-images.githubusercontent.com/5037600/40735024-66e14670-643a-11e8-98f7-1195735f3b5a.png)

The only clue I have so far is that those multiple-logged errors are always logged by the [UncaughtExceptionHandler](https://github.com/JabRef/jabref/blob/master/src/main/java/org/jabref/FallbackExceptionHandler.java) (they have logger name = FallbackExceptionHandler). I guess AI has problems when exceptions are unhandled and still logged via this fallback handler.

**Comment by littleaj** [comment] 2019-07-31 18:33
@tobiasdiez Do you still see this issue with the latest version, 2.4.0?

**Comment by tobiasdiez** [comment] 2019-08-27 22:38
Yes! We updated on July 11 to 2.4.0 but on July 23 a user triggered an error leading to 4.000 reports. The reported exceptions look as follows:
![image](https://user-images.githubusercontent.com/5037600/63812792-c953cd80-c92b-11e9-8731-231faa35d1d1.png)
and stack trace
````
java.lang.NullPointerException:
   at com.sun.javafx.collections.ListListenerHelper$Generic.fireValueChangedEvent (ListListenerHelper.java329)
   at com.sun.javafx.collections.ListListenerHelper.fireValueChangedEvent (ListListenerHelper.java73)
   at javafx.collections.FXCollections$SynchronizedObservableList.lambda$new$0 (FXCollections.java1178)
   at javafx.collections.WeakListChangeListener.onChanged (WeakListChangeListener.java88)
   at com.sun.javafx.collections.ListListenerHelper$SingleChange.fireValueChangedEvent (ListListenerHelper.java164)
   at com.sun.javafx.collections.ListListenerHelper.fireValueChangedEvent (ListListenerHelper.java73)
   at javafx.collections.ObservableListBase.fireChange (ObservableListBase.java233)
   at javafx.collections.ListChangeBuilder.commit (ListChangeBuilder.java485)
   at javafx.collections.ListChangeBuilder.endChange (ListChangeBuilder.java541)
   at javafx.collections.ObservableListBase.endChange (ObservableListBase.java205)
   at com.sun.javafx.collections.ObservableListWrapper.access$200 (ObservableListWrapper.java45)
   at com.sun.javafx.collections.ObservableListWrapper$1$1.invalidated (ObservableListWrapper.java75)
   at com.sun.javafx.collections.MapListenerHelper$Generic.fireValueChangedEvent (MapListenerHelper.java320)
   at com.sun.javafx.collections.MapListenerHelper.fireValueChangedEvent (MapListenerHelper.java72)
   at com.sun.javafx.collections.ObservableMapWrapper.callObservers (ObservableMapWrapper.java115)
   at com.sun.javafx.collections.ObservableMapWrapper.put (ObservableMapWrapper.java173)
   at org.jabref.model.entry.BibEntry.setField (BibEntry.java413)
   at org.jabref.model.entry.BibEntry.setField (BibEntry.java439)
   at org.jabref.gui.fieldeditors.AbstractEditorViewModel.lambda$bindToEntry$409 (AbstractEditorViewModel.java66)
   at org.jabref.gui.util.BindingsHelper$BidirectionalBinding.updateLocked (BindingsHelper.java234)
   at org.jabref.gui.util.BindingsHelper$BidirectionalBinding.changedA (BindingsHelper.java223)
   at com.sun.javafx.binding.ExpressionHelper$Generic.fireValueChangedEvent (ExpressionHelper.java361)
   at com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent (ExpressionHelper.java81)
   at javafx.beans.property.StringPropertyBase.fireValueChangedEvent (StringPropertyBase.java103)
   at javafx.beans.property.StringPropertyBase.markInvalid (StringPropertyBase.java110)
   at javafx.beans.property.StringPropertyBase.set (StringPropertyBase.java144)
   at javafx.beans.property.StringPropertyBase.set (StringPropertyBase.java49)
   at javafx.beans.property.StringProperty.setValue (StringProperty.java65)
   at javafx.beans.property.StringProperty.setValue (StringProperty.java57)
   at com.sun.javafx.binding.BidirectionalBinding$TypedGenericBidirectionalBinding.changed (BidirectionalBinding.java599)
   at com.sun.javafx.binding.ExpressionHelper$Generic.fireValueChangedEvent (ExpressionHelper.java361)
   at com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent (ExpressionHelper.java81)
   at javafx.scene.control.TextInputControl$TextProperty.fireValueChangedEvent (TextInputControl.java1389)
   at javafx.scene.control.TextInputControl$TextProperty.markInvalid (TextInputControl.java1393)
   at javafx.scene.control.TextInputControl$TextProperty.controlContentHasChanged (TextInputControl.java1332)
   at javafx.scene.control.TextInputControl$TextProperty.access$1600 (TextInputControl.java1300)
   at javafx.scene.control.TextInputControl.lambda$new$0 (TextInputControl.java139)
   at com.sun.javafx.binding.ExpressionHelper$SingleInvalidation.fireValueChangedEvent (ExpressionHelper.java137)
   at com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent (ExpressionHelper.java81)
   at javafx.scene.control.TextField$TextFieldContent.insert (TextField.java87)
   at javafx.scene.control.TextInputControl.replaceText (TextInputControl.java1204)
   at javafx.scene.control.TextInputControl.updateContent (TextInputControl.java556)
   at javafx.scene.control.TextInputControl.replaceText (TextInputControl.java548)
   at javafx.scene.control.TextInputControl.replaceText (TextInputControl.java510)
   at javafx.scene.control.TextInputControl.replaceSelection (TextInputControl.java1084)
   at javafx.scene.control.TextInputControl.paste (TextInputControl.java626)
   at com.sun.javafx.scene.control.behavior.TextInputControlBehavior.paste (TextInputControlBehavior.java356)
   at com.sun.javafx.scene.control.behavior.TextInputControlBehavior.callAction (TextInputControlBehavior.java141)
   at com.sun.javafx.scene.control.behavior.BehaviorBase.callActionForEvent (BehaviorBase.java218)
   at com.sun.javafx.scene.control.behavior.TextInputControlBehavior.callActionForEvent (TextInputControlBehavior.java127)
   at com.sun.javafx.scene.control.behavior.BehaviorBase.lambda$new$0 (BehaviorBase.java135)
   at com.sun.javafx.event.CompositeEventHandler$NormalEventHandlerRecord.handleBubblingEvent (CompositeEventHandler.java218)
   at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent (CompositeEventHandler.java80)
   at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent (EventHandlerManager.java238)
   at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent (EventHandlerManager.java191)
   at com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent (CompositeEventDispatcher.java59)
   at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent (BasicEventDispatcher.java58)
   at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent (EventDispatchChainImpl.java114)
   at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent (BasicEventDispatcher.java56)
   at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent (EventDispatchChainImpl.java114)
   at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent (BasicEventDispatcher.java56)
   at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent (EventDispatchChainImpl.java114)
   at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent (BasicEventDispatcher.java56)
   at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent (EventDispatchChainImpl.java114)
   at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent (BasicEventDispatcher.java56)
   at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent (EventDispatchChainImpl.java114)
   at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent (BasicEventDispatcher.java56)
   at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent (EventDispatchChainImpl.java114)
   at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent (BasicEventDispatcher.java56)
   at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent (EventDispatchChainImpl.java114)
   at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent (BasicEventDispatcher.java56)
   at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent (EventDispatchChainImpl.java114)
   at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent (BasicEventDispatcher.java56)
   at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent (EventDispatchChainImpl.java114)
   at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent (BasicEventDispatcher.java56)
   at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent (EventDispatchChainImpl.java114)
   at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent (BasicEventDispatcher.java56)
   at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent (EventDispatchChainImpl.java114)
   at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent (BasicEventDispatcher.java56)
   at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent (EventDispatchChainImpl.java114)
   at com.sun.javafx.event.EventUtil.fireEventImpl (EventUtil.java74)
   at com.sun.javafx.event.EventUtil.fireEvent (EventUtil.java54)
   at javafx.event.Event.fireEvent (Event.java198)
   at javafx.scene.Scene$KeyHandler.process (Scene.java3964)
   at javafx.scene.Scene$KeyHandler.access$1800 (Scene.java3910)
   at javafx.scene.Scene.impl_processKeyEvent (Scene.java2040)
   at javafx.scene.Scene$ScenePeerListener.keyEvent (Scene.java2501)
   at com.sun.javafx.tk.quantum.GlassViewEventHandler$KeyEventNotification.run (GlassViewEventHandler.java217)
   at com.sun.javafx.tk.quantum.GlassViewEventHandler$KeyEventNotification.run (GlassViewEventHandler.java149)
   at com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleKeyEvent$1 (GlassViewEventHandler.java248)
   at com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock (QuantumToolkit.java410)
   at com.sun.javafx.tk.quantum.GlassViewEventHandler.handleKeyEvent (GlassViewEventHandler.java247)
   at com.sun.glass.ui.View.handleKeyEvent (View.java546)
   at com.sun.glass.ui.View.notifyKey (View.java966)
   at com.sun.glass.ui.win.WinApplication.lambda$null$3 (WinApplication.java177)
   at java.lang.Thread.run
````

The common theme is that all duplicate exceptions are reported in the [FallbackExceptionHandler](https://github.com/JabRef/jabref/blob/master/src/main/java/org/jabref/FallbackExceptionHandler.java#L21) via `Logger.error`. Let me know if you need further information.

**Closed** 2020-06-10 04:42 UTC
Labels: Question, Team-Triaged, help wanted

**Comment by tobiasdiez** [comment] 2021-07-06 09:39
Just for the record, we still see this problem.

From what I get from the logs, it's one exception that occurs at the users side but is then logged multiple times in the application insights.
