### ISSUE TITLE
Failed to create com.microsoft.applicationinsights.channel.concrete.inprocess.InProcessTelemetryChannel, null

### ISSUE THREAD

**Issue by TheRubble** [Microsoft/ApplicationInsights-Java#351] opened 2016-12-17 14:43 UTC
Hi,

Completely new to Java so this could be something I've done wrong however after much investigation I don't believe it is.

Using version 1.0.6 with JDK 8, when initialising from the ApplicationInsights.xml file I get the above error.

It appears to fire when the getChannel method is called.

Any ideas?

Thanks

**Comment by JosJanssen** [comment] 2017-01-02 20:50
I'm having the same issue:

Failed to create com.microsoft.applicationinsights.channel.concrete.inprocess.InProcessTelemetryChannel, null

**Comment by Dmitry-Matveev** [comment] 2017-02-02 01:53
In the release 1.0.7, AI Core JAR was packaged with all dependencies (so-called shadow jar), so I would expect less issues with apache 43 connections creation. Please give it a try.

**Comment by beckylino** [comment] 2017-08-02 20:30
@TheRubble and @JosJanssen were you able to try the fix recommended by @Dmitry-Matveev ?

**Comment by JosJanssen** [comment] 2017-08-03 06:45
@beckylino 

I remember we found another solution to get it working. 
But we abandoned that project shortly afterwards, so we didn't needed another fix.

**Comment by dhaval24** [comment] 2017-10-02 00:32
@Dmitry-Matveev I have not seen this issue reproducing in the current version of the SDK.. Is it safe to close this issue now? I believe JosJanssen had also found a way to get it working according to his previous comment.

**Comment by Dmitry-Matveev** [comment] 2017-10-05 01:53
@dhaval24, we've updated Http Client to version 4.5.3 since then and packaged it as a Shadow Jar dependencies with our own namespace. It might've helped, of course. If we have a repro with 1.0.6 and it goes away as soon as we update app onto 1.0.10 - that's a definite signal to close the bug.
However, we have enough reason to believe that the aforementioned fixes should've addressed the issue and we can close the bug as is (but with some lower confidence).

**Closed by Dmitry-Matveev** 2017-10-05 01:53 UTC
Labels: bug

**Comment by dhaval24** [comment] 2017-10-05 02:25
@Dmitry-Matveev thanks for the update and closing the bug.
