### ISSUE TITLE
Exception tracked via AppInsights Log4j Implementation doesnt forward the logger message that gets set as a part of Exception

### ISSUE THREAD

**Issue by SaiVikas-Dharmaraju** [Microsoft/ApplicationInsights-Java#400] opened 2017-07-10 09:47 UTC
The current issues  lies in App Insights Appender implementation where formatted message is not being set when we log our errors:

For Example if I log my exception as below , the log event message is not being tracked as a part of the ExceptionTelemetry Event.
log.error("Logging Exception in Impl", exception);

App Insights Appender implementation doesn't set logger event message as a part of Exception Telemetry.

![log4j_appender](https://user-images.githubusercontent.com/30042420/28012217-bd028af8-6582-11e7-8da2-c5951996d0b9.png)

**Comment by SaiVikas-Dharmaraju** [comment] 2017-07-13 10:45
Any update on the above reported issue??

**Comment by Dmitry-Matveev** [comment] 2017-07-17 17:54
@SaiVikas-Dharmaraju , `new ExceptionTelemetry(exceptionObj)` is using that [exception object message ](https://github.com/Microsoft/ApplicationInsights-Java/blob/10becb08b728463c9415484d974f47dd4d1e80d0/core/src/main/java/com/microsoft/applicationinsights/telemetry/ExceptionTelemetry.java#L190)(usually not empty in case of the exception). As per my understanding of this code that was a designed implementation.

Do you think it makes more sense to override the exception's original message with the trace message within appender? It looks like doing this will hide the original exception and might make it less useful in some cases.

**Comment by SaiVikas-Dharmaraju** [comment] 2017-07-18 06:27
@Dmitry-Matveev , like you said we shouldn't override the exception's original message with the LogeEvent message. What we are looking right now is a mechanism to track the formattedMessage along with the exception in the appender, something like the below in the appender 

![ai_400](https://user-images.githubusercontent.com/30042420/28303276-eebf756e-6baf-11e7-8a6f-e16d5dc7cd2b.png)

Hope this is helpful.

**Comment by Dmitry-Matveev** [comment] 2017-07-19 17:54
Thanks for the clarification, @SaiVikas-Dharmaraju . I'm marking it as an enhancement request for the future iteration (subject to triage). It makes total sense to me to preserve the trace message itself, otherwise it's completely lost and the collected exception lacks a bit of the context.

**Comment by dhaval24** [comment] 2018-01-10 00:57
@SaiVikas-Dharmaraju I recently pushed a PR for some improvements in Log4J Appender #514 However, this particular issue is still pending. Could you tell me how important this particular one is for you?

**Comment by SaiVikas-Dharmaraju** [comment] 2018-01-10 05:52
@dhaval24 : It's important for us , since it's not supported in the Appenders  that is provided we are maintaining our own set of appenders for various logging implementations, Like Log4j, Log4j2, JUL and so on.

Also we recently noted that values that are set as part of ThreadMDC is not being pushed from the LogBack appender to AI , Can you guys check if you are pushing the values that are set in MDC in logging frameworks.

**Comment by dhaval24** [comment] 2018-01-10 05:59
@SaiVikas-Dharmaraju thanks for this information. Would #514 too add value for you guys? Did you had a chance to look at it?

Also for the LogBack could you please file another Github issue so it could be tracked better, with some steps to reproduce it? Personally I am not aware of what values are being set by ThreadMDC. Apologies if it's too obvious question.

**Comment by dhaval24** [comment] 2018-01-28 03:37
@SaiVikas-Dharmaraju  please have a look at #539. It adds the above requested enhancement where Logger messages were being dropped in case of reporting exceptions via loggers.

**Comment by dhaval24** [comment] 2018-02-22 07:13
Closing this as #539 fixed it.

**Closed by dhaval24** 2018-02-22 07:13 UTC
Labels: enhancement
