### ISSUE TITLE
Metrics don't upload correctly on short-running applications

### ISSUE THREAD

**Issue by iadir** [microsoft/ApplicationInsights-Java#891] opened 2019-03-29 19:13 UTC
### Expected behavior
Client should properly drain the queue and upload metrics when app execution ends.

### Actual behavior
On a short running application, the client doesn't have enough time to upload the metrics before the app shuts down. 

### To Reproduce
- Call .trackMetric() right before application execution ends

### System information
Please provide the following information:
 - SDK Version: 2.3.1
 - OS type and version: Ubuntu
 - Application Server type and version (if applicable): Spark app running in a HDInsight cluster
 - Using spring-boot? No
 - Additional relevant libraries (with version, if applicable): Using applicationinsights-core package

### Logs
AI: ERROR 19-03-2019 18:15:00.268+0000, 22(ActiveTransmissionNetworkOutput_1-0): Failed to send, unexpected exception.
Stack Trace:
java.lang.IllegalStateException: Connection pool shut down
    at com.microsoft.applicationinsights.core.dependencies.http.util.Asserts.check(Asserts.java:34)
    at com.microsoft.applicationinsights.core.dependencies.http.pool.AbstractConnPool.lease(AbstractConnPool.java:189)
    at com.microsoft.applicationinsights.core.dependencies.http.impl.conn.PoolingHttpClientConnectionManager.requestConnection(PoolingHttpClientConnectionManager.java:257)
    at com.microsoft.applicationinsights.core.dependencies.http.impl.execchain.MainClientExec.execute(MainClientExec.java:176)
    at com.microsoft.applicationinsights.core.dependencies.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:185)
    at com.microsoft.applicationinsights.core.dependencies.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
    at com.microsoft.applicationinsights.core.dependencies.http.impl.execchain.RedirectExec.execute(RedirectExec.java:111)
    at com.microsoft.applicationinsights.core.dependencies.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
    at com.microsoft.applicationinsights.core.dependencies.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
    at com.microsoft.applicationinsights.core.dependencies.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:108)
    at com.microsoft.applicationinsights.core.dependencies.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:56)
    at com.microsoft.applicationinsights.internal.channel.common.ApacheSender43.sendPostRequest(ApacheSender43.java:75)
    at com.microsoft.applicationinsights.internal.channel.common.TransmissionNetworkOutput.send(TransmissionNetworkOutput.java:185)
    at com.microsoft.applicationinsights.internal.channel.common.ActiveTransmissionNetworkOutput$1.run(ActiveTransmissionNetworkOutput.java:79)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
    at java.lang.Thread.run(Thread.java:748)
 
AI: TRACE 19-03-2019 18:15:00.269+0000, 22(ActiveTransmissionNetworkOutput_1-0): Http response code 0 not handled by com.microsoft.applicationinsights.internal.channel.common.ErrorHandler
AI: TRACE 19-03-2019 18:15:00.269+0000, 22(ActiveTransmissionNetworkOutput_1-0): Http response code 0 not handled by com.microsoft.applicationinsights.internal.channel.common.PartialSuccessHandler
AI: TRACE 19-03-2019 18:15:00.269+0000, 22(ActiveTransmissionNetworkOutput_1-0): Http response code 0 not handled by com.microsoft.applicationinsights.internal.channel.common.ThrottlingHandler.

**Comment by dhaval24** [comment] 2019-03-30 03:42
This is expected and by design. You can try to reduce the buffer flush time to 1 second. However, it is still possible that a sigkill / system.exit(0) command happens and you force stop the thread responsible to send telemetry. Best is to wait a few seconds based on flush interval before letting program exit.

**Comment by trask** [comment] 2020-06-10 03:57
This is resolved in [3.0 Preview](https://docs.microsoft.com/en-us/azure/azure-monitor/app/java-in-process-agent) (buffer is flushed on JVM shutdown hook)

**Closed by trask** 2020-06-10 03:57 UTC
Labels: Team-Triaged, enhancement
