### ISSUE TITLE
trackException calls are not showing up in Exceptions section of App Insights

### ISSUE THREAD

**Issue by reutann** [Microsoft/ApplicationInsights-Java#771] opened 2018-11-10 13:42 UTC
### Expected behavior
The below should log an exception to AI
```
@Log4j2
@RestController
@RequestMapping("/user")
public class UserController {
	@Autowired
	TelemetryClient appInsights;

	@GetMapping("/error")
	@ResponseBody
	public String error() {
		IllegalArgumentException e = new IllegalArgumentException("App Insights test");
		appInsights.trackTrace("I'm about to test exceptions");
		appInsights.trackException(e);
		appInsights.trackException(new ExceptionTelemetry(e));
		log.error("Uh oh!", e);
		throw e;
	}
}
```

### Actual behavior
The exception is never logged and no failure messages are provided. Note that the trace that is indeed showing up in App Insights.

#### Sample Application
If applicable, provide a sample application which reproduces the issue.
![image](https://user-images.githubusercontent.com/25594617/48301952-a9017200-e4c3-11e8-9245-7cc55d481b3e.png)
![image](https://user-images.githubusercontent.com/25594617/48301961-b6b6f780-e4c3-11e8-97d7-fee53027e00b.png)
+ the above controller

### System information
Please provide the following information:
 - SDK Version: applicationinsights-spring-boot-starter 1.1.0-BETA, 
 - OS type and version: Win 10
 - Application Server type and version (if applicable): Spring boot, 2.x
 - Using spring-boot? Yes
 - Additional relevant libraries (with version, if applicable):

### Logs
[Turn on SDK logs](https://docs.microsoft.com/en-us/azure/application-insights/app-insights-java-troubleshoot#debug-data-from-the-sdk) and attach/paste them to the issue. If using an application server, also attach any relevant server logs.

_Be sure to remove any private information from the logs before posting!_

Not available when using spring boot

### Screenshots
![image](https://user-images.githubusercontent.com/25594617/48301997-6e4c0980-e4c4-11e8-9623-443b6b5cfd9b.png)
![image](https://user-images.githubusercontent.com/25594617/48302006-8885e780-e4c4-11e8-95a2-e09c8f5044ba.png)

**Comment by dhaval24** [comment] 2018-11-10 20:46
@reutann thanks for creating an issue. I will verify the behavior and update here. Could you please turn the AI-SDK logs on and let us know if there are any exceptions coming out. You can add the following property to application.properties file.
`azure.application-insights.logger.level=trace`

**Comment by dhaval24** [comment] 2018-11-21 03:35
@reutann I haven't been able to reproduce this issue. If you can provide with a repro / trimmed down version of the application I can help you here. Let me know.

**Comment by dhaval24** [comment] 2018-12-16 18:10
@reutann I have tried exactly your configuration and it works for me. 

```Java
 @Autowired
    TelemetryClient telemetryClient;

    @GetMapping("/hello")
    public String hello() {

        telemetryClient.trackEvent("hello");
        telemetryClient.trackException(new Exception("This is exception"));
        telemetryClient.trackException(new ExceptionTelemetry(new Exception("Track exception via method")));

        return "hello application insights";

    }
```

This is what I tried and I can see the exceptions on the portal 
<img width="1166" alt="screen shot 2018-12-16 at 10 08 57 am" src="https://user-images.githubusercontent.com/16353121/50057108-b0e3b000-011a-11e9-8fa0-fa74b7ce3294.png">

I am closing this issue for now. Please provide a trimmed down sample application if you are still running into issues which I can use to reproduce the issue and diagnose on my side.

**Closed by dhaval24** 2018-12-16 18:10 UTC
Labels: SpringBoot
